### ISSUE TITLE
Dapr quits unexpectedly while running the DistributedLock example

### ISSUE THREAD

**Issue by yash-nisar** [dapr/dotnet-sdk#1022]
## Expected Behavior

Dapr quits unexpectedly because the localstorage component yaml doesn't have the correct metadata format.
https://github.com/dapr/dotnet-sdk/blob/master/examples/Client/DistributedLock/Components/localstorage.yaml#L11 should have the absolute path for `rootPath`. See https://docs.dapr.io/reference/components-reference/supported-bindings/localstorage/#spec-metadata-fields

## Actual Behavior

Dapr should not quit unexpectedly while running the DistributedLock example.

## Steps to Reproduce the Problem
Follow the instructions to run the DistributedLock example: https://github.com/dapr/dotnet-sdk/tree/master/examples/Client/DistributedLock

**Comment by halspang** [comment]
Closing as the error was on Dapr's side.
