### ISSUE TITLE
[Workflow] Improvements to Dapr Client APIs for Workflow

### ISSUE THREAD

**Issue by cgillum** [dapr/dotnet-sdk#1027]
## Describe the proposal

I'm proposing we make the following changes to the workflow management APIs in the .NET Dapr client. This is based on the feedback we got from the v1.10 alpha release of the workflow management APIs.

* In `StartWorkflowAsync`, make `instanceId` and `input` parameters optional.

```csharp
public abstract Task<WorkflowReference> StartWorkflowAsync(
    string workflowComponent,
    string workflowName,
    string? instanceId = null,
    object? input = null,
    IReadOnlyDictionary<string, string> workflowOptions = default,
    CancellationToken cancellationToken = default);
```

* Replace `GetWorkflowResponse` with `WorkflowState` from the authoring SDK
* Add `WorkflowFailureDetails` property to `WorkflowState` so that users can obtain more information about a workflow failure.

```csharp
public record WorkflowFailureDetails(
    string ErrorType,
    string ErrorMessage,
    string? StackTrace,
    WorkflowFailureDetails? InnerFailure)
```

* Add the following methods to `DaprClient`:

```csharp
// Waits for a workflow to start running and then returns the state associated with that workflow
public WorkflowState WaitForWorkflowStartAsync(
    string instanceId,
    bool fetchPayloads = false,
    CancellationToken cancellationToken = default);

// Wait for workflow the workflow to run to completion, be terminated, or fail
public WorkflowState WaitForWorkflowCompletionAsync(
    string instanceId,
    bool fetchPayloads = true,
    CancellationToken cancellationToken = default);
```

/cc @nyemade-uversky

**Comment by cgillum** [comment]
As part of this work, we should also update the console app sample to use the updated Dapr client instead of workflow engine client. That will help us be confident that the new API surface area is sufficient for real use.

**Comment by msfussell** [comment]
> 

I also added this issue in the Quickstarts repo https://github.com/dapr/quickstarts/issues/830
