### ISSUE TITLE
What would cause dapr service invocation to get stuck

### ISSUE THREAD

**Issue by ngorden** [dapr/dotnet-sdk#1048]
I have a microservice that connects an IoT device to a server. When a device is connected to my service, I make a dapr service invocation to another microservice to receive a GUID to identify that device before continuing. 

If I am running my application locally in a docker-desktop k8s cluster (Windows 10, 64GB RAM), alongside my other services, the behavior I see is that my application hangs on the dapr service invocation. I do not get a 500 response; I do not timeout; the application just hangs. I only get this issue locally, it doesn't happen when the service is running in the cloud, which leads me to believe my app is correctly configured.

I can resolve the issue by connecting a second device (second dapr service invocation), and I will get  no further hangs. My question is: what can I do to not hang on my first service invocation?

<details>
<summary>Dapr sidecar logs:</summary>

time="2023-02-28T19:51:47.024017444Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 2368ms" app_id=connector-app-id instance=connector-596894d64c-8q9qx scope=dapr.runtime type=log ver=1.9.5

time="2023-02-28T19:51:47.02413965Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005" app_id=connector-app-id instance=connector-596894d64c-8q9qx scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5

time="2023-02-28T19:51:47.029047163Z" level=debug msg="established connection to placement service at dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005" app_id=connector-app-id instance=connector-596894d64c-8q9qx scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5

time="2023-02-28T19:51:47.02939001Z" level=debug msg="placement order received: lock" app_id=connector-app-id instance=connector-596894d64c-8q9qx scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5

time="2023-02-28T19:51:47.029425142Z" level=debug msg="placement order received: update" app_id=connector-app-id instance=connector-596894d64c-8q9qx scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5

time="2023-02-28T19:51:47.029434856Z" level=info msg="placement tables updated, version: 0" app_id=connector-app-id instance=connector-596894d64c-8q9qx scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5

time="2023-02-28T19:51:47.02944142Z" level=debug msg="placement order received: unlock" app_id=connector-app-id instance=connector-596894d64c-8q9qx scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5

time="2023-02-28T19:52:29.115192118Z" level=debug msg="retry count: 1, grpc call failed, ns: demo, addr: assignment-app-id-dapr.demo.svc.cluster.local:50002, appid: assignment-app-id, err: rpc error: code = Unavailable desc = last resolver error: produced zero addresses" app_id=connector-app-id instance=connector-596894d64c-8q9qx scope=dapr.runtime.direct_messaging type=log ver=1.9.5

time="2023-02-28T19:52:30.121124314Z" level=debug msg="retry count: 2, grpc call failed, ns: demo, addr: assignment-app-id-dapr.demo.svc.cluster.local:50002, appid: assignment-app-id, err: rpc error: code = Unavailable desc = last resolver error: produced zero addresses" app_id=connector-app-id instance=connector-596894d64c-8q9qx scope=dapr.runtime.direct_messaging type=log ver=1.9.5

time="2023-02-28T19:52:31.129112507Z" level=debug msg="retry count: 3, grpc call failed, ns: demo, addr: assignment-app-id-dapr.demo.svc.cluster.local:50002, appid: assignment-app-id, err: rpc error: code = Unavailable desc = last resolver error: produced zero addresses" app_id=connector-app-id instance=connector-596894d64c-8q9qx scope=dapr.runtime.direct_messaging type=log ver=1.9.5
</details>

**Comment by halspang** [comment]
@ngorden - Do the retries continue forever? Or do they stop? The error appears to be about the name resolution server not picking up anything. So I wonder if it's a matter of timing for that first one. To debug it more I'd probably need to see the code though.

**Comment by ngorden** [comment]
@halspang thanks for the response.

The logs I shared in my original post are all of the logs I have. Nothing more. One additional piece to this: I see logs in the second service that the request is received and a response is sent back

**Comment by ngorden** [comment]
closing this issue as it was in fact not dapr related
