### ISSUE TITLE
Workflow will break once changes to dapr and components contrib are pushed. Updates to SDK are needed

### ISSUE THREAD

**Issue by RyanLettieri** [dapr/dotnet-sdk#1058]
## Expected Behavior

SDK should function properly.

## Actual Behavior

SDK will not operate properly due to changes to the request structure for starting a workflow.

## Steps to Reproduce the Problem

Attempt to start a workflow.

## Release Note
 This breakage will be a result from the following PRs:
 https://github.com/dapr/components-contrib/pull/2653
 https://github.com/dapr/dapr/pull/6049
 
 These PRs change the structure of the start workflow request to no longer require the "InstanceID" to be wraped by the "WorkflowReference" structure. 

RELEASE NOTE:

**Comment by halspang** [comment]
Closed by: https://github.com/dapr/dotnet-sdk/pull/1087
