### ISSUE TITLE
InvokeMethodAsync return 404 on every second invoke.

### ISSUE THREAD

**Issue by dmitriy-pisarevskiy** [dapr/dotnet-sdk#1076]
Hey, I have local issue with dapr every second invoke with dapr get 404.

For example:
await _daprClient.InvokeMethodAsync<PackageDto>(HttpMethod.Get, _daprSettings.Value.ReceiveAppId,
            $"packages/{packageId}", cancellationToken)

First invoke every time is success, but after that it show 404, then again 200.

Exception details:
An exception occurred while invoking method: 'packages/38' on app-id: 'receive-api'
status
: 
404
title: "Not Found"
traceId: "00-992fb3e951f0fb034b11b87d075af0e2-3684c2f8297ade22-01"
type: "https://httpstatuses.io/404"

Dapr.Client.InvocationException

What is can be?

**Comment by Flern** [comment]
Probably not the case, but I've made plenty of manual errors with local deployments to check the stupid things...  Most "every other" issues I've encountered are when I've somehow managed to get two sidecars running with the same app id, but only one of the sidecars is connected to the expected app.  That causes dapr to round robin the requests and fail every other time.

**Comment by dmitriy-pisarevskiy** [comment]
@Flern @halspang sorry guys, already solved, someone committed change on our docker-compose file with doubled service.
