### ISSUE TITLE
FEATURE PREVIEW: Add Actor State TTL support

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dotnet-sdk#1078]
Add first class API support for Actor State TTL https://github.com/dapr/dapr/issues/5899

A dedicated function to Actor State should be created. Psudo code: `func (key string, value string, ttl duration)`. It should be made clear in the SDK documentation/comments that users should always use this function, unless they have specifically created some kind of Actor State clean up out of band of Dapr or don't have an issue with the Actor State store keep state and grow "forever".

Please see the [go-sdk](https://github.com/dapr/go-sdk/pull/383/files) for implementation reference.

**Comment by JoshVanL** [comment]
UPDATE: Due to the nature of the current implementation of write through caching of actor state and the unavailability of the real TTL expire time of state keys, SDKs will have an inconsistent view of the world when it has a cold cache and the state store has TTL keys. The TTL functionality has been put behind a feature gate in daprd. See https://github.com/dapr/dapr/pull/6400 for more details. This feature is expected to be moved to GA in 1.12.

**Comment by artursouza** [comment]
Can this be added in 1.12?

**Comment by onionhammer** [comment]
Any update on this?

**Comment by sicoyle** [comment]
@srparupu Please let us know if you need help with anything, and when you open a PR with the changes so we can move this issue in the board to "In review"! Thank youuuuu :)

**Comment by halspang** [comment]
This was handled by: https://github.com/dapr/dotnet-sdk/pull/1164
