### ISSUE TITLE
Creating Interface for DaprClient

### ISSUE THREAD

**Issue by shivam-51** [dapr/dotnet-sdk#1094]
## Describe the proposal
Currently there's no Interface for DaprClient which makes it non unit testable. This proposal is to create one such interface for it.

Using: Dapr.Client Version 1.10.0

**Comment by halspang** [comment]
Thanks for opening this issue. Unfortunately, this isn't something we're going to pursue. I see you have already commented in this discussion the last time it happened: https://github.com/dapr/dotnet-sdk/issues/774. The points still stand there that an interface isn't actually ideal for this solution. The main reasons being:

1. Any change to a shipped interface is a breaking change. Given that Dapr continues to expand and add APIs, this is a non-starter.
2. In general, an interface should define a simple contract and should lend themselves to multiple inheritance. Good examples here are things like `IDisposable` and `IComparable`. These interfaces, which could be combined, let you know that this object can be disposed and compared. A client does not really fit into this.

With that being said, we do already provide an abstract class for `DaprClient`. This does allow you to mock the methods in the client or even create your own implementation of it. Yes, there are some methods that are not virtual/abstract in the client but all those methods do call down to a virtual/abstract method. So, there is a way to mock or implement each method already with several examples in that issue as well.
