### ISSUE TITLE
[Workflow] Number of actor keys keeps growing

### ISSUE THREAD

**Issue by clintsinger** [dapr/dotnet-sdk#1109]
## Actual Behavior

When a workflow is executed it is backed by an actor.   It appears that the number of actor keys keeps growing rather than being cleaned up.   This may be contributing to performance issues.

An example from the daprd log
```
{"app_id":"service-b","instance":"41d7c78f6c9d","level":"debug","msg":"TestWorkflow_A: saving 13521 keys to actor state store","scope":"dapr.runtime.wfengine","time":"2023-06-10T00:49:56.808823458Z","type":"log","ver":"1.11.0-rc.9"}
```

## Steps to Reproduce the Problem

Run the https://github.com/clintsinger/dapr-Issue6435 project for some time and observe the number of keys increasing and never decreasing.

## Release Note

RELEASE NOTE:

**Comment by cgillum** [comment]
This was a runtime issue. The fix is here and will be part of the 1.12 runtime release: https://github.com/dapr/dapr/pull/6618. No SDK changes will be required for this fix.
