### ISSUE TITLE
Unable to reference Dapr.Client or Dapr.AspNetCore due to use of netstandard3.0

### ISSUE THREAD

**Issue by philliphoff** [dapr/dotnet-sdk#112]
## Expected Behavior

The reference is added, the package is restored, and the library can be built.

## Actual Behavior

The reference is not added, failing with the error:

```
error NU1202: Package Dapr.Client 0.1.0-preview01 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Dapr.Client 0.1.0-preview01 supports: netstandard3.0 (.NETStandard,Version=v3.0)
```

The issue appears to be due to the fact that `Dapr.Client` assemblies are added to the NuGet package in the `netstandard3.0` folder instead of `netcoreapp3.0` folder (despite being built as `netcoreapp3.0` assemblies).

## Steps to Reproduce the Problem

  1. Create a `netcoreapp3.0` library (e.g. `dotnet new console`).
  1. `dotnet add package Dapr.Client --version 0.1.0-preview01`

**Comment by youngbupark** [comment]
cc/ @amanbha @shalabhms

**Comment by amanbha** [comment]
@philliphoff  Thansk for reporting the issue.
I have uploaded new packages https://www.nuget.org/packages/Dapr.AspNetCore/0.1.0-preview02
These are being indexed now and should be available soon

**Comment by davidfowl** [comment]
@amanbha Why are we using exact version ranges? We shouldn't be. I'll open an issue for that.

**Comment by amanbha** [comment]
> @amanbha Why are we using exact version ranges? We shouldn't be. I'll open an issue for that.

Sure, makes sense.

**Comment by philliphoff** [comment]
Thanks for the quick turnaround!
