### ISSUE TITLE
Upgrade Grpc.Net.Client library (Vulnerability Issue - Connection Confusion)

### ISSUE THREAD

**Issue by tonysneed** [dapr/dotnet-sdk#1137]
### Describe the bug
In our application we found out vulnerability issue (Connection Confusion) regarding Grpc.Net.Client library which this library uses. Issue was found with Veracode scans.

### Dependency graph:
dapr.client 1.10.0 -> grpc.net.client 2.47.0

Please upgrade affected libraries that will use at least grpc.net.client 2.52.0 in which Connection Confusion vulnerability is fixed.

### Additional context
grpc is vulnerable to Connection Confusion. The vulnerability exists when the gRPC HTTP2 stack raised a header size exceeded error, and it skipped parsing the rest of the HPACK frame, which caused any HPACK table mutations also to be skipped, resulting in the desynchronization of HPACK tables between sender and receiver, leading to requests from the proxy being interpreted as containing headers from different proxy clients, allowing an attacker to gain sensitive information and gain access to the system or data exfiltration.

**Comment by philliphoff** [comment]
The Dapr client was updated to `Grpc.Net.Client` 2.52.0 with #1126 which should be included with the upcoming 1.12 release.

**Comment by tonysneed** [comment]
Closing as this is now fixed with the 1.12 release.
