### ISSUE TITLE
Service Invocation - InvocationException doesn't hold the original Exception

### ISSUE THREAD

**Issue by akakarikos** [dapr/dotnet-sdk#1139]
## Expected Behavior

When there is a ServiceA => ServiceB call through the Dapr Service Invocation building block, and an unhandled exception occurs in the target service - ServiceB - then an `InvocationException `is thrown that contains the original Exception as well. Maybe the original exception could reside in the `.InnerException` field of the `InvocationException`.

## Actual Behavior

When there is a ServiceA => ServiceB call through the Dapr Service Invocation building block, and an unhandled exception occurs in the target service - ServiceB - then the Dapr emits a generic InvocationException and does not contain the original exception that occurred in the ServiceB. Instead the .InnerException of the `InvocationException` is an `HttpRequestException` with the generic 500 error.

## Steps to Reproduce the Problem

```
var request = _daprClient.CreateInvokeMethodRequest(method, appId, route, message);
try
{
    return await _daprClient.InvokeMethodAsync<Message>(request);
}
catch (InvocationException invEx)
{
   HttpRequestException innerEx = invEx.InnerException;

   // the original exception cannot be retrieved here.
}
```
Can you please advise how we could achieve the expected behavior?

**Comment by halspang** [comment]
This is by design as including inner exceptions over the wire in a response can be a security concern. In general, the methodology here is to have your other service either provide an appropriate error message or log the exception so you can investigate it on that service.

**Comment by akakarikos** [comment]
Got it @halspang thanks a lot for your input.
