### ISSUE TITLE
Document That Users Can Self-Assign Issues

### ISSUE THREAD

**Issue by cicoyle** [dapr/dotnet-sdk#1149]
Please link to the [daprbot documentation](https://docs.dapr.io/contributing/daprbot/) inside the contributing.md file, so that users know what Github commands they can run in this repo. Based on the dapr-bot.yml they can run the [/assign to self assign issues and a few other commands](https://github.com/dapr/dotnet-sdk/blob/master/.github/workflows/dapr-bot.yml#L45) in this repo.

**Comment by Shubhdeep02** [comment]
@cicoyle I will take this ticekt....

**Comment by Shubhdeep02** [comment]
#1330 fixes this one
