### ISSUE TITLE
Remove deprecated RenameActorReminder methods

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dotnet-sdk#1166]
The RenameActorReminder methods have been removed in the runtime for Dapr 1.13. The methods need to be removed from the SDK.

See [dapr/dapr#6945](https://github.com/dapr/dapr/pull/6945)

> In most SDKs, methods shouldn't be outright removed, but should return an error saying the method is not implemented instead, to prevent compile-time errors.

**Comment by halspang** [comment]
That's correct, the .NET SDK never supported this API.
