### ISSUE TITLE
Problems invoking HTTP services using HttpClient

### ISSUE THREAD

**Issue by danobis** [dapr/dotnet-sdk#1167]
## Ask your question here
I am experimenting with Dapr and would like to incorporate its service invocation ability in an existing application. I am trying to replicate the service invocation as shown here:

https://learn.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/service-invocation

<img width="738" alt="image" src="https://github.com/dapr/dotnet-sdk/assets/68187440/a88568e2-9b97-4bf7-bbe7-60d4b6079fae">

This is how I am registering the service in Program.cs of project 1 (the commented out section is how it was done originally before trying to leverage Dapr):

```
// builder.Services.AddHttpClient<IEventCatalogService, EventCatalogService>(c =>
// {
//     c.BaseAddress = new Uri(builder.Configuration["ApiConfigs:EventCatalog:Uri"]);
// });

builder.Services.AddSingleton<IEventCatalogService, EventCatalogService>(
    _ => new EventCatalogService(DaprClient.CreateInvokeHttpClient("event-catalog")));
```

As suggested on the tutorial page, the EventCatalogService itself has no Dapr-specific code:

```
public class EventCatalogService : IEventCatalogService
    {
        private readonly HttpClient _client;

        public EventCatalogService(HttpClient client)
        {
            this._client = client;
        }

        public async Task<IEnumerable<Category>> GetCategories()
        {
            var response = await _client.GetAsync("/api/categories");
            return await response.ReadContentAs<List<Category>>();
        }
    }
```

This is the method I am trying to invoke from project 2:

```
    [Route("api/categories")]
    public class CategoryController : ControllerBase
    {
        private ICategoryRepository _categoryRepository;
        private IMapper _mapper;

        public CategoryController(ICategoryRepository categoryRepository, IMapper mapper)
        {
            _categoryRepository = categoryRepository;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<CategoryDto>>> Get()
        {
            var result = await _categoryRepository.GetAllCategories();
            return Ok(_mapper.Map<List<CategoryDto>>(result));
        }
    }
```

Project 1 and project 2 are launched in terminals using:

dapr run --app-id web dotnet run
dapr run --app-id event-catalog dotnet run

I get status code 500 when trying to handle the service invocation this way:

```
== APP == StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
== APP == {
== APP ==   Date: Mon, 16 Oct 2023 12:10:35 GMT
== APP ==   Traceparent: 00-fedf071b822dedc58891163d1c8c4288-3b47039d5bb3bcca-01
== APP ==   Content-Type: application/json
== APP ==   Content-Length: 150
== APP == }
```

I assume I am missing some crucial configurations? Any help is highly appreciated!

**Comment by philliphoff** [comment]
@danobis Can you provide a bit more information about the error you're seeing, such as which application (`web` or `event-catalog`) generates it and, if possible, the actual exception that causes it (e.g. by logging it in the application)?  Which version of Dapr runtime and SDK are you using?

I attempted to reproduce this issue with a similar setup but I am getting successful calls via Dapr from service A to service B.

**Comment by danobis** [comment]
Hi @philliphoff, thanks for your response.

`web` is generating the error. This is the exception it causes:

<img width="1635" alt="image" src="https://github.com/dapr/dotnet-sdk/assets/68187440/02df5db1-66be-4cd5-828f-e026948938b2">

Dapr runtime: 1.11.2
SDK: 7.0.401

**Comment by philliphoff** [comment]
@danobis Looking at the error, it *appears* that `web` gets the request, makes a request of `event-catalog`, which gets received but returns a `500`, which then causes `web` to itself return an error.  In other words, it *seems* like the Dapr method invocation works, but the `event-catalog` controller returns an error.

I see that the `event-catalog` controller method requires a `categoryId` GUID argument extracted from the query string, but I don't see any provided in the URL of the call being made by `web` (e.g. `/api/events`).  Might that be an issue?

**Comment by danobis** [comment]
Sorry @philliphoff , I made a mistake and pasted the wrong methods into my question. I am actually trying to get the categories, not the events. I corrected the code snippets above.

Interestingly, it works just fine if I register the service like this:

```
builder.Services.AddHttpClient<IEventCatalogService, EventCatalogService>(c =>
{
     c.BaseAddress = new Uri(builder.Configuration["ApiConfigs:EventCatalog:Uri"]);
 });
```

However, when using the DaprClient variant, I get the above exception.

**Comment by philliphoff** [comment]
@danobis Are you (also) seeing an exception in the categories application?  You might also bump up the logging level of the Dapr sidecars (e.g. `--log-level debug`) and see if they show any errors in how they're attempting to make/receive method invocations.

**Comment by danobis** [comment]
Thanks for the suggestion, @philliphoff. It seems that the `Get()` method of `event-catalog` never gets executed. Maybe these log statements in `web` can indicate where the problem may be?

```
DEBU[0010] no mDNS address found in cache, browsing network for app id event-catalog  app_id=web component="mdns (nameResolution/v1)" instance=MacBook-Pro.local scope=dapr.contrib type=log ver=1.11.2
DEBU[0010] Browsing for first mDNS address for app id event-catalog  app_id=web component="mdns (nameResolution/v1)" instance=MacBook-Pro.local scope=dapr.contrib type=log ver=1.11.2
DEBU[0010] no mDNS address found in cache, browsing network for app id event-catalog  app_id=web component="mdns (nameResolution/v1)" instance=MacBook-Pro.local scope=dapr.contrib type=log ver=1.11.2
DEBU[0010] mDNS response for app id event-catalog received.  app_id=web component="mdns (nameResolution/v1)" instance=MacBook-Pro.local scope=dapr.contrib type=log ver=1.11.2
DEBU[0010] Adding IPv4 address 193.170.132.110:61702 for app id event-catalog cache entry.  app_id=web component="mdns (nameResolution/v1)" instance=MacBook-Pro.local scope=dapr.contrib type=log ver=1.11.2
DEBU[0010] mDNS browse for app id event-catalog canceled.  app_id=web component="mdns (nameResolution/v1)" instance=MacBook-Pro.local scope=dapr.contrib type=log ver=1.11.2
DEBU[0010] Browsing for first mDNS address for app id event-catalog canceled.  app_id=web component="mdns (nameResolution/v1)" instance=MacBook-Pro.local scope=dapr.contrib type=log ver=1.11.2
DEBU[0010] Refreshing mDNS addresses for app id event-catalog.  app_id=web component="mdns (nameResolution/v1)" instance=MacBook-Pro.local scope=dapr.contrib type=log ver=1.11.2
DEBU[0010] mDNS response for app id event-catalog received.  app_id=web component="mdns (nameResolution/v1)" instance=MacBook-Pro.local scope=dapr.contrib type=log ver=1.11.2
DEBU[0010] Adding IPv4 address 193.170.132.110:61702 for app id event-catalog cache entry.  app_id=web component="mdns (nameResolution/v1)" instance=MacBook-Pro.local scope=dapr.contrib type=log ver=1.11.2
```

**Comment by danobis** [comment]
Built everything from scratch and am no longer encountering this problem. Unfortunately I can't say what caused it.
