### ISSUE TITLE
Please use .NET Standard for abstracts libraries

### ISSUE THREAD

**Issue by ElderJames** [dapr/dotnet-sdk#118]
## Describe the proposal

I think there only ASP.NET Core depend the .net core 3.0, but as the clear architecture, developers prefer to put the interfaces and other abstracts to a single library using .net standard.

**Comment by davidfowl** [comment]
Which interfaces?

**Comment by ElderJames** [comment]
Like `IActor`,`Actor` and `ActorId` etc.

**Comment by amanbha** [comment]
@ElderJames How would that help, for this SDK, we only want to support .netcore 3.0.

**Comment by loic-sharma** [comment]
That means .NET Framework customers cannot use this project. Is that intended?

**Comment by amanbha** [comment]
Yes, that's intended
