### ISSUE TITLE
Support .NET 8

### ISSUE THREAD

**Issue by philliphoff** [dapr/dotnet-sdk#1187]
## Describe the feature

While .NET 8 Dapr applications are able to use the SDK's .NET 6 target, the SDK should specifically target .NET 8 as well.

At the very least, we should now be testing the SDK against .NET 8.

## Release Note

RELEASE NOTE:

**Comment by onionhammer** [comment]
>  error CS0618: 'ISystemClock' is obsolete: 'Use TimeProvider instead.' 

ISystemClock is referenced in AuthenticationHandler<>

**Comment by philliphoff** [comment]
Note: The Workflow package currently supports .NET 7 (whereas the others support only .NET 6), so that package will need to support .NET 6/7/8 at least until .NET 7 reaches end of support.
