### ISSUE TITLE
[Workflow] Examples do not work due to alpha -> beta changes

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dotnet-sdk#1189]
See the search results for references of `v1.0-alpha`

https://github.com/search?q=repo%3Adapr%2Fdotnet-sdk+v1.0-alpha1&type=code

These alpha APIs no longer exist and need uplifting to be inline with https://docs.dapr.io/reference/api/workflow_api/

This is causing problems for adopters which has surfaced via Discord

**Comment by halspang** [comment]
Fixed with #1194
