### ISSUE TITLE
[Bug] Console will be stuck in workflow sample

### ISSUE THREAD

**Issue by MregXN** [dapr/dotnet-sdk#1191]
## Expected Behavior
The program exits gracefully when I press Ctrl + C.

## Actual Behavior
Unable to terminate the generation of these logs
```
...
info: Microsoft.DurableTask[3]
      The gRPC server for Durable Task gRPC worker is unavailable. Will continue retrying.
info: Microsoft.DurableTask[3]
      The gRPC server for Durable Task gRPC worker is unavailable. Will continue retrying.
info: Microsoft.DurableTask[3]
      The gRPC server for Durable Task gRPC worker is unavailable. Will continue retrying.
...
```

## Steps to Reproduce the Problem

`dotnet run` in `./examples/Workflow/WorkflowConsoleApp` without dapr sidecar start. 
Or terminate the dapr sidecar when the program is running.

**Comment by cgillum** [comment]
Which process are you killing with Ctrl+C? The dapr sidecar? If so, I think this behavior is expected. [Here](https://github.com/dapr/dotnet-sdk/blob/09008bb43b89c85390db297d5bd8379a5c42d795/examples/Workflow/WorkflowConsoleApp/Program.cs#L61-L65) you can see that the app waits for the sidecar to become available. Even after this, the app is designed to run continuously.

**Comment by MregXN** [comment]
> Which process are you killing with Ctrl+C? The dapr sidecar? If so, I think this behavior is expected. [Here](https://github.com/dapr/dotnet-sdk/blob/09008bb43b89c85390db297d5bd8379a5c42d795/examples/Workflow/WorkflowConsoleApp/Program.cs#L61-L65) you can see that the app waits for the sidecar to become available. Even after this, the app is designed to run continuously.

I cant exit the WorkflowConsoleApp even I press ctrl + C as long as I exit the dapr sidecar first. It gets stuck in my command line so I can't do anything else, which I'm sure isn't a great experience for other users either.
