### ISSUE TITLE
Add more workflow samples

### ISSUE THREAD

**Issue by MregXN** [dapr/dotnet-sdk#1203]
## Describe the proposal
Python and Java SDKs have provided sample codes based on the [Dapr workflow pattern](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/) as mentioned in the official documents. However, dotnet SDK is yet to provide corresponding samples.

It is suggested to first add the following sample according to the documentation:
- [Task chaining](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/#task-chaining)
- [Fan-out/fan-in](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/#fan-outfan-in)
- [Monitor](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/#monitor)
- [External system interaction](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/#external-system-interaction)

**Comment by cgillum** [comment]
Looks like the work has been mostly completed and just needs to be reviewed/merged.

**Comment by WhitWaldo** [comment]
@MregXN I'm showing a merge conflict in the solution file for each of the referenced issues in this PR. If you can resolve that, I'd be happy to review these and get them merged in.
