### ISSUE TITLE
[Proposal] Remove usage of DaprClient APIs for wokflow

### ISSUE THREAD

**Issue by MregXN** [dapr/dotnet-sdk#1205]
## Describe the proposal
The `DaprClient` for workflow is outdated and is going to be abandoned. The `DaprWorkflowClient` class in `Dapr.Workflow` are recommended to use instead.

Here are the projects I found that are still using DaprClient to operate workflows:
- `workflowsapp` in `dapr/dapr` tests app ([link](https://github.com/dapr/dapr/tree/master/tests/apps/workflowsapp))
- `order-processor` in `dapr/quickstarts` workflow csharp sample ([link](https://github.com/dapr/quickstarts/tree/master/workflows/csharp/sdk/order-processor))
- `WorkflowConspleApp` in `dapr/dotnet-sdk` sample ([link](https://github.com/dapr/dotnet-sdk/tree/master/examples/Workflow))

**Comment by cgillum** [comment]
Marked as `P0` since I think we shouldn't declare workflows as stable with APIs that we don't intend to support.

**Comment by WhitWaldo** [comment]
@cgillum Does this differ in any meaningful way from #1344 ? I already have a PR for that one at #1345 and the PR for the docs has already been merged [here](https://github.com/dapr/docs/pull/4336).

**Comment by cgillum** [comment]
@WhitWaldo good observation. I think the difference is that #1344 tracks removing the APIs whereas this item tracks removing all _references_ to those APIs. Technically, this one could be completed first without removing the APIs themselves.

It looks like there's [at least one place](https://github.com/dapr/dapr/blob/9591e5778c4e03587acabe35744770881a86c35f/tests/apps/workflowsapp/Controller.cs#L43) where we're still using the deprecated APIs in `dapr/dapr` test code.

**Comment by WhitWaldo** [comment]
It's probably worth doing a cursory peek through all the SDKs to see if any of the non-.NET variants are using the old methods as well.

**Comment by mikeee** [comment]
Duplicate/new issue - #1344

**Comment by WhitWaldo** [comment]
Closed as part of #1362
