### ISSUE TITLE
Workflow status displays as `Unknown` after being paused using 

### ISSUE THREAD

**Issue by MregXN** [dapr/dotnet-sdk#1215]
## Expected Behavior

workflow status should be `Suspended`

## Actual Behavior

 displays as `Unknown`

## Steps to Reproduce the Problem
use `SuspendWorkflowAsync` in `DaprWorkflowClient` to pause a workflow instance 
```csharp

...
await workflowClient.SuspendWorkflowAsync(instanceId);
var getResponse = await workflowClient.GetWorkflowStateAsync(instanceId);
Console.WriteLine(Enum.GetName(typeof(WorkflowRuntimeStatus), getResponse.RuntimeStatus));
...
```

**Comment by WhitWaldo** [comment]
Has any testing been done with the other language SDKs to confirm that this is an issue with the .NET SDK itself and not an issue with the sidecar implementation?

**Comment by mikeee** [comment]
> Has any testing been done with the other language SDKs to confirm that this is an issue with the .NET SDK itself and not an issue with the sidecar implementation?

The durabletask-go implementation and downstream dapr go-sdk is working as expected (although missing tests)

**Comment by cgillum** [comment]
Looks like there's a `switch` case missing for `Suspended` in the code [here](https://github.com/dapr/dotnet-sdk/blob/74f6b0127fb33d72ff1c62aecfce8b1694a6b334/src/Dapr.Workflow/WorkflowState.cs#L75-L89). Should be an easy fix.
