### ISSUE TITLE
Cascade Terminate/Purge for workflow

### ISSUE THREAD

**Issue by shivamkm07** [dapr/dotnet-sdk#1226]
## Describe the feature

Cascade terminate/purge feature for workflow has been added in Dapr runtime. It is enabled by default and can be disabled by passing `non_recursive=True` in the terminate/purge request. 

SDK needs to expose this option to customer.

Reference: 
1. https://github.com/dapr/dapr/pull/7340
2. https://github.com/microsoft/durabletask-go/pull/47
3. https://github.com/microsoft/durabletask-dotnet/issues/260

## Release Note

RELEASE NOTE:

**Comment by shivamkm07** [comment]
PR to support cascade terminate/purge in durabletask-dotnet: https://github.com/microsoft/durabletask-dotnet/pull/262

After this gets merged, will create the PR to surface the option here.

**Comment by halspang** [comment]
I've added the breaking change label here because this is technically a change in core behavior that the user can't opt into. I do understand that this is the desired path so it's more of a bugfix than anything else, but we need to advertise that.

**Comment by shivamkm07** [comment]
Closed by #1243
