### ISSUE TITLE
Consider using xUnit as testing framework

### ISSUE THREAD

**Issue by shaggygi** [dapr/dotnet-sdk#123]
It seems like xUnit would be a better choice for testing, especially since other main .NET repos are using (e.g. corefx, iot, etc.).  Would it be possible to convert before too many tests are created?

**Comment by amanbha** [comment]
@shaggygi Could you please share why xUnit would be better, may be share some benefits over what we have today? That would help us make a educated decision.

**Comment by shaggygi** [comment]
@amanbha This probably comes down to my experience while working on projects (both for employer and GitHub), so don't let me sway if the core dapr team already has experience/decision to use the current test framework.  I've also used NUnit, but as mentioned, it appears xUnit has a good traction in the wild and is used by many of the core .NET repos like Roslyn and such.

I'm sure they all have similar features.  One thing I like about xUnit is it includes its own analyzers to help improve tests.

I'll keep reviewing and reading the docs.

**Comment by amanbha** [comment]
@shaggygi I don't have strong preference for xunit or mstest, If xunit is more preferable by community and makes the life easier then sure, lets use it.

**Comment by shaggygi** [comment]
@amanbha thank you for being flexible.  If you don't mind, let me add the xunit packages while I'm working on #121.  I don't think there should be any conflicts with both.  This would allow you to review the PR and if all good, I can circle back and update the current tests with xunit and remove the older package dependencies.  Thoughts?

**Comment by amanbha** [comment]
> @amanbha thank you for being flexible. If you don't mind, let me add the xunit packages while I'm working on #121. I don't think there should be any conflicts with both. This would allow you to review the PR and if all good, I can circle back and update the current tests with xunit and remove the older package dependencies. Thoughts?

Would there be an issue with 2 different Adapters? I believe it should be fine, You can go ahead and make the changes to all.
