### ISSUE TITLE
Its Not clear which is the most up-to-date-dotnet Workflow Sample

### ISSUE THREAD

**Issue by tshaiman** [dapr/dotnet-sdk#1234]
There are two versions of .NET SDK Workflow samples , in two different repos : 

https://github.com/dapr/quickstarts/tree/master/workflows/csharp/sdk/order-processor

and 

https://github.com/dapr/dotnet-sdk/tree/master/examples/Workflow/WorkflowConsoleApp

which is the "Lastest-And-Greatest" ?

**Comment by cgillum** [comment]
It seems like both of these samples are sufficiently up-to-date now.
