### ISSUE TITLE
AddDaprClient incompatible with keyed services

### ISSUE THREAD

**Issue by onionhammer** [dapr/dotnet-sdk#1235]
## Expected Behavior
When adding dapr client to service builder, this should not error

https://weblogs.asp.net/ricardoperes/net-8-dependency-injection-changes-keyed-services

```C#
// Add dapr client
builder.Services.AddDaprClient(client =>
{
    client.UseJsonSerializationOptions(JsonExtensions.JsonOptions);
});
```

## Actual Behavior

When adding dapr to your serviceBuilder, if there are keyed services present, adding dapr fils with exception:

```
Unhandled exception. System.InvalidOperationException: This service descriptor is keyed. Your service provider may not support keyed services.
```

## Steps to Reproduce the Problem
Add a dapr client to an application with keyed services defined, i.e. with Orleans:

```C#
builder.Host.UseOrleans(siloBuilder =>
{
    siloBuilder.AddActivityPropagation();
});
```

**Comment by artyom-p** [comment]
Same here, related to [this](https://github.com/dotnet/runtime/issues/95789) issue.

![image](https://github.com/dapr/dotnet-sdk/assets/3993463/18a09c54-92b6-4b3b-b3fa-b9c537663e20)

**Comment by Sen-Gupta** [comment]
I'm not sure it this works for you, I placed AddDapr above all calls in service registration and it works.

Additionally, I downgraded Assemblies to 8.0.0 for DependencyInjection.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rliberoff** [comment]
Thank you @Sen-Gupta.

The issue is not with `AddDapr` but with `AddDaprClient`.

This happens with the newest .NET Aspire Preview 3.

**Comment by Sen-Gupta** [comment]
Apologies, I meant that only.

I attached the file, I would be able to share more details tomorrow.

It is midnight in my time zone.

Regards
Sen


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rliberoff** [comment]
From further investigation, we found out that the offending dependency is with library `Microsoft.Extensions.Http.Resilience` when updated from version `8.1.0` to `8.2.0`. Hope it helps.

**Comment by Sen-Gupta** [comment]
@rliberoff 

Double Confirmation!

That's correct. I did upgrade Microsoft.Extensions.Http.Resilience to 8.2.0.
