### ISSUE TITLE
Remove redundant dependencies

### ISSUE THREAD

**Issue by thompson-tomo** [dapr/dotnet-sdk#1239]
## Describe the feature
I want to be able to use framework dependencies wherever possible rather than an explicit one ie System.Net.Http.Json

## Release Note

**UPDATE** Remove dependencies available as part of framework

**Comment by philliphoff** [comment]
I assume you mean that we should remove the package reference to `System.Net.Http.Json` in the `Dapr.Client` assembly?

**Comment by thompson-tomo** [comment]
Correct and based on the comment in Dapr.Actors.AspNetCore, System.IO.Pipelines should also be able to be removed.
