### ISSUE TITLE
Use editorconfig and remove Stylecop.Analyzers dependency

### ISSUE THREAD

**Issue by shaggygi** [dapr/dotnet-sdk#124]
It might be better to use Microsoft.CodeAnalysis.FxCopAnalyzers instead of the StyleCop.Analyzers package.

Don't get me wrong as I've used StyleCop.Analyzers in many projects and is very helpful.  It just appears Microsoft.CodeAnalysis.FxCopAnalyzers is the future direction IMHO.

Referencing...  https://github.com/dotnet/roslyn-analyzers

**Comment by amanbha** [comment]
@shaggygi Thansk for suggesting this, it would be a good idea. Do you have suggestion for some subset of categories rules to enable in first iteration and then make it stricter it overtime. Based on my experience with StylecopAnalyzer, turning all the rules in first iteration would be too many issues.

**Comment by shaggygi** [comment]
Not at the moment, but could review in the near future.  I'm cc-ing @sharwell as he is the creator of StyleCop.Analyzers and now works on the Roslyn team.  He might be able to provide some initial content to get started.

**Comment by sharwell** [comment]
These are two different products serving two different needs. They can be used separately or together depending on the specific goals of the project.

**Comment by rynowak** [comment]
I'd suggest editorconfig **enthusiastically** over stylecop. The IDE has really rich support for editorconfig, and it supports running formatting with a command line tool (`dotnet format`).

When I saw that this repo was using Stylecop, it was like being transported back in time 😆

**Comment by sharwell** [comment]
@rynowak StyleCop Analyzers is not StyleCop.

**Comment by rynowak** [comment]
and I'm suggesting using neither 😆

**Comment by rynowak** [comment]
@sharwell - thanks for reaching out to me offline.

The StyleCop analyzers add some features that editorconfig doesn't support, as well as the ability to enforce style rules at build time.

My feedback was mostly about:
- StyleCop's default rules, which doesn't match the style of most .NET OSS today
- Breaking the build for style validation (which I think can become warnings instead)

I'd suggest that we add an editor config and think about relaxing some of things stylecop is doing, or make it warnings.
