### ISSUE TITLE
JsonReaderExtensions.ReadValueAsTimeSpanDaprFormat should return TimeSpan instead of TimeSpan?

### ISSUE THREAD

**Issue by gmanvel** [dapr/dotnet-sdk#125]
JsonReaderExtensions.ReadValueAsTimeSpanDaprFormat method signature is the following

`public static TimeSpan? ReadValueAsTimeSpanDaprFormat(this JsonReader reader)`

It initializes return value to null at the begging of the method:
`TimeSpan? value = null;`

DueTime & Period properties of ReminderInfo are non nullable TimeSpan, so even if they're not set, TimeSpan.Zero will be used & serialized.
This method should also return TimeSpan.Zero although I can't see when that will happen as any failure to deserialize this property will result in exception being thrown.

This change in turn will allow to simplify ReminderInfo's GetFromJsonProperties(JsonReader reader) method, where we have

`dueTime = (TimeSpan)reader.ReadValueAsTimeSpanDaprFormat();`

&

`period = (TimeSpan)reader.ReadValueAsTimeSpanDaprFormat();`

Right now it has a warning on those lines saying `Possible System.InvalidOperationException`.

**Comment by rynowak** [comment]
@gmanvel - are you saying there's a functional bug here? What would a repo for that bug look like?

**Comment by gmanvel** [comment]
@rynowak if `reader.ReadValueAsTimeSpanDaprFormat();` returns null, then `dueTime = (TimeSpan)reader.ReadValueAsTimeSpanDaprFormat();` will throw an exception.

I also can't see in which case [JsonReaderExtensions.ReadValueAsTimeSpanDaprFormat](https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Actors/JsonReaderExtensions.cs#L387) will return null, so I think this can be simplified to return `TimeSpan` instead of `Nullable<TimeSpan>` which will further simplify the client code for this method.

You can find suggested changes in PR - https://github.com/dapr/dotnet-sdk/pull/126
