### ISSUE TITLE
macOS Sonoma 14.4 - SocketException: Can't assign requested address

### ISSUE THREAD

**Issue by borbiuk** [dapr/dotnet-sdk#1257]
## Expected Behavior

Successful operation publishing.

## Actual Behavior

I'm running ~8 dotnet APIs locally that use Dapr. Sometimes I have problems with the Internet (ERR_ADDRESS_INVALID) when all services are running, besides this, it happens that the publication of Dapr events fails.

**OS: macOS Sonoma 14.4**
**Dapr version: 1.12.3**

**Exception:**
```
Dapr.DaprException: Publish operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
 ---> Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException: Can't assign requested address")
 ---> System.Net.Sockets.SocketException (49): Can't assign requested address
```

I will be very grateful for your help. If you need any additional information, please let me know.

## Steps to Reproduce the Problem

Run many dotnet APIs that use Dapr Sidecar. Try to publish a new Dapr operation or open some website in your browser. 

## Release Note

RELEASE NOTE: **FIX** Bug in runtime

**Comment by borbiuk** [comment]
I think I solved the problem.

First, you had to set the environment variable `DAPR_HOST_IP` (see [dapr docs](https://docs.dapr.io/reference/environment/)).

Then I uninstalled and reinstalled Dapr:
`dapr uninstall && dapr init`

And maybe you will find this article useful:
[Resolving service invocation timeout errors with Dapr and mDNS on OSX](https://medium.com/@catalin.tomescu/service-invocation-with-dapr-and-mdns-on-osx-3e10b2a1db62)

**Comment by philliphoff** [comment]
As this refers to runtime behavior and is not specific to the .NET SDK, I'll close this in favor of [dapr/dapr#7383](https://github.com/dapr/dapr/issues/7383)
