### ISSUE TITLE
SaveBulkStateAsync() throws context deadline exceeded exception

### ISSUE THREAD

**Issue by koumdev** [dapr/dotnet-sdk#1265]
## Ask your question here
Hello,

I'm using Azure Cosmos DB state store and the SaveBulkStateAsync() to save bulk records, but an exception (`context deadline exceeded`) is thrown when the call takes more than 20 seconds(ish).

From [cosmosdb.go code](https://github.com/dapr/components-contrib/blob/cfee998aba0817ae07dc31bb53c34d21f6b9f4f2/state/azure/cosmosdb/cosmosdb.go#L83), it looks like there is a default timeout of 20 seconds.

All of the functions (`Get`, `Set`, `Delete`, ...) except `BulkGet` are using `defaultTimeout` to set the context timeout.

- Is that the reason why my call fails?
- Does that mean all the Azure Cosmos DB state store calls timeout after 20 seconds?
- Is there any way to change this timeout?

Thank you!

**Comment by philliphoff** [comment]
@koumdev It looks to me like it's a hardcoded 20s timeout in the component itself.  I'd file an issue in [dapr/components-contrib](https://github.com/dapr/components-contrib) and ask these questions.  In any case, it's unlikely to be specific to the .NET SDK.

**Comment by philliphoff** [comment]
Closing this in favor of the components-contrib issue.
