### ISSUE TITLE
It is not possible to read headers sent from a RabbitMQ message

### ISSUE THREAD

**Issue by jcnewmanunilink** [dapr/dotnet-sdk#1267]
## Expected Behavior

When I publish a message which contains data in the header, it should be possible to ready them by interrogating the Request.Headers Object in code.

## Actual Behaviour

Although some system headers are being sent (Content-Type for example) not all headers appear to be passed along.
The Request Header object should contain all headers sent in the message payload

## Steps to Reproduce the Problem

Publish a message from the RabbitMq interface like so:
![image](https://github.com/dapr/dotnet-sdk/assets/143734061/9cb89b24-0e82-48e8-ab96-3ccbfa2ae932)

I am expecting to be able to retrieve the ImportantHeader value in the controller, however, the Request object appears to omit the values provided in the message above:
![image](https://github.com/dapr/dotnet-sdk/assets/143734061/55b199be-6f47-47ac-a223-827e6cb683e8)

## Release Note

RELEASE NOTE: **FIX** RabbitMQ headers now sent from Dapr sidecar to application

**Comment by philliphoff** [comment]
This may be a current limitation of the Dapr pub/sub component model as a whole (i.e. not specific to the .NET SDK).  See [dapr/dapr#6075](https://github.com/dapr/dapr/issues/6075).

**Comment by philliphoff** [comment]
Will close this issue in favor of the existing Dapr runtime issue.
