### ISSUE TITLE
Standardize README with shield badges

### ISSUE THREAD

**Issue by marcduiker** [dapr/dotnet-sdk#1283]
_-- Updated so all badges are links, added FOSSA license scan --_

We want to update the README for all Dapr repos so they all include shield badges for YouTube, Discord, X/Twitter and ensure they are all in the same style. See: https://github.com/dapr/community/issues/355

These are the [shield badges]( https://shields.io/badges) for the dotnet-sdk repo. 

[![NuGet Version](https://img.shields.io/nuget/v/Dapr.Client?logo=nuget&label=Latest%20version&style=flat)](https://www.nuget.org/packages/Dapr.Client) [![NuGet Downloads](https://img.shields.io/nuget/dt/Dapr.Client?style=flat&logo=nuget&label=Downloads)](https://www.nuget.org/packages/Dapr.Client) [![GitHub Actions Workflow Status](https://img.shields.io/github/actions/workflow/status/dapr/dotnet-sdk/.github%2Fworkflows%2Fsdk_build.yml?branch=master&label=Build&logo=github)](https://github.com/dapr/dotnet-sdk/actions/workflows/sdk_build.yml) [![codecov](https://codecov.io/gh/dapr/dotnet-sdk/branch/master/graph/badge.svg)](https://codecov.io/gh/dapr/dotnet-sdk) [![GitHub License](https://img.shields.io/github/license/dapr/dotnet-sdk?style=flat&label=License&logo=github)](https://github.com/dapr/dotnet-sdk/blob/master/LICENSE) [![FOSSA Status](https://app.fossa.com/api/projects/custom%2B162%2Fgithub.com%2Fdapr%2Fdotnet-sdk.svg?type=shield&issueType=license)](https://app.fossa.com/projects/custom%2B162%2Fgithub.com%2Fdapr%2Fdotnet-sdk?ref=badge_shield&issueType=license) [![GitHub issue custom search in repo](https://img.shields.io/github/issues-search/dapr/dotnet-sdk?query=type%3Aissue%20is%3Aopen%20label%3A%22good%20first%20issue%22&label=Good%20first%20issues&style=flat&logo=github)](https://github.com/dapr/dotnet-sdk/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) [![Discord](https://img.shields.io/discord/778680217417809931?label=Discord&style=flat&logo=discord)](http://bit.ly/dapr-discord) [![YouTube Channel Views](https://img.shields.io/youtube/channel/views/UCtpSQ9BLB_3EXdWAUQYwnRA?style=flat&label=YouTube%20views&logo=youtube)](https://youtube.com/@daprdev) [![X (formerly Twitter) Follow](https://img.shields.io/twitter/follow/daprdev?logo=x&style=flat)](https://twitter.com/daprdev)

Snippet to include in the README:

```
[![NuGet Version](https://img.shields.io/nuget/v/Dapr.Client?logo=nuget&label=Latest%20version&style=flat)](https://www.nuget.org/packages/Dapr.Client) [![NuGet Downloads](https://img.shields.io/nuget/dt/Dapr.Client?style=flat&logo=nuget&label=Downloads)](https://www.nuget.org/packages/Dapr.Client) [![GitHub Actions Workflow Status](https://img.shields.io/github/actions/workflow/status/dapr/dotnet-sdk/.github%2Fworkflows%2Fsdk_build.yml?branch=master&label=Build&logo=github)](https://github.com/dapr/dotnet-sdk/actions/workflows/sdk_build.yml) [![codecov](https://codecov.io/gh/dapr/dotnet-sdk/branch/master/graph/badge.svg)](https://codecov.io/gh/dapr/dotnet-sdk) [![GitHub License](https://img.shields.io/github/license/dapr/dotnet-sdk?style=flat&label=License&logo=github)](https://github.com/dapr/dotnet-sdk/blob/master/LICENSE) [![FOSSA Status](https://app.fossa.com/api/projects/custom%2B162%2Fgithub.com%2Fdapr%2Fdotnet-sdk.svg?type=shield&issueType=license)](https://app.fossa.com/projects/custom%2B162%2Fgithub.com%2Fdapr%2Fdotnet-sdk?ref=badge_shield&issueType=license) [![GitHub issue custom search in repo](https://img.shields.io/github/issues-search/dapr/dotnet-sdk?query=type%3Aissue%20is%3Aopen%20label%3A%22good%20first%20issue%22&label=Good%20first%20issues&style=flat&logo=github)](https://github.com/dapr/dotnet-sdk/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) [![Discord](https://img.shields.io/discord/778680217417809931?label=Discord&style=flat&logo=discord)](http://bit.ly/dapr-discord) [![YouTube Channel Views](https://img.shields.io/youtube/channel/views/UCtpSQ9BLB_3EXdWAUQYwnRA?style=flat&label=YouTube%20views&logo=youtube)](https://youtube.com/@daprdev) [![X (formerly Twitter) Follow](https://img.shields.io/twitter/follow/daprdev?logo=x&style=flat)](https://twitter.com/daprdev)
```

**Contributing**
- Comment `/assign` on this issue if you want to self-assign this issue and update the README.
- Don't forget to sign off your commit, for more details see [Developer Certificate of Origin (DCO) in the docs](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work).

Please label this as `good first issue`.

**Comment by marcduiker** [comment]
Thanks for adding the badges @m3nax!

Could you make another PR and add back the `# Dapr SDK for .NET` on the first line of the README, please? This has unintentionally been removed with your change :). See the diff: https://github.com/dapr/dotnet-sdk/pull/1284/files

**Comment by m3nax** [comment]
@marcduiker fixed

**Comment by marcduiker** [comment]
Thanks @m3nax !

**Comment by mikeee** [comment]
@marcduiker - just noticed that some of links aren't working or included as intended. The twitter badge for example only contains the image url and navigates to the badge image when clicked.

**Comment by m3nax** [comment]
Fixed build badge:
[![build](https://github.com/dapr/dotnet-sdk/actions/workflows/sdk_build.yml/badge.svg)](https://github.com/dapr/dotnet-sdk/actions/workflows/sdk_build.yml)

**Comment by marcduiker** [comment]
> @marcduiker - just noticed that some of links aren't working or included as intended. The twitter badge for example only contains the image url and navigates to the badge image when clicked. The others are: latest version, build and license

Thanks @mikeee! I'll update the issue, and re-open. You can use the formatted snippet in this issue @m3nax since I've updated that.
