### ISSUE TITLE
Passing query string parameters on method invocation

### ISSUE THREAD

**Issue by WhitWaldo** [dapr/dotnet-sdk#1303]
The [service invocation documentation](https://docs.dapr.io/reference/api/service_invocation_api/) speaks to a body-based payload (via POST) and doesn't mention query strings anywhere.

I was looking to use Dapr to invoke a method on an API controller that required query string parameters. On a whim, I jammed the query string to the end of the request URL to see what it'd do and to my surprise, it worked precisely as expected. To that end, I thought I'd file this ticket to confirm this is happening as it was expected to and if so, see if there's any interest in a PR that adds some overloads to allow query strings to be more readily appended to the URI.

In the short term, here's what I'm currently doing that's working:
```cs
//API - MyController.cs
[ApiController]
[Route("[controller]")]
public class MyController() : ControllerBase
{
  [HttpGet]
  public IEnumerable<MyObject> Get([FromQuery(Name="c")] int count)
  {
    //Return something
  }
}

// Extensions
    public static void AddQueryParameters(
        this HttpRequestMessage? message,
        Dictionary<string, string>? queryStringParameters)
    {
        ArgumentNullException.ThrowIfNull((object)message, nameof(message));
        if (queryStringParameters == null)
            return;
        UriBuilder uriBuilder = new UriBuilder(message.RequestUri);
        string str = uriBuilder.Query;
        foreach (KeyValuePair<string, string> queryStringParameter in queryStringParameters)
        {
            if (!string.IsNullOrEmpty(str))
                str += "&";
            str = str + Uri.EscapeDataString(queryStringParameter.Key) + "=" + Uri.EscapeDataString(queryStringParameter.Value);
        }
        uriBuilder.Query = str;
        message.RequestUri = uriBuilder.Uri;
    }

//Service - Program.cs
app.MapGet("/api/data", async (DaprClient client) => 
{
  var req = daprClient.CreateInvokeMethodRequest(HttpMethod.Get, "api-service", "Get");
  req.AddQueryParameters(new Dictionary<string,string>
  {
    {"c", "2"}
  });

  return await client.InvokeMethodAsync<int[]>(req);  
});
```

Can anyone confirm this is working as fully expected?

**Comment by philliphoff** [comment]
@WhitWaldo As far as I know, query parameters were intended to "just work" with Dapr service invocation and simply "forwarded" to the application.  You might submit an issue in the [docs](https://github.com/dapr/docs) repo to have that be made explicit.

As far as a PR goes to help with query parameters, I'm a bit torn.  On the one hand, it could be useful in that I've always thought .NET had unexpectedly poor support for managing query parameters.  On the other hand, I don't necessarily want to create APIs that might be inconsistent with how developers typically manage query parameters in .NET.

I could see explicit support for query parameters in, say, the basic service invocation methods (e.g. in `InvokeMethodAsync()` pass a dictionary that represents the query).  However, I'm not sure I can see explicit support for query parameters when working with `HttpClient`, as that seems more the purview of .NET itself or, at least, of non-Dapr libraries.

**Comment by WhitWaldo** [comment]
@philliphoff Yes, my proposal was more centered on augmenting the InvokeMethodAsync method to include a query string argument as under the hood it's simply building out the URL to invoke the method out of the pieces provided, so we could simply add the query string to the end. It would make more sense to simply augment this method than necessarily add some extension method for the HttpClient returned from `DaprClient.CreateInvokeHttpClient()` as you're right, that's more the purview of the .NET team.
