### ISSUE TITLE
[docs] Add Jobs API .NET client example to doc

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/dotnet-sdk#1322]
Once .NET client support is available, add example to this doc: https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-client/#building-blocks

Related links:
#1320 
#1331

**Comment by sebastianamaro** [comment]
Hi! Are Jobs already supported in .NET? Is there any doc to it?

**Comment by WhitWaldo** [comment]
@sebastianamaro Jobs are supported in Dapr as of 1.14 and accessible via the [HTTP API](https://docs.dapr.io/reference/api/jobs_api/) today. The .NET SDK will include support in the 1.15 release ([targeting Dec 10](https://github.com/dapr/dapr/issues/8017)).

**Comment by WhitWaldo** [comment]
These docs are included in #1409
