### ISSUE TITLE
Starting a workflow at different app

### ISSUE THREAD

**Issue by ozgurgunseli** [dapr/dotnet-sdk#1333]
Hi there,

Currently, we can start a workflow using DaprClient. However, when we need to start a workflow that is registered in a different Dapr application, the current client does not allow us to initiate it.

**Scenario:**

- **App 1:** Server application with a workflow called "GenerateLog," has a Dapr Sidecar (app-id: `server-app`).
- **App 2:** An API application, also with a Dapr Sidecar (app-id: `api-app`).

In this scenario, when an API call is made to App 2, it should start the "GenerateLog" workflow in App 1. While we can achieve this by directly calling the Dapr URL for `server-app`, the current `StartWorkflowAsync` method of DaprClient does not allow us to specify an app-id.

Given the need for a client-server architecture in our applications, adding this feature would be highly beneficial.

Thank you!

**Comment by WhitWaldo** [comment]
An overload could be added to the DaprClient that added a dapr-id argument and which registered some sort of endpoint to listen for such calls to the target application, but in the short term, why not just implement that yourself?

1) In App 2, create an endpoint with the logic to start some workflow with provided arguments
2) In App 1, use the DaprClient to utilize the service invocation functionality to all this endpoint and pass it the necessary arguments.
3) App 2 starts the target workflow locally as desired.

**Comment by WhitWaldo** [comment]
As there hasn't been any additional activity on this issue, I'm going to go ahead and mark it as closed for now as it would require a runtime change (not SDK-level). If it's something you would really like to see, I'd urge you to fill out a feature request in the runtime repo at https://github.com/dapr/dapr and if they take it on, we'll certainly update this SDK to match.
