### ISSUE TITLE
Add Conversational building block support #1382

### ISSUE THREAD

**Issue by WhitWaldo** [dapr/dotnet-sdk#1383]
Proposal: https://github.com/dapr/proposals/blob/main/20240618-RCBS-Conversation-building-block.md

**Comment by cecilphillip** [comment]
Microsoft recently released their new [Microsoft.Extensions.AI Extensions](https://devblogs.microsoft.com/dotnet/introducing-microsoft-extensions-ai-preview/). Will the Dapr .NET SDK support this through the building block?

**Comment by luisquintanilla** [comment]
> Will the Dapr .NET SDK support this through the building block?

Thanks for the tag @cecilphillip. We're happy to work with the team and community on enabling support for MEAI in the .NET SDK. 

cc: @stephentoub @SteveSandersonMS @eiriktsarpalis

**Comment by cecilphillip** [comment]
This scope of this would just be for the conversational bits, but we should keep in mind the possibility of support the vector store abstractions if/when those building blocks are ready.

@WhitWaldo I don't believe there's time to get this in for 1.15 would it?

**Comment by WhitWaldo** [comment]
@cecilphillip That's right - we're going to have to look at what we can do about this after 1.15 as code freeze is imminent.

I'm still trying to wrap my head around what opportunities there are here because from what I've read, they seem to be providing similar abstractions to the downstream AI functionality, both making it readily accessible from .NET. This new Conversational block in Dapr and the Microsoft.Extensions.AI.Extensions both allow for easy integration with LLMs.

Given that they appear to address the same problem, I'm curious about what specific integration or complementary use you envision between the two. Could you share more about how you see them working together?

Finally, I have been soliciting interest in building out a [next-gen set](https://github.com/dapr/dapr/issues/7339) of state APIs and I've fielded an ask for a vector store as part of that. While there's no movement on actually implementing that yet, it's certainly somewhere on the horizon.
