### ISSUE TITLE
[docs] Update pre-requisites on the .NET landing page with supported .NET versions

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/dotnet-sdk#1397]
.NET 6 and .NET 8 supported for 1.14, not .NET 7
With 1.15, only .NET 8 and .NET 9

**Comment by WhitWaldo** [comment]
Almost:
- v1.15 will still target .NET 6 and .NET 8 (not .NET 7, though it's tested against for now). It doesn't target .NET 9 since it's not actually released yet and we're feature frozen as of this week.
- v1.16 will drop .NET 6 and target .NET 8 and .NET 9

**Comment by hhunter-ms** [comment]
@WhitWaldo thank you for the clarifications!

**Comment by WhitWaldo** [comment]
I definitely intend to add a release note to clarify things, so I'll circle back when that's drafted.
