### ISSUE TITLE
Missing debug documentation

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/dotnet-sdk#141]
Currently, information about starting and debugging (multiple) Dapr apps from Visual Studio and Visual Studio Code is missing and should be provided.

(outcome from a discussion at https://gitter.im/Dapr/community @LukePammant @lynn-orrell)

**Comment by amanbha** [comment]
@RicardoNiepel currently we don't have any tooling integration, but for debugging you can attach to user app process after it's launched by Dapr cli

**Comment by philliphoff** [comment]
I've been doing some Dapr application building in VS Code and am using the following running/debugging pattern.  It's a bit tedious to setup and manage with a lot of services (I'm up to 9 services so far), but it works well enough for now.

 - When needing to simply run a service (e.g. DeckManager):
   - Run the `DeckManager: Launch` task from the command palette
     - This will rebuild the service due to the `dependsOn` property
     - This will then launch the service using the `dapr` CLI
 - When needing to debug a service (e.g. DeckManager):
   - Select and <kbd>F5</kbd> the `DeckManager` configuration
     - This will rebuild the service due to the `preLaunchTask` property
     - This will then launch the service within the debugger (like any other .NET application)
   - Run the `DeckManager: Dapr` task from the command palette
     - This will run the Dapr "sidecar" process using the `daprd` CLI, which then binds to the application running in the debugger.

> Note that I run the `daprd` sidecar task *after* the application's running in the debugger.  I tried to make this a pre-launch dependency of the debug configuration, but couldn't get VS Code to recognize when the task was "complete" (as it's a background/watch type task).  I've still got more investigation to do there.

I don't have a good method of tearing down services, yet. Currently I have to <kbd>Ctrl</kbd>+<kbd>C</kbd> in each of the terminal windows spawned by each of the launch tasks.  I've run into issues with simply killing the `dapr` processes; sometimes its wrapped application process fails to get killed and you end up with port-in-use issues on the next startup.

`tasks.json`:

```json
        ...
        {
            "label": "DeckManager: Build",
            "command": "dotnet",
            "type": "process",
            "options": {
                "cwd": "${workspaceFolder}/src/DaprCards.DeckManager"
            },
            "args": [
                "build"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "DeckManager: Dapr",
            "command": "daprd",
            "type": "process",
            "args": [
                "--dapr-id", "dapr-deck-manager",
                "--app-port", "5006",
                "--dapr-http-port", "45006",
                "--dapr-grpc-port", "46006",
                "--placement-address", "localhost:50005"
            ],
            "problemMatcher": []
        },
        {
            "label": "DeckManager: Launch",
            "command": "dapr",
            "type": "process",
            "options": {
                "cwd": "${workspaceFolder}/src/DaprCards.DeckManager"
            },
            "args": [
                "run",
                "--app-id", "dapr-deck-manager",
                "--app-port", "5006",
                "dotnet", "run"
            ],
            "problemMatcher": []
        },
        ...
```

`launch.json`:

```json
        ...
        {
            "name": "DeckManager",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "DeckManager: Build",
            "program": "${workspaceFolder}/src/DaprCards.DeckManager/bin/Debug/netcoreapp3.0/DaprCards.DeckManager.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development",
                "DAPR_HTTP_PORT": "45006"
            }
        },
        ...
```
