### ISSUE TITLE
Dapr Workflow pacakge || Update the dependency 'System.Text.Json' to the latest version

### ISSUE THREAD

**Issue by AlbertoVPersonal** [dapr/dotnet-sdk#1414]
### Current scenario

Given a solution in .NET,
when the user executes the following command 

```powershell
dotnet add package Dapr.Workflow --version 1.14.0
```
then the system shows a warning

`warn : NU1903: El paquete "System.Text.Json" 6.0.0 tiene una vulnerabilidad de gravedad alta conocida`

### Workaround

Update the package with the command:

```powershell
dotnet add package System.Text.Json
```

PS: Albert0 (from Discord).

**Comment by WhitWaldo** [comment]
This is already covered in the master branch as [part of the .NET 9 support](https://github.com/dapr/dotnet-sdk/blob/0b80c853b640686085b931eb92f20be7ce6dbc3b/Directory.Packages.props#L47).
