### ISSUE TITLE
ETag usage

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/dotnet-sdk#142]
I cannot find any usage of etag fields or headers in the codebase, but for my understanding this should be used.

E.g.
- for actors reminders, see dapr/dapr#677 and dapr/docs#211
- for state, see https://github.com/dapr/docs/blob/master/reference/api/state.md

**Comment by amanbha** [comment]
> As etag will not be exposed for Actors as runtime ensures their single threadedness, it's still the question if we need them to be used with state management, e.g. expose them through the SDK?

Yes, for state management it should be exposed.

**Comment by RicardoNiepel** [comment]
I can do this, if you've not already started

**Comment by amanbha** [comment]
Sure, thanks, please assign it to yourself.

**Comment by amanbha** [comment]
Tracked by P0 item https://github.com/dapr/dotnet-sdk/issues/225
This item will add state apis as wrapper over gRPC api.
