### ISSUE TITLE
Mapping topic subscriptions through the app.UseEndpoints()

### ISSUE THREAD

**Issue by nikneem** [dapr/dotnet-sdk#1424]
When I want to subscribe subscription handlers for PubSub, I use the following code:
```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapSubscribeHandler(); // This is the Dapr subscribe handler
    endpoints.MapControllers();
});
```

Although the code works and I do see the /dapr/subscription endpoint called succesfully, it also raises a compiler warning ASP0014 indicating that using top level route registrations is recommended.

I'm using the  Dapr .NET SDK in a .NET Aspire project with .NET 9 and all the latest and greatest and I would like to be able to map the subscription handlers without the compiler warning.

**Comment by WhitWaldo** [comment]
It looks like you might have pulled that out of one of the .NET 6 examples. You indicate you're using .NET 9, so replace that block of code with the following:

```cs
app.MapSubscribeHandler();
app.MapControllers();
```

The various examples will be updated when .NET 6 support is discontinued in v1.16, but they're still relevant to the older version for now.

**Comment by WhitWaldo** [comment]
@nikneem Was the above guidance able to resolve your issue?

**Comment by nikneem** [comment]
Het @WhitWaldo, yes it was indeed! God rid of the warning and runs like a charm. Thanks a bunch!

Issue can be closed obviously 👌🏻
