### ISSUE TITLE
Async main in console

### ISSUE THREAD

**Issue by JamesNK** [dapr/dotnet-sdk#144]
Is there a reason why the Main method here is not async?

https://github.com/dapr/dotnet-sdk/blob/07fa2c615dd4c5c9df35947f7fc7262d8205ae94/samples/Grpc/GrpcClient/Program.cs

Making this method async will allow you to replace `.GetAwaiter().GetResult();` with `await`.

Details: https://blogs.msdn.microsoft.com/mazhou/2017/05/30/c-7-series-part-2-async-main/

**Comment by amanbha** [comment]
No specific reason, yes, It can be made async.
