### ISSUE TITLE
AddDapr() should return IMvcBuilder instead of void

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#146]
## Expected Behavior

It's conventional with MVC builder methods to return the `IMvcBuilder` to support chaining. We forgot this on `AddDapr().

**Compiles**

```C#
            services
                .AddControllers()
                .AddJsonOptions(options => { ... })
                .AddDapr();
```

**Doesn't compile**

```C#
            services
                .AddControllers()
                .AddDapr()
                .AddJsonOptions(options =>{ ... });
```

This was just missed while building this out. I'd be happy to send a PR

**Comment by amanbha** [comment]
Thanks @rynowak I have assigned it to you.
