### ISSUE TITLE
Allow actor type be specified during registration

### ISSUE THREAD

**Issue by philliphoff** [dapr/dotnet-sdk#164]
Currently actors are registered via: 

```csharp
Dapr.Actors.Runtime.ActorRuntime.RegisterActor<TActor>(Func<ActorTypeInformation, ActorService> actorServiceFactory = null)
```
The "type" of the registered actor is inferred from the actor implementation class name.  However, clients of the actor must specify the same type string when invoking actor methods.  This makes the implementation class name an implicit component of the actor contract, subject to the risk of breaking the contract due to an innocent refactoring of the implementation.

Proposal:

Add an overload that allows passing an explicit actor type string, which can then be a shared contract between implementation and client (alongside the actor interface definition):

```csharp
Dapr.Actors.Runtime.ActorRuntime.RegisterActor<TActor>(string actorType, Func<ActorTypeInformation, ActorService> actorServiceFactory = null)
```

**Comment by amanbha** [comment]
@philliphoff This sounds good. Would you like to do a PR for this?

**Comment by philliphoff** [comment]
Sure!
