### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by Shawn-Fan** [dapr/dotnet-sdk#167]
It looks like too early to ask this question, but I am still wondering if you guys have a road map for a n example application like "dotnet-architecture/eShopOnContainers" ?

**Comment by amanbha** [comment]
@Shawn-Fan  This is currently not on our roadmap. If you want to try and help the project with the port, it would be really appreciated by the team.

**Comment by Shawn-Fan** [comment]
Thanks in advance

**Comment by shaggygi** [comment]
Not .NET, but referencing... [How to get the App running on dapr?](https://github.com/dapr/dapr/issues/774) and [microservices-demo](https://github.com/GoogleCloudPlatform/microservices-demo).

**Comment by Shawn-Fan** [comment]
@shaggygi Sound exciting, Polyglot reactive microservices in the future. Any plan yet?

**Comment by amanbha** [comment]
@shaggygi  & @Shawn-Fan Polyglot would be a good sample, Could you please open it in samples repo, this repo is for dotnet sdk only.

**Comment by Shawn-Fan** [comment]
Sorry, @amanbha, Please close this topic.
