### ISSUE TITLE
Dependency injection for Actors

### ISSUE THREAD

**Issue by Xorpio** [dapr/dotnet-sdk#171]
Ass the basis of the Actor project is a .net core webapp we should be able to use the asp.net Dependecy Injection framework. However if you try to use it now the ActorService cannot create the Actor as it is not setup to create actors with other constructors.
see:
https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Actors/Runtime/ActorService.cs#L43

**Comment by amanbha** [comment]
@Xorpio When you register your actor, you can provide a Func to create Actor instances, it will be sued to create your actor instances, you can inject through this Func.
`actorRuntime.RegisterActor<DemoActor>(
                (type) =>
                new ActorService(type, (actorService, actorId) =>
                new DemoActor(actorService, actorId)));`

**Comment by Xorpio** [comment]
Great! Missed that one. Works like a charm. Thanks!

**Comment by neildonkin** [comment]
I like this approach, but how does it work if you want to inject an instance of `ILogger` into your actor's constructor?  How do you obtain an instance of ILogger within the `CreateHostBuilder` method?

**Comment by guihlk** [comment]
> I like this approach, but how does it work if you want to inject an instance of `ILogger` into your actor's constructor? How do you obtain an instance of ILogger within the `CreateHostBuilder` method?

Hi @neildonkin,
I instead followed the steps provided here [https://github.com/dapr/dotnet-sdk/issues/255#issuecomment-624382344](https://github.com/dapr/dotnet-sdk/issues/255#issuecomment-624382344) in #255 and it worked. Basically you do not need to inject the ILogger from withing the CreateHostBuilder. It can simply turn into:
```
.UseActors(actorRuntime =>
                {
                })
```

And then, together with the actor registration, you define a factory. Not the ideal answer to your question, but maybe you end up achieving the same outcome?

The registration then ends up basically like:
. . .
`services.AddActor(MyActorFactory)`
. . .
```
private static MyActor MyActorFactory(ActorService service, ActorId id, IServiceProvider provider) =>
          new MyActor (
              service,
              id,
              provider.GetRequiredService<IMyCustomService>());
```
Just remember registering your custom services before adding them within the actor factory.

**Comment by rynowak** [comment]
I'm reopening this issue - I was playing with this over the weekend and I didn't end up finding a solution that made me happy. We shouldn't require as much code as https://github.com/dapr/dotnet-sdk/issues/255#issuecomment-624382344 to solve this. 

Basic task like getting a logger instance inside an actor are too hard.

**Comment by guihlk** [comment]
Thanks, @rynowak 
That's a very nice approach to the problem

**Comment by neildonkin** [comment]
@guihlk thank you very much for the additional information and sample code.

**Comment by neildonkin** [comment]
> Basic task like getting a logger instance inside an actor are too hard.
> 
> There's a long history in ASP.NET Core of users having problems with "split brain" when there are two DI containers, two instances of the logging system, etc. Since we provide ASP.NET Core integration this should do the right thing by default.

@guihlk I agree 100% with you on this.  Thanks very much for re-opening this issue.

**Comment by guihlk** [comment]
> > Basic task like getting a logger instance inside an actor are too hard.
> > There's a long history in ASP.NET Core of users having problems with "split brain" when there are two DI containers, two instances of the logging system, etc. Since we provide ASP.NET Core integration this should do the right thing by default.
> 
> @guihlk I agree 100% with you on this. Thanks very much for re-opening this issue.

thanks mate @neildonkin , but it was @rynowak who reopened the issue hehe

**Comment by pohorely** [comment]
Of course you don't need to have 2 DI containers when using ASP.NET Core ;-)

I agree that it should be available from NuGet package without need to code it again in an app. Maybe I can check the current code and prepare a pull request. I am a little busy, so it may take a week or two...

Are you are interested in?

**Comment by rynowak** [comment]
# Summary

Make it easy to use Actors with DI by enabling dependency injection when using ASP.NET Core. In theory the current Actor runtime provides a way to *wire up* a dependency injection container - but in practice this is too much manual work and it's actually very hard to get the right behavior.

## Desired state

Each Actor type has an ActorRegistration which configuration options specific to that Actor type
- The actor runtime has an "activator" service that's responsible for creation/destruction of actors
- When using ASP.NET Core the actor runtime will have a default "activator" service that uses DI

Each Actor type has a constructor that accepts:
- an instance of `ActorService` that must be passed to the base constructor
- arbitrary other parameters to be satisfied from DI
- the `ActorService` acts as a parameter object allows us to bundle all of the functionality that needs to be passed to the base class without further API changes
- the ActorId is now part of `ActorService`
- features that are not intended for consumption in an Actor instance are moved elsewhere (from `ActorService`)

Each Actor Instance gets its own DI scope
- Scoped services resolved from DI share the same lifetime as the Actor instance
- Disposable transients accessed from the Actor instance will be disposed on Actor deactivation

## Example

Here's a design proposal for what the UX would look like:

```C#
public class MyCoolActor : Actor, IIceCreamVendor
{
    private readonly IceCreamRepository repo;

    public MyCoolActor(ActorService service, IceCreamRepository repo)
        base(service)
    {
         this.repo = repo;
    }
    
    public async Task<IceCream> ServeAsync(IceCreamOrder order)
    {
        // do something amazing here with 'this.repo'
    }
}
```

## API Changes

I'll make a list of API changes as I'm going through this and building it:

- Actor constructor signature *changes* (see above)
- Remove `IActorService` (why does it exist)
- Changes to properties on `ActorService`
- Changes to how Actors are registered in non-mainline cases

**Comment by iskandersierra** [comment]
If we can make the `IServiceProvider` instance get into the `ActorSystem`, then we can replace this [line](https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Actors/Runtime/ActorService.cs#L54), which is using `Activator.CreateInstance`, by `ActivatorUtilities.CreateInstance` [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.activatorutilities.createinstance?view=dotnet-plat-ext-5.0), which expects you to pass a `IServiceProvider` as well as some non-injected parameters.

In this [line](https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Actors.AspNetCore/WebHostBuilderExtensions.cs#L62), we could pass the `IServiceProvider s` to the `ActorRuntime`, and then the `ActorRuntime` can pass the provider to the `ActorService` in this [line](https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Actors/Runtime/ActorRuntime.cs#L37).

@rynowak If you are on not working on this already, I can have a try this weekend to make a PR for this.
