### ISSUE TITLE
Make it possible to create unit tests for Actors

### ISSUE THREAD

**Issue by Xorpio** [dapr/dotnet-sdk#173]
Right now i can't create a actor inside a unit test. Take the following Actor code for example

    public class TestActor : Actor
    {
        public TestActor(ActorService actorService, ActorId actorId) : base(actorService, actorId)
        {
        }

        public async Task<string> GetString()
        {
            return await StateManager.GetStateAsync<string>("Test");
        }
    }
And using the following unit test:

        [Test]
        public async Task CanCreateActor()
        {
            var actor = new TestActor(
                new ActorService(
                    new ActorTypeInformation()
                ),
                new ActorId("Test")
            );

            Assert.IsInstanceOf<Actor>(actor);
        }

When i run the unit test it throws a NullRefference exception

```
Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    Actor.ctor(ActorService actorService, ActorId actorId)
    TestActor.ctor(ActorService actorService, ActorId actorId) line 12
    IAMEmployeeTest.CanCreateActor() line 19
    GenericAdapter`1.GetResult()
    AsyncToSyncAdapter.Await(Func`1 invoke)
    TestMethodCommand.RunTestMethod(TestExecutionContext context)
    TestMethodCommand.Execute(TestExecutionContext context)
    SimpleWorkItem.PerformWork()
```

**Comment by amanbha** [comment]
@Xorpio Thanks for reporting. Will using Moq and setting them correctly for ActorService help in this case? Or do you have other suggestions in mind?

**Comment by Xorpio** [comment]
The problem is that there are some hardcoded dependencies that cannot be faked. (as far as i know). Like on this line:
https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Actors/Runtime/Actor.cs#L42

**Comment by malotho** [comment]
Any traction on this?

**Comment by malotho** [comment]
@Xorpio please check out this work. 
https://github.com/Ignition-Group-Open-Source-Contrib/DaprDotnetActorUnitests. Code coverage, and 100% testebility on the actor.

**Comment by Xorpio** [comment]
Oh nice work. it looks like a working solution. I can look further in depth in the coming days.

**Comment by malotho** [comment]
@amanbha should this issue be closed?

**Comment by amanbha** [comment]
@malotho I would suggest to keep it open to track more improvements needed in SDK itself to make it easier to write unit tests.

**Comment by malotho** [comment]
@amanbha that makes sense.

**Comment by amanbha** [comment]
Keeping this open for tracking more improvements to making actor unit tests

**Comment by onionhammer** [comment]
The advice here appears very outdated... is there any examples with updated SDK references on how to do unit testing with actors?
