### ISSUE TITLE
Reminder will not restore state correctly - End of Stream encountered exception

### ISSUE THREAD

**Issue by codeputer** [dapr/dotnet-sdk#182]
## Expected Behavior
when reminder is activated, the state returned is 9 bytes, the bytes sent was 421 - error on deserialization  - End of stream encountered before parsing was complete....

## Actual Behavior

returned only 9 bytes, then failure

## Steps to Reproduce the Problem

Set a reminder with State over 9 bytes ( mind was 421)
![DaprrRemindIssue](https://user-images.githubusercontent.com/611541/70368875-a95a7100-186d-11ea-95d0-cf11d834de07.png)

**Comment by amanbha** [comment]
@codeputer I have fixed the issue. It will be part of next release. You can sync and build the master branch now to try it.
