### ISSUE TITLE
How to debug in "Invoke Actor method without Remoting over Http"?

### ISSUE THREAD

**Issue by Shawn-Fan** [dapr/dotnet-sdk#183]
Using the example in "dotnet-sdk/samples/Actor/ActorClient/", I am wondering if it is possible to debug the code by applying curl command "curl -X POST ....." ?

**Comment by amanbha** [comment]
@Shawn-Fan, when you make curl calls, they will directly go to Dapr runtime which will route it to your actor service. Yes, so you can attach debugger to your Actor Service process.

**Comment by Shawn-Fan** [comment]
@amanbha , Thanks for quick response. I use vs 2019 but it can not touch the debug point of the source code when I run curl command, could you let me know the right way?

**Comment by amanbha** [comment]
@Shawn-Fan  Could you please share some screenshots showing the steps?

**Comment by Shawn-Fan** [comment]
**step 1** 
PS C:\Users\Ac\Desktop\Dapr\dotnet-sdk-master\samples\Actor\demoactor> dapr run --port 3500 --app-id demo_actor --app-port 5000 dotnet run          Starting Dapr with id demo_actor. HTTP Port: 3500. gRPC Port: 54821
You're up and running! Both Dapr and your app logs will appear here.

[93;1m== DAPR == time="2019-12-11T19:29:02-07:00" level=info msg="starting Dapr Runtime -- version 0.2.0 -- commit c75b111-dirty"
[0m[93;1m== DAPR == time="2019-12-11T19:29:02-07:00" level=info msg="log level set to: info"
[0m[93;1m== DAPR == time="2019-12-11T19:29:02-07:00" level=info msg="standalone mode configured"
[0m[93;1m== DAPR == time="2019-12-11T19:29:02-07:00" level=info msg="dapr id: demo_actor"
[0m[93;1m== DAPR == time="2019-12-11T19:29:02-07:00" level=info msg="loaded component messagebus (pubsub.redis)"
[0m[93;1m== DAPR == time="2019-12-11T19:29:02-07:00" level=info msg="loaded component statestore (state.redis)"
[0m[93;1m== DAPR == time="2019-12-11T19:29:02-07:00" level=info msg="application protocol: http. waiting on port 5000"
[0m[94;1m== APP == Hosting environment: Development
[0m[94;1m== APP == Content root path: C:\Users\Acer\Desktop\Dapr\dotnet-sdk-master\samples\Actor\demoactor
[0m[94;1m== APP == Now listening on: http://localhost:5000
[0m[94;1m== APP == Application started. Press Ctrl+C to shut down.
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="application discovered on port 5000"
[0m[94;1m== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
[0m[94;1m== APP ==       Request starting HTTP/1.1 GET http://127.0.0.1:5000/dapr/config application/json
[0m[94;1m== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
[0m[94;1m== APP ==       Request finished in 14.2156ms 200
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="application configuration loaded"
[0m[93;1m== DAPR == 2019-12-11 19:29:06.323004 I | redis: connecting to localhost:6379
[0m[93;1m== DAPR == 2019-12-11 19:29:06.325008 I | redis: connected to localhost:6379 (localAddr: [::1]:54837, remAddr: [::1]:6379)
[0m[94;1m== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
[0m[94;1m== APP ==       Request starting HTTP/1.1 GET http://127.0.0.1:5000/dapr/subscribe application/json
[0m[94;1m== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
[0m[94;1m== APP ==       Request finished in 1.2128ms 404
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="actors: starting connection attempt to placement service at localhost:6050"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="http server is running on port 3500"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="gRPC server is running on port 54821"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="local service entry announced"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 3708.8956ms"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="actors: established connection to placement service at localhost:6050"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="actors: placement order received: lock"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="actors: placement order received: update"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="actors: placement tables updated"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="actors: placement order received: unlock"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="actors: placement order received: lock"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="actors: placement order received: update"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="actors: placement tables updated"
[0m[93;1m== DAPR == time="2019-12-11T19:29:06-07:00" level=info msg="actors: placement order received: unlock"
[0m[94;1m== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
[0m

**step 2** 
PS C:\Users\Ac> c:/curl/curl1 -X POST http://localhost:3500/v1.0/actors/DemoActor/abc/method/SaveData -d '{\"propertyA\":\"valueA1\",\"propertyB\":\"valueB1\"}'
null

**step3**
[0m[94;1m== APP ==       Request starting HTTP/1.1 POST http://127.0.0.1:5000/actors/DemoActor/abc application/json 0
[0m[94;1m== APP == Actor: abc Activated
[0m[94;1m== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
[0m[94;1m== APP ==       Request finished in 30.657300000000003ms 200
[0m[94;1m== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
[0m[94;1m== APP ==       Request starting HTTP/1.1 PUT http://127.0.0.1:5000/actors/DemoActor/abc/method/SaveData application/json 45
[0m[94;1m== APP == This is Actor id abc with data PropertyA: valueA1, PropertyB: valueB1.
[0m[94;1m== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
[0m[94;1m== APP ==       Request finished in 4301.8859ms 200
[0m  

**step4**
![image](https://user-images.githubusercontent.com/15960295/70677865-9a990300-1c4d-11ea-8b8c-5f6703402556.png)

**Comment by amanbha** [comment]
After step 1, you should attach debugger to DemoActor process.  Debug-Attach to Process.

**Comment by Shawn-Fan** [comment]
Could let me know how to "Iattach debugger to DemoActor process. Debug-Attach to Process."?

**Comment by ddobric** [comment]
I suggest to provide asap F5 debugging experience n VS. This is how enterprise developers works with VS and .NET. Anything else feels as a workaround and makes the efficiency an enterprise developer very bad.

**Comment by codeputer** [comment]
I found that it's a better (?) environment to use Visual Studio code than VS 2019.  

I  actually feel like a newly born fawn trying to stand up, and my legs simply not knowing what to do next.

So much is new, Dapr as a runtime, docker, containers, actor framework, grpc , and all on Linux containers!

On top of all this, DAPR on  dot net doesn't even feel like it's a main focus, but just another side project of DAPR in general with a host of other languages in the mix.

Thinking an F5 vs 2019 is a main focus point is simply not in the mix as I see it.

DAPR focus is on VS code, and as we ask our business user to always adapt to new software, I think we too can't put our feet in the sand either.

Do I like moving to VS code... Nope, not a bit.  But slowly,slowly I'm growing my understanding of this new world, and making sense of it all.

With SF too expensive to run, and SF mesh NOT becoming a reality, I'm hoping this is where Actors on a mesh will exist....but then coyote also has reared its implementation.

Also DAPR exist as an incubation project from the office of the CTO, which makes it outside of MS Research...the more traditional path for these projects IMO.  Why that is is a concern IMO for the long term viability and support of DAPR as well.

In the end, I'm learning, and that's what I'm focusing on.  Building large scale  distributed applications is my focus, and this project is enhancing that knowledge.
