### ISSUE TITLE
gRPC(Grpc) Roadmap

### ISSUE THREAD

**Issue by Shawn-Fan** [dapr/dotnet-sdk#187]
It looks like you guys are working on gRPC, I am just wondering if you have a roadmap of gRPC for the dapr/dotnet-sdk?

**Comment by amanbha** [comment]
@Shawn-Fan Currently we have autogenerated gRPC clients from proto files. We would create convenience wrapper apis on top of the autogenerated once, but we are not actively working on it as of now.

**Comment by Shawn-Fan** [comment]
thanks
