### ISSUE TITLE
abp integrate Dapr

### ISSUE THREAD

**Issue by xewn** [dapr/dotnet-sdk#190]
[abp integrate Dapr](https://github.com/abpframework/abp/issues/2183)
Any better suggestions?

**Comment by amanbha** [comment]
@xewn It would be to good to generate Dapr integration code leveraging state management, pubsub capabilities for Dapr.

**Comment by amanbha** [comment]
@xewn ARe mor einputs needed for this, I am closing this issue, please feel free to reopen
