### ISSUE TITLE
Is this a typo in the StateHttpClient?

### ISSUE THREAD

**Issue by darraghjones** [dapr/dotnet-sdk#192]
When BaseAddress is not null, the separator looks to be missing between StatePath and Key

https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Client/StateHttpClient.cs#L57

**Comment by rynowak** [comment]
`StatePath` has a leading `/`. https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Client/DaprUris.cs#L12

Writing URI paths this way is a habit of mine based on `PathString` which requires the leading slash (asp.net core). It's a convetion that makes segments easier to concatenate.

**Comment by darraghjones** [comment]
But I was pointing out there is no "/" here: `$"{StatePath}{key}";`

**Comment by rynowak** [comment]
Ah, I think you're right. I'll submit a fix.
