### ISSUE TITLE
Improvements to dapr client

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#197]
## Describe the proposal

This is a larger issue to propose, debate, and track completion of some larger improvements to the dapr client for dotnet-sdk. Consider all of this up for discussion for now until we decide on direction.

I've already worked through some of these, I plan to send as piecemeal improvements if they are wanted. 

We can discuss all of these line-items and then turn them into individual work items as needed.

## Open questions

**Q:** Should we have a separate client class for each of concerns dapr has? (state, publish, invoke)

I did the initial draft of `Dapr.Client` and defined state as its own class (`StateClient`). Since then we've had an `InvokeClient` contributed, and now have an issue for `PublishClient`. We've arrived at 3 organically.

I don't have a strong feeling here, I think there are advantages to both, however it looks like the prevailing style of all of the other SDKs is a single client type - and that's also what gRPC is going to generate.

---

**Q:** Should we drop the HttpClient based implementation and make the gRPC client the only production client?

I discussed this idea with @yaron2 a while ago and we were leaning this way to reduce maintenance pain and investment. However, it looks like since then there's an open item tracking doing this for Java - https://github.com/dapr/java-sdk/issues/21. 

## General

- Add C#8 nullability - this has a pretty small impact on the overall dapr (non-actor) API surface. (have done)
- Unify gRPC and HTTP APIs - the `Dapr.Client.Grpc` library doesn't implement any of the abstractions used in `Dapr.Client`.

## Missing Features

- Add publish client for HTTP
- Add support for options [described here](https://github.com/dapr/docs/blob/master/reference/api/state.md#request-body)
- Add support for ETags (have prototype)
- Add support for save operations with multiple keys

## HttpClient-specific work

- Correct error handling (have done) - the error handling code here doesn't handle all of the important cases, and doesn't understand dapr's error format yet
- Correct handling of non-utf8 responses (have done)  - the client is hardcoded right now to interpret all responses as utf8. I can't think of a reason why you'd ever encounter non-utf8 responses - but this isn't a good bug to have and its easy to fix.
- Optimize use of JSON serializer (we allocate unnecessarily in some cases)

**Comment by darraghjones** [comment]
Regarding unification of the gRPC and HTTP APIs, how about having 3 nuget packages?
Dapr.Client.Abstractions
Dapr.Client.Http
Dapr.Client.Grpc

**Comment by yaron2** [comment]
For unification and consistency, the SDK should probably be more prescriptive. We are having the same discussion for the Java SDK now.

> Unify gRPC and HTTP APIs - the Dapr.Client.Grpc library doesn't implement any of the abstractions used in Dapr.Client.

> Should we drop the HttpClient based implementation and make the gRPC client the only production client?

Definite yes. We should use gRPC for everything besides actors, which are not implemented in the Dapr gRPC proto yet, but there's an [open issue](https://github.com/dapr/dapr/issues/927) for it.

There's no reason to not use gRPC everywhere to call into Dapr.

> Should we have a separate client class for each of concerns dapr has? (state, publish, invoke)

A single user facing client is best. It can orchestrate and encapsulate internal clients if it needs to.

**Comment by amanbha** [comment]
@rynowak A single client is better.
Usage could be:

Reg. Packaging, following are my thoughts:
Dapr.Client  (Contains interfaces/abstract classes)
Dapr.Client.Grpc (Implements the interface in Dapr.Client Over gRPC, its a wrapper over auto-generated gRPC client)

If needed we can keep following:
Dapr.Client.Http (Implements interfaces Over Http)

 `
var httpClient = new HttpClient();
var daprClient = new DaprClient(httpClient);
daprClient.SaveStateAsync<T>(...);
daprClient.GetStateAsync<T>(...);
daprClient.PublishEvent(...);
daprClient.InvokeService(...);
daprClient.InvokeBinding(...);
`
As a starting point, Api signatures could be: https://gist.github.com/amanbha/0156528aca408d893d11ba5533a7c4d5

**Comment by amanbha** [comment]
Granular items for this are:
https://github.com/dapr/dotnet-sdk/issues/226
https://github.com/dapr/dotnet-sdk/issues/225
https://github.com/dapr/dotnet-sdk/issues/224
https://github.com/dapr/dotnet-sdk/issues/223
https://github.com/dapr/dotnet-sdk/issues/222
