### ISSUE TITLE
Use Orleans as Actor Framework

### ISSUE THREAD

**Issue by ElderJames** [dapr/dotnet-sdk#201]
## Describe the proposal
Orleans is a great Actor Framework, we can use Orleans to handle actor-to-actor in the same application and use dapr to proxy the messaging between different application.

**Comment by amanbha** [comment]
While Orleans is a good Actor framework but its C# only. Dapr runtime has an in built virtual Actor framework built into it which encapsulates core functionalities of Actors (turn based concuurrency, activation/deactivation, placement reminders etc) in the runtime. This allows users to can write Actors in any language and make cross language Actor calls. We would like users to use Dapr's in built Actor model and help us improve it. At this point team doesn't plan to integrate with Orleans as an aCtor framework.
For messaging between Application, the apps can use Dapr's pubsub or Service Invocation capabilities.
