### ISSUE TITLE
Connect to daprd using loopback ipv4 or ipv6 address instead of localhost

### ISSUE THREAD

**Issue by LMWF** [dapr/dotnet-sdk#215]
## Expected Behavior

The sdk connects to daprd using localhost which may hit issues similar to https://github.com/dapr/java-sdk/issues/210.  The sdk should explicitly use the ipv4 or ipv6 loopback address through a configuration.

## Actual Behavior

"localhost" is used to connect to daprd today.

**Comment by RicardoNiepel** [comment]
Already done with: #214

**Comment by amanbha** [comment]
fixed with https://github.com/dapr/dotnet-sdk/pull/214
