### ISSUE TITLE
Using output bindings (writing to blobstore)

### ISSUE THREAD

**Issue by larserikfinholt** [dapr/dotnet-sdk#217]
## Ask your question here
Will there be any built in support for writing/reading to blobstore from the dotnet-sdk? 

Or should we be using the InvokeClient and pass in some different data based on what binding we are using? It would be great to see a sample of working with blobstorage.

**Comment by amanbha** [comment]
@larserikfinholt Dotnet sdk will be adding APIs to write to bindings. Currently the auto generated grpc wrapper can be used to make calls to dapr to invoke a binding. Where that binding writes is determined by the components configured with Dapr, so when invoking a binding for blob storage it will write to blob storage, Its explained here https://github.com/dapr/docs/tree/master/concepts/bindings

**Comment by amanbha** [comment]
@larserikfinholt

**Comment by larserikfinholt** [comment]
@amanbha  sorry, I did not understand. Will the dotnet sdk:

* a) Provide a generic Invoke command that takes in an object and leave it the rest to the developer
* b) Add additional API that helps developers perform generic blob task like read/write/list folders / blobs etc

**Comment by amanbha** [comment]
@larserikfinholt Output bindings are provided by Dapr runtime. 
dotnet sdk will provide api to invoke a binding via Dapr runtime https://github.com/dapr/dotnet-sdk/issues/223 
dotnet sdk will not provide apis to work with blobs directly.
I hope it clarifies, please let me know if you have any more questions or need more clarification.
