### ISSUE TITLE
Support optional behaviours in the `SaveStateAsync` method

### ISSUE THREAD

**Issue by pacodelacruz** [dapr/dotnet-sdk#221]
## Describe the proposal

I'd expect the `SaveStateAsync` method to support the use of [optional behaviours](https://github.com/dapr/docs/blob/master/reference/api/state.md#optional-behaviors), such as 

- concurrency
- consistency
- retry policy

This is somehow mentioned in #197 , but I believe it deserves an independent issue for tracking purposes. 

Additionally, these might have a dependency on [#142 ](https://github.com/dapr/dotnet-sdk/issues/142)

**Comment by amanbha** [comment]
@pacodelacruz Yes, its on the plan and we will be overhauling our client apis in dotnet sdk, that work would add all these behaviors.

**Comment by amanbha** [comment]
Thsi should be handled by https://github.com/dapr/dotnet-sdk/issues/225
