### ISSUE TITLE
Dapr client to support multi-operation state requests (need runtime implementation)

### ISSUE THREAD

**Issue by pacodelacruz** [dapr/dotnet-sdk#222]
## Describe the proposal

The Dapr client should support multi-operation requests, i.e. atomic transactions as mentioned in the  [state management documentation ](https://github.com/dapr/docs/blob/master/concepts/state-management/state-management.md#bulk-operations)

**Comment by amanbha** [comment]
@pacodelacruz Thsi is being added in dapr runtime, once added to runtime, we will add support in sdks. https://github.com/dapr/dapr/pull/931

**Comment by wanton7** [comment]
Will that change allow me to retrieve and store multiple keys with actor StateManager? Currently I have to use things like
`await Task.WhenAll(commentIds.Select(id => StateManager.GetStateAsync<CommentState>("comment" + id)));`

It would be even greater if I could retrieve and store different kind of states with single call. Example something like StateManager would return multiple StateValue classes/structs and then you could get typed value from it by .GetValue<CommentState>().

**Comment by amanbha** [comment]
This request is for sdtate management api outside of actor and is requesting for addition of multiple state updates https://github.com/dapr/docs/tree/master/concepts/state-management#bulk-operations
Proto is https://github.com/dapr/dapr/blob/release-0.4/pkg/proto/dapr/dapr.proto#L21

**Comment by amolenk** [comment]
I believe we have this now with `DaprClient.ExecuteStateTransactionAsync`

**Comment by vinayada1** [comment]
Done.
