### ISSUE TITLE
Add examples of dotnet core gRPC service invocation to samples

### ISSUE THREAD

**Issue by TomHermolle** [dapr/dotnet-sdk#232]
I am struggling to implement the invocation of a dotnet core gRPC service via Dapr, and no example exists in the samples project.

I have found an example in the Java SDK, and attempted to work from that (although I don't know Java), but I haven't managed to get it working, so some examples/documentation of how to invoke services over gRPC in C# would be greatly appreciated, including how to implement streaming calls.

**Comment by sebader** [comment]
I am using this (not sure if this is best practice, though). So any feedback welcome as well.

````
using static Dapr.Client.Grpc.Dapr;

var defaultPort = Environment.GetEnvironmentVariable("DAPR_GRPC_PORT") ?? "52918";
// Create Client
var daprUri = $"http://127.0.0.1:{defaultPort}";
var channel = GrpcChannel.ForAddress(daprUri);
DaprClient grpcClient = new DaprClient(channel);

var getStateEnvelope = new GetStateEnvelope()
{
	StoreName = "mystore",
	Key = myId,
};

var response = await grpcClient.GetStateAsync(getStateEnvelope);

if (!response.Data.Value.IsEmpty)
{
	// do something with the value
}

````

**Comment by amanbha** [comment]
@sebader Thsi seems fine. We are int he process of refactoring our SDK and we will be providing wrapper methods for App-> Dapr calls which will under the hood use autogenerated gRPC clients from proto. This it he main issue tracking the work and it will be part of our next release https://github.com/dapr/dotnet-sdk/issues/197

**Comment by TomHermolle** [comment]
@sebader thanks for your response - I had also managed to access the statestore and publish events over gRPC without difficulty, but this issue more specifically relates to the invocation of another microservice over gRPC and Dapr i.e. Service A <-> Service B becomes Service A <-> Dapr A <-> Dapr B <-> Service B.

I have subsequently managed to get this working, although I think I've discovered a couple of bugs in Dapr.Client.Grpc in the process. I'll create a sample repo and link to it when I get a chance.

@amanbha do you know whether the refactoring work will allow streaming calls from service - service over gRPC, or will they still be unary as they are at present? i think the lack of streaming calls will be a bit of a blocker for my app.

**Comment by amanbha** [comment]
@TomHermolle The calls would be unary, the Dapr runtime itself doesnt support it.

**Comment by amanbha** [comment]
With the refactored client the code snippet is added to samples https://github.com/dapr/dotnet-sdk/commit/51fc48fb743204d6e2a830bfb12568d1231fa410#diff-d43fb1cb49d2d5bea15afe07418dd112R87

Please feel free to reopen if you have more questions.
