### ISSUE TITLE
DaprError cannot be deserialized because of missing parameterless constructor

### ISSUE THREAD

**Issue by sebader** [dapr/dotnet-sdk#233]
## Expected Behavior

Code should run without such exceptions

## Actual Behavior

When [this line](https://github.com/dapr/dotnet-sdk/blob/7005e246240a4919863984c9ebf2a2206f9451c7/src/Dapr.Actors/DaprHttpInteractor.cs#L434) 
`error = await JsonSerializer.DeserializeAsync<DaprError>(contentStream);`

is reached, JsonSerializer cannot deserialize the DaprError and throws:

> {"Deserialization of reference types without parameterless constructor is not supported. Type 'Dapr.Actors.DaprError'"}

This then results in this

`throw new DaprException(string.Format("ServerErrorNoMeaningFulResponse", response.StatusCode), ex);`

instead of the actual response error being correctly deserialized and returned.

Sample response content:

`response.Content.ReadAsStringAsync().Result`:
`"{\"errorCode\":\"ERR_ACTOR_STATE_GET\",\"message\":\"not found\"}"`

[DaprError ](https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Actors/DaprError.cs)does not have a parameterless constructor. 
## Steps to Reproduce the Problem

Make any request that results in an error response

**Comment by sebader** [comment]
to add: When I added a parameterless constructor, the deserilization does not fail anymore. However, the new DaprError object is still empty (not message or error code set), so I guess there are also some serialization options needed.

**Comment by sebader** [comment]
@LMWF did you check that deserialization works properly with your new constructor? As I wrote above, I added a similar constructor in a quick test that I did and after deserialization the fields were not set.

**Comment by LMWF** [comment]
You are correct, sending a PR soon.
