### ISSUE TITLE
Error running Actor sample

### ISSUE THREAD

**Issue by iamalexmang** [dapr/dotnet-sdk#236]
My expectation is that I can follow the readme.md guide and test DAPR Actors.
However, I come across this error when I'm running the DemoActor, which prevents the ActorClient from initializing an actor instance of type DemoActor:
```
level=warning msg="either no actor state store or multiple actor state stores are specified in the configuration, actor stores specified: 0"

**Comment by codeputer** [comment]
I think it's state is not initialized.  Run " Dapr init" then run a docker command to see if you have a placement service/container, and a redis storage service/container.

R

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by amanbha** [comment]
@iamalexmang  I think you have ran sample with older version of Dapr earlier and older components yanl file is still used., A breaking change was introduced in latest release of DApr runtime which support multiple state stores. Could you please try with after deleting the components folder which is created by dapr cli in DemoActor directory. If you still see the issue, please share the components yaml in the folder.

**Comment by iamalexmang** [comment]
@amanbha, you were correct.
For anyone else coming across this issue, the problem I was facing was that I was using a component configuration file which was missing the 
  ```
- name: actorStateStore
    value: "true"
```
metadata from the state.redis component type.
The previous redis.yaml confg was replaced in the latest repo version with statestore.yaml.
