### ISSUE TITLE
Pub/Sub - WithTopic and Topic attribute conventions

### ISSUE THREAD

**Issue by perokvist** [dapr/dotnet-sdk#239]
## Guide to avoid breaking conversions of subscribers

It's easy to believe that an endpoint or controller route could differ from topic name.

```       
[Topic("sample")]
[HttpPost("something_else")]
```
or

```
endpoints.MapPost("/somethingelse", fun context -> 
      context.Response.WriteAsync("Hello sample")
).WithTopic("sample") |> ignore
```

Should the SDK care, or guide the user here ?
It's possible to setup a route that follow the conventions and forward to custom route, but is adding complexity.

**Comment by perokvist** [comment]
another topic is exposing these endpoint to the sidecar/localhost only.

**Comment by amanbha** [comment]
@rynowak for suggestion on route configuration in aspnetcore for topics.

**Comment by amanbha** [comment]
@perokvist IMO Mapping a route to topic name should be left to the user.
I am closing this issue, feel free to open if you have more questions.
