### ISSUE TITLE
Secret Store Grpc Client

### ISSUE THREAD

**Issue by cmendible** [dapr/dotnet-sdk#240]
## Describe the proposal

I know you are working to improve the dapr client as statedt in #197, but since the Secrets API endpoint has been merged (https://github.com/dapr/dapr/pull/1059 & https://github.com/dapr/dapr/pull/1085) a Secret Store grpc client should be provided

**Comment by amanbha** [comment]
@cmendible Thanks for adding the secrets api, This add s a new SecretsClient, I would wait and add the api api refactoring which is being done for DaprClient.

**Comment by cmendible** [comment]
> @cmendible Thanks for adding the secrets api, This add s a new SecretsClient, I would wait and add the api after refactoring which is being done for DaprClient, the calls would go over gRPC

Ohhh I see, so the http will be deprecated?

I just submitted #241 so I guess it will be a no go. If there is anyway I can help just let me know.

**Comment by amanbha** [comment]
> Ohhh I see, so the http will be deprecated?
Yes, non-actor calls from .net sdk will go over gRPC/
> I just submitted #241 so I guess it will be a no go. If there is anyway I can help just let me know.
Please modify the issue, to add it to DaprClient api over gRPC. This is the branch we will be working in https://github.com/dapr/dotnet-sdk/tree/one_client, currently it has an interface and a class please feel free to app secret api to this branch.
