### ISSUE TITLE
Can SDK use same default GRPC port as `daprd`?

### ISSUE THREAD

**Issue by philliphoff** [dapr/dotnet-sdk#257]
Currently the .NET SDK [defaults to using port `52918`](https://github.com/dapr/dotnet-sdk/blob/51fc48fb743204d6e2a830bfb12568d1231fa410/src/Dapr.Client/DaprClientBuilder.cs#L17) when `DAPR_GRPC_PORT` is *not* set.  Is there a specific reason for this port (e.g. it's the canonical port used by gRPC-based applications)?

The Dapr daemon (`daprd`) [defaults to port `50001`](https://github.com/dapr/dapr/blob/d8aa4008346735aa8e4746626c0a7a5eb4e9a9fa/pkg/runtime/config.go#L24) unless otherwise configured. This can cause a "gRPC connection refused" error in a user's application if the user starts `daprd` directly but does not explicitly configure one or both the Dapr sidecar and application to use the same port.  Would it make sense to settle on a single default port across the Dapr ecosystem?

**Comment by amanbha** [comment]
@philliphoff Sure, it can use 50001 by default. It relies on DAPR_GRPC_PORT when its launched by dapr.
If user is launching daprd manually then it can still fail if a mom-default port is specified for gRPC but app is not told about it.
