### ISSUE TITLE
Error starting gRPC call: Connection refused in Kubernetes

### ISSUE THREAD

**Issue by ryzam** [dapr/dotnet-sdk#264]
I'm using AspNetCore sample and try to running dapr in Kubernetes, unfortunately when try to call API I got this error:
`Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: Connection refused")
   at Dapr.Client.DaprClientGrpc.MakeGrpcCallHandleError[TResponse](Func2 callFunc, CancellationToken cancellationToken)
   at Dapr.Client.DaprClientGrpc.GetStateAndETagAsync[TValue](String storeName, String key, Nullable'1 consistencyMode, CancellationToken cancellationToken)`

**Comment by amanbha** [comment]
@ryzam is it from the master branch with project refs? Or you are using nugets?

**Comment by ryzam** [comment]
I'm using nuget

**Comment by cmendible** [comment]
@ryzam take a look at #263

**Comment by ryzam** [comment]
Tq @cmendible , btw i already pull from lastest repo, but now i got container error

` Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  64s                default-scheduler  Successfully assigned default/userservice-76d4d9dd86-jxrw7 to minikube
  Normal   Pulling    51s                kubelet, minikube  Pulling image "docker.io/daprio/dapr:latest"
  Normal   Created    42s                kubelet, minikube  Created container daprd
  Normal   Started    42s                kubelet, minikube  Started container daprd
  Normal   Pulled     42s                kubelet, minikube  Successfully pulled image "docker.io/daprio/dapr:latest"
  Normal   Pulling    15s (x3 over 63s)  kubelet, minikube  Pulling image "irwanazam/dapruserservice:v2"
  Normal   Created    5s (x3 over 51s)   kubelet, minikube  Created container userregistration
  Normal   Started    5s (x3 over 51s)   kubelet, minikube  Started container userregistration
  Normal   Pulled     5s (x3 over 51s)   kubelet, minikube  Successfully pulled image "irwanazam/dapruserservice:v2"
  Warning  BackOff    3s (x5 over 30s)   kubelet, minikube  Back-off restarting failed container`

**Comment by ryzam** [comment]
Tq, this issue resolve ....
