### ISSUE TITLE
DaprClient via gRPC: problem with object serialization 

### ISSUE THREAD

**Issue by GennadiiSvichinskyi** [dapr/dotnet-sdk#268]
## Expected Behavior

InvokeMethodAsync returns deserialized HelloReply object

## Actual Behavior

` Unhandled exception. System.Text.Json.JsonException: '0x13' is an invalid start of a value. Path: $ | LineNumber: 1 | BytePositionInLine: 0.`

## Steps to Reproduce the Problem

1. Create gRPC service with ASP.NET Core 3.1 (in VS 2019 it will be created with Greeter service sample), generate client classes from daprclient.proto (Service only). It also require darp.proto classes generation
2. Create implementation of DaprClientBase where on OnInvoke you receive HelloRequest and return HelloResponce objects.
2. Create ASP.NET Core console application, generate client classes from daprclient.proto (Client only), generate client classes from greet.proto (Client only)
3. Add reference on Dapr.Client package, create dapr client and call InvokeMethodAsync against gRPC service. Something like
`var msg = new HelloRequest() {Name = "Gennadii"};  
 var anyReply = await client.InvokeMethodAsync<HelloRequest, HelloReply>("testGrpcDapr", "SayHello", msg);`
4. Start both apps via Dapr with grpc protocol (I used standalone mode).

Test project attached. (there is a workaround there which is commented out there)
[TestGrpcWithDapr.zip](https://github.com/dapr/dotnet-sdk/files/4393549/TestGrpcWithDapr.zip)

**Comment by amanbha** [comment]
@GennadiiSvichinskyi The client package is using json serialization/deserialization. Serialization of HelloRequest is fine when sending the request but json deserialization of the response is failing, does your service method returns a json?

**Comment by GennadiiSvichinskyi** [comment]
@amanbha  No, according to the signature of the OnInvoke handler (Task<Any> OnInvoke(InvokeEnvelope request, ServerCallContext context)) I should return Any object
` var msg = new HelloReply() { Message = requestHelloRequest.Name };
var any = Any.Pack(msg);
return any;`
The problem is that System.Text.Json.JsonSerializer cannot deserialize Any object into my HelloResponse object.

**Comment by amanbha** [comment]
@GennadiiSvichinskyi From thes erverside, you can return serialized json as Any.
Please see here, how the Dapr client serializes your HelloRequest to Any and sends it to server https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Client/DaprClientGrpc.cs#L135

**Comment by GennadiiSvichinskyi** [comment]
@amanbha , okay, it s working, thanks. Although, I consider it as workaround because the standard Any.Pack(IMessage) is not working correctly. But if you take a collection instead of an object (or, in terminology of Google - message with repeated property) you get into the same trouble. Try generate from 
`message HelloRepeatedReply{
  repeated HelloReply replies = 1;
}`
then call something like GetRepeatedHelloReply and deserialization returns empty object.

**Comment by amanbha** [comment]
@GennadiiSvichinskyi Glad its working. I tend to agree that this falls in a workaround category, will look into it. If you have fixes in mind, would you like to contribute and do a PR.

**Comment by igalfsg** [comment]
@amanbha My proposed solution would be do parameter that is default to false, to cast the variable, if it is set to true instead of deserializing a json you cast the return string to the variable type passed. Also for user experience to catch the error and give a friendly error explaining the options. what do you think?

**Comment by jjindrich** [comment]
Hi @GennadiiSvichinskyi, please can you share you sample ? I'm looking for simple greeter demo using gpcs protocol

**Comment by igalfsg** [comment]
@jjindrich  here is the dapr official demo https://github.com/dapr/dotnet-sdk/blob/master/samples/Client/DaprClient/Program.cs, and here is a demo of my implementation https://github.com/coding-flamingo/K8sandHelm/blob/master/K8sFrontEnd/Pages/APITest.razor

**Comment by GennadiiSvichinskyi** [comment]
> Hi @jjindrich , I've a little bit updated it to DAPR 0.71 and put to [here](https://github.com/GennadiiSvichinskyi/test-grpc-dapr).  Hopefully, it will help you )

**Comment by codeputer** [comment]
Where is GreeterBase coming from - the proto files?

**Comment by jjindrich** [comment]
@GennadiiSvichinskyi many thanks for sharing demo !

**Comment by jjindrich** [comment]
@GennadiiSvichinskyi I tried to run your demo, but getting this error on server side:
Could not update sidecar metadata for cliPID: PUT http://127.0.0.1:58069/v1.0/metadata/cliPID giving up after 5 attempts
Updating metadata for app command: dotnet run
Could not update sidecar metadata for appCommand: PUT http://127.0.0.1:58069/v1.0/metadata/appCommand giving up after 5 attempts

**Comment by GennadiiSvichinskyi** [comment]
@jjindrich , http2 is Okay. As a note - I tested the solution with dapr in a 'standalone' mode locally. So, probably in 'kubernetes' mode it might have different ports or some additional settings

**Comment by jjindrich** [comment]
@GennadiiSvichinskyi I retested locally again in following steps:
1. starting server: PS C:\temp\test-grpc-dapr-master\test-grpc-dapr-master\TestGrpcWithDapr\bin\Debug\netcoreapp3.1> dapr run --app-id testGrpcDaprService --app-port 5000 --protocol grpc --log-level debug dotnet run
2. starting client: PS C:\temp\test-grpc-dapr-master\test-grpc-dapr-master\TestGrpcWithDapr.Client\bin\Debug\netcoreapp3.1> dapr run --app-id testClient --protocol grpc --log-level debug dotnet run testGrpcDaprService SayHello GrpcLover

When client is started, getting on serverside this message: 
Could not update sidecar metadata for cliPID: PUT http://127.0.0.1:55124/v1.0/metadata/cliPID giving up after 5 attempts
Updating metadata for app command: dotnet run
Could not update sidecar metadata for appCommand: PUT http://127.0.0.1:55124/v1.0/metadata/appCommand giving up after 5 attempts

On client side not receiving message.

**Comment by codeputer** [comment]
Clear your state containers and issue DAPR INIT to reset your state containers.  I find this clears this error.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jjindrich** [comment]
I did uninstall and init again, same result.

**Comment by GennadiiSvichinskyi** [comment]
@jjindrich you shouldn't run from 'bin' folders with 'dotnet run'. Go to the folder with .csproj file and run from there. Both server and client. I think that's the core of your problem.

**Comment by jjindrich** [comment]
@GennadiiSvichinskyi Thank you, now is working correctly.

**Comment by jjindrich** [comment]
@GennadiiSvichinskyi please can you help me how to call gRpc service (your greeting service running in Dapr) from outside of Dapr ?
I tried to call var client = new DaprClientBuilder().UseEndpoint("http://localhost:54702").Build(); but not returning message.

**Comment by jjindrich** [comment]
@GennadiiSvichinskyi If I good understand, when calling with dapr, on server side is not used GreeterService.SayHello method, correct ?

**Comment by GennadiiSvichinskyi** [comment]
@jjindrich, right. :) I've updated the solution with invoking existing GreeterService.

**Comment by akkie** [comment]
The question is why Dapr uses JSON serialization/deserialization internally for `Any` instead of using `Any.Pack` and `Any.Unpack` which protobuf supports out of the box?

**Comment by akkie** [comment]
Today I stumbled over the same issue @GennadiiSvichinskyi mentioned previously: https://github.com/dapr/dotnet-sdk/issues/268#issuecomment-605427567

A repeated field will not be deserialized! The .NET protobuf implementation uses the [Google.Protobuf.Collections.RepeatedField]( https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/collections/repeated-field-t-) to represent a list. It seems that the JSON deserializer cannot properly handle this type. There is an [open issue](https://github.com/protocolbuffers/protobuf/issues/6995) which suggests to use a `List` to make JSON serialization/deserialization easier. Nonetheless, this wouldn't occur if Dapr would use `Any.Pack` and `Any.Unpack` internally.

In my opinion, this is a serious issue, because Dapr quietly loses data when working with gRPC requests.

**Comment by amanbha** [comment]
Thanks for reporting it @akkie . Would love to have you contribute the fix, please let me know.
Could you also clarify how does the issue which you linked above refers to this one?

**Comment by akkie** [comment]
Sure, will try to contribute the fix. Would it be OK to replace the internal JSON encoding with the proto based serialization for the any type? Are there any edge cases I don't see currently?

Which linked issue do you mean exactly? I've linked two.

**Comment by amanbha** [comment]
> Sure, will try to contribute the fix. Would it be OK to replace the internal JSON encoding with the proto based serialization for the any type? Are there any edge cases I don't see currently?
> 
> Which linked issue do you mean exactly? I've linked two.

Great thanks @akkie. I was referring to https://github.com/PlanBGmbH/dapr-vote/issues/2. 
Currently all methods us System.Text.Json to serialize deserialize for methods like InvokeMethod, InvokeBinding, Publish, SaveState, it also takes options for the serializer. Would changing it internally change the behavior for those methods?

**Comment by akkie** [comment]
@amanbha 

It was not possible to use `Any.Pack` or `Any.Unpack` for any type, because these methods can only handle messages based on the `Google.Protobuf.IMessage` type. So I've implemented two conversion methods. If a type based on `Google.Protobuf.IMessage` is given then it uses the protobuf conversion and for all other types it uses JSON based conversion.

Please see: #358
