### ISSUE TITLE
ActorStateManager GetStateAsync and TryGetStateAsync methods should be thread safe

### ISSUE THREAD

**Issue by wanton7** [dapr/dotnet-sdk#271]
## Describe the proposal

Because actors state can be granulated (have multiple state names) I thought calling ActorStateManager actor methods `GetStateAsync` and `TryGetStateAsync` would be thread safe. So I could use `Task.WhenAll` to retrieve multiple state pieces simultaneous. But I just looked at the code and it's not thread safe because `Dictionary<string, StateMetadata> stateChangeTracker` is used for caching. 
Those methods should be thread safe or there should be a way to load multiple state pieces in single call.

**Comment by amanbha** [comment]
Its not thread safe as actors are single threaded, it will not be thread safe as it will make the code unnecessarily complex just for allowing a one off scenario.This follows the pattern of SF reliable Actors.

**Comment by wanton7** [comment]
Ok, but if state is granulated to like 100 parts getting those sequentially might be little bit slow.
Saw this from @yaron2 at gitter chat at https://gitter.im/Dapr/actors
> @vaclavpetr we could extend our state APIs to support BulkGet. can you open an issue for it? we can then discuss and possibly start work if triaged, or someone from the community might pick it up. In any case, until that is resolved, I suspect if you call Dapr 100 times for the keys in parallel you should be able to get it in under 200ms

I guess that is not possible then with dotnet SDK without using custom state management code.

**Comment by amanbha** [comment]
The state is cached in SDK, so its a one time call till the actor is active. If there is a bulk get implemented in runtime, then that can be exposed in SDK as well.

**Comment by wanton7** [comment]
Maybe it's time to think my state design of one of my actors then :) I created feature proposal for bulk state get yesterday https://github.com/dapr/dapr/issues/1338
I'll close this in favor if that then.
