### ISSUE TITLE
Calling Actor that returns void (Task) via Remoting throws XmlSerialization Exception

### ISSUE THREAD

**Issue by DavidHoerster** [dapr/dotnet-sdk#278]
## Expected Behavior

An actor that returns `void` (`async Task`) should be able to be called via Remoting

## Actual Behavior

Calling an actor method that returns `void` (`async Task`) via Remoting throws an XmlSerialization exception. Changing the call to the actor method using non-remoting succeeds.

## Steps to Reproduce the Problem

I have an actor defined as such:

```C#
    internal class GribSupervisorActor : Actor, IGribSupervisor
    {
        public GribSupervisorActor(ActorService actorService, ActorId actorId)
            : base(actorService, actorId)
        {
        }
        public async Task BeginProcessingScheduledGribFiles(BeginGribProcess msg)
        {
            var datetimestamp = DateTime.UtcNow.AddHours(-1);
            var date = datetimestamp.ToString("yyyyMMdd");
            var hour = datetimestamp.ToString("HH");
            ...
        }
    }
```

Calling it using remoting fails:

```C#
    var id = new ActorId("runner");
    var proxy = ActorProxy.Create<IGribSupervisor>(id, "GribSupervisorActor");
    await proxy.BeginProcessingScheduledGribFiles(new BeginGribProcess
    {
        FileTypes = names,
        Locations = locations
    });
```
The above throws an exception of XmlSerialization, saying that the response was not formatted correctly.

Calling the actor method without remoting succeeds:

```C#

    var id = new ActorId("runner");
    var proxy = ActorProxy.Create(id, "GribSupervisorActor");
    await proxy.InvokeAsync("BeginProcessingScheduledGribFiles", new BeginGribProcess
    {
        FileTypes = names,
        Locations = locations
    });
```

This seems similar to issue #129 which was closed.

My message that I'm passing to my actor method is such:

```C#
    public class BeginGribProcess
    {
        public IEnumerable<string> FileTypes { get; set; }
        public IEnumerable<Location> Locations { get; set; }
        public BeginGribProcess() { }
    }
```

I have received a similar issue with messages that do not have enumerables.

I'm using Dapr 0.5.1 and this is running in my AKS cluster (1.17).

**Comment by amanbha** [comment]
@DavidHoerster The samples have calls for the methods that return just a Task. i just ran it and could not repro:
https://github.com/dapr/dotnet-sdk/blob/master/samples/Actor/ActorClient/Program.cs#L49

Could you share the full exception as well?

**Comment by LMWF** [comment]
@DavidHoerster does this still repro on the latest version of dapr and dapr/dotnet-sdk (0.7)?

**Comment by amanbha** [comment]
Closing it due to lack of response, feel free to reopen, if it still happens.
