### ISSUE TITLE
PubSub not working when specifying a route attribute on AspNetCore Controllers 

### ISSUE THREAD

**Issue by etuboko** [dapr/dotnet-sdk#280]
## Expected Behavior

Specifying a route attribute on controller  should not disable PubSub topic registration.

Publishing events using Dapr should reach API using ASP.NET Core routing with specified route attributes at controller level.

## Actual Behavior

App is subscribed to the topics but published events are not reaching defined endpoints.

```
== DAPR == time="2020-04-04T11:47:42.658059-04:00" level=info msg="app is subscribed to the following topics: [deposit]" app_id=routing instance=Christians-MacBook-Pro.local scope=dapr.runtime type=log ver=0.6.0
```
## Steps to Reproduce the Problem

Using the Controller sample, specify a controller level template using ASP.NET Core routing.

```
[ApiController]  
[Route("/api")]
public class SampleController : ControllerBase
{
}
```

**Comment by etuboko** [comment]
Specifying a different template then the topic at the method level has the same effect 
```
 [Topic("deposit")]
 [HttpPost("/")]
 public async Task<ActionResult<Account>> Deposit(Transaction transaction, [FromServices] DaprClient daprClient)
 {
       ...         
 }
```

**Comment by rynowak** [comment]
This is pretty unfortunate, but reflects the way that pub/sub works in Dapr. The route has to match the topic name. When I discussed with the team earlier, we had the idea of enlightening the protocol to allow arbitrary URLs as routes. 

We could try to make this fail in some more obvious way like an error on startup, but the limitation you're hitting here is with Dapr's protocol not with the SDK.

/cc @yaron2 - we discussed this a while back, is there any interest in making pub/sub more flexible?

**Comment by etuboko** [comment]
Hi @rynowak ! Thanks for the comments and reference. My goal for the URI structure of the API is to make it logical, meaningful and predictable for clients. A foundational aspect in API design is that the API is Resource-centric. Operations (verbs) are represented via HTTP Verbs on these Resources, not in the URI space.  This limitation is preventing us from respecting this design aspect.

**Comment by yaron2** [comment]
Yes, we are planning on changing this. Being tracked here:
https://github.com/dapr/dapr/issues/843

**Comment by etuboko** [comment]
@yaron2 Thanks, great news!

**Comment by rynowak** [comment]
> A foundational aspect in API design is that the API is Resource-centric. Operations (verbs) are represented via HTTP Verbs on these Resources, not in the URI space. This limitation is preventing us from respecting this design aspect.

Yeah I complained about this too 👍
