### ISSUE TITLE
Failed to sTart Metrics Server on RoutingSample using DAPR extension

### ISSUE THREAD

**Issue by codeputer** [dapr/dotnet-sdk#281]
## Expected Behavior

Attempted to use the DAPR extension to run the routingSample application.  Expected it to run and attach the debugger, allowing get/post work, and allow break points in the code base of the project, and related projects.
![dockerimagesrunning](https://user-images.githubusercontent.com/611541/78628260-dc7b3400-7850-11ea-9ebb-e885ec962d4c.png)

## Actual Behavior
Attempts to start the application via daprd and fails, recording a fatal error message:
time="2020-04-06T21:44:55.9190433-06:00" level=info msg="metrics server started on :9090/" app_id=RoutingsSample instance=PHXHomeOfficeV2 scope=dapr.metrics type=log ver=0.6.0
time="2020-04-06T21:44:55.920044-06:00" level=fatal msg="failed to start metrics server: listen tcp :9090: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted." app_id=RoutingsSample instance=PHXHomeOfficeV2 scope=dapr.metrics type=log ver=0.6.0

## Steps to Reproduce the Problem
1) Fork/clone the repo: https://github.com/dapr/dotnet-sdk
2) Navigate to ...\dotnet-sdk\samples\AspNetCore\RoutingSample
3) open visual code in that directory (code . -r)
4) Dapr: Scaffold the project
5) Run the .Net Core Launch (web) with DAPR
6) Starts and fails
7) Docker ps shows no images running, and but Dapr extension show that it is running (?? - new to all of this Visual Code and Docker tech)

Solution fails to run, yet still appears in the DAPR application running (DaprExtensionShoulditRunning image)

![TerminalWindowOutput](https://user-images.githubusercontent.com/611541/78627937-f5cfb080-784f-11ea-8851-da23864947c2.png)
![DaprExtensionShoulditRunning](https://user-images.githubusercontent.com/611541/78628059-5363fd00-7850-11ea-8c9b-ec300c5c8e56.png)

![metricServerFailure](https://user-images.githubusercontent.com/611541/78627299-54942a80-784e-11ea-9ad8-c641a4c2df16.png)

**Comment by amanbha** [comment]
Is some other process listening on port 9090?

**Comment by codeputer** [comment]
Not that I know of.  I rebooted I got same result.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by amanbha** [comment]
There seems to be some one already listening on the port, Could you please check what is listening on port. If you are on windows you can use netstat.

**Comment by codeputer** [comment]
I believe this is the surfacing issue when old YAML files are used.  My project was several months old, and deleting all YAML file sin the components directory seems to have corrected this issue.
