### ISSUE TITLE
ActorProxy:Create method with a type parameter

### ISSUE THREAD

**Issue by jpiquot** [dapr/dotnet-sdk#283]
Hi,

Could we add an third Create method on the ActorProxy class with a type argument? To be able to make a call like this :

var myActor = (IMyActorProxy)ActorProxy.Create(new ActorId("dummy"), typeof(IMyActor), "MyActor");

**Comment by jpiquot** [comment]
Also add "Create" methods in the IActorProxy interface so we can inject the proxy in constructors. It will enable us to make tests easier. As we can then Mock the proxy.

**Comment by amanbha** [comment]
Could you please share the scenario and benefits of following:
> var myActor = (IMyActorProxy)ActorProxy.Create(new ActorId("dummy"), typeof(IMyActor), "MyActor");

Clients making the calls usually dont have service implementation, they only have the interface to know the contract.

**Comment by jpiquot** [comment]
I have for example command request handler actors, that I need to be called thru a command handler factory.

```
   public class DaprActorHandlerFactory : IAmAHandlerFactoryAsync
    {
        private readonly IActorProxy _actorProxy;
        private readonly int _maxHandlers;
        private readonly Random _random;

        public DaprActorHandlerFactory(IActorProxy actorProxy, int maxHandlers = 100)
        {
            _random = new Random();
            _actorProxy = actorProxy;
            _maxHandlers = maxHandlers;
            if (maxHandlers < 1)
            {
                throw new ArgumentOutOfRangeException(string.Format(CultureInfo.CurrentCulture, Properties.Resources.MinimimValueForArgument, 1, nameof(maxHandlers)));
            }
        }

        public IHandleRequestsAsync Create(Type handlerType)
        {
            if (handlerType == null)
            {
                throw new ArgumentNullException(nameof(handlerType));
            }
            // TODO: Change create signature
            return (IHandleRequestsAsync)_actorProxy.Create(new ActorId(_random.Next(1, _maxHandlers).ToString(CultureInfo.InvariantCulture)), handlerType, handlerType.Name.Substring(1));
        }

        public void Release(IHandleRequestsAsync handler)
        {
        }
    }

```
For tests : when Actor A calls Actor B. If you use the IActorProxy passed in the constructor to call Actor B instead of the static ActorProxy to make the call, its easier to Mock for tests.

**Comment by amanbha** [comment]
@jpiquot Thanks for sharing the sample. what happens after that, how is that type used inside the proxy?

**Comment by jpiquot** [comment]
Exactly in the same way as the actual generic method :

**Existing generic method :**
```
   public static TActorInterface Create<TActorInterface>(ActorId actorId, string actorType)
            where TActorInterface : IActor
        {
            return DefaultProxyFactory.CreateActorProxy<TActorInterface>(actorId, actorType);
        }

```
**Add new type parameter method:**
```
   public static object Create(ActorId actorId, Type actorInterfaceType, string actorType)
            where TActorInterface : IActor
        {
            return DefaultProxyFactory.CreateActorProxy(actorId, actorInterfaceType, actorType);
        }

```
**The internal ActorProxyFactory already has a CreateActorProxy with the good parameters :** 
```
        internal object CreateActorProxy(ActorId actorId, Type actorInterfaceType, string actorType)
        {
            var remotingClient = new ActorRemotingClient(this.daprInteractor);
            var proxyGenerator = ActorCodeBuilder.GetOrCreateProxyGenerator(actorInterfaceType);
            var actorProxy = proxyGenerator.CreateActorProxy();
            actorProxy.Initialize(remotingClient, actorId, actorType);

            return actorProxy;
        }

```

I would also add the Create methods the IActorProxy interface. This will enable mocked proxy interface injection in actors. It will enable to Test chained actor calls.

**Comment by amanbha** [comment]
@jpiquot Sure, makes sense. Would you like to contribute and submit a PR for it?

**Comment by jpiquot** [comment]
Ok, I will submit a PR.

**Comment by amanbha** [comment]
Fixed in PR https://github.com/dapr/dotnet-sdk/pull/285
