### ISSUE TITLE
Event not consumed in the ControllerSample when published with 'dapr publish'

### ISSUE THREAD

**Issue by ddobric** [dapr/dotnet-sdk#292]
## Expected Behavior
when publishing event to topic the WebApi in ControllerSample should consume it.

dapr publish -t deposit -p '{"id": "17", "deposit": 15 }'

## Actual Behavior

The WebAi in ControllerSample does not consume event.
However when sending the same event from DaprClient sample, all works as expected.

**Comment by amanbha** [comment]
@ddobric Are you running it on Windows?
Run the command as:
dapr publish -t deposit -p "{\"id\": \"17\", \"amount\": 15 }"

**Comment by ddobric** [comment]
Yes @amanbha, it was Wndows.

the command you provided must be executed in the command prompt (not in PowerShell):

`dapr publish -t deposit -p "{\"id\": \"17\", \"amount\": 15 }"`

In that case all works fine.
Thanks
