### ISSUE TITLE
Actor Invocation over HTTP does NOT invoke middleware

### ISSUE THREAD

**Issue by codeputer** [dapr/dotnet-sdk#294]
## Expected Behavior

DAPR allows the invocation of an Actor and it's methods over HTTP (default port 3500).  Actors are registered within a web application which listens on an assigned port (examples are 5000).  When Actors are invoked over HTTP, I don't understand why the middleware is not being invoked.

## Actual Behavior

CloudEvents and my own middleware is ignored.

## Steps to Reproduce the Problem

1) create breakpoint in middleware
2) create a post to an actor invoking a method
3) breakpoint in middle ware is never invoked 

Solution: Can we register middleware during the process of an http POST to the --app-port?

**Comment by amanbha** [comment]
@codeputer Could you please point me to the repo where you have this sample code.

**Comment by codeputer** [comment]
I it was in that pull request  - the only test that i didn't put in was a post to an actor as opposed to a post to an endpoint.... can you restore the PR? Or should I do it from my end?

**Comment by amanbha** [comment]
If you can just point me to your repo where you have the sample code with middleware registered with aspnetcore for actors. I can clone it and try it out.

**Comment by codeputer** [comment]
I believe this link is what you are looking  for?
https://github.com/dapr/dotnet-sdk/pull/289/files#r416924384 ... I also added the link in the comment to issue 294.

**Comment by codeputer** [comment]
Updated the Actor project to demo the behavior in what I believe is a bug... I'll add you to the repo so that you can download and test it.... Execute the ActorClient with the DemoActor running, and the ActorClient will fail.

**Comment by codeputer** [comment]
If I'm reading the code right, I'm pretty sure the Routes that are added in the UseActor() will NOT allow a CloudEvent to be routed directly to the Actor using the URL syntax of invoking the Actor from an HTTP Request.  I'm by no means an ASP.NET expert, I'm just trying to trace in the request to port 3500, and why that doesn't invoke the middle ware.

**Comment by amanbha** [comment]
@codeputer Thanks for more info, I will see how configuring the routes is affecting middlewares.

**Comment by codeputer** [comment]
Thanks @amanbha  - Ive dug into the code, and the UseActor puts in a lot of routes (DaprSetupFilters).. UserRouter (vs UseRouting) is involved. I'm not a SME in the ASP.NET Core incoming request pipeline - but both ports 3500/5000 are being listened to, and I think the UseActor router just needs a hook to register the middleware as the first bit in the pipeline.  The user scenario that I think I woudl use is that a CloudEvent has been assigned directly to an actor, and needs to be unwrapped before that can occur.

I also can't figure out how my POST to 3500 becomes a PUT to the Actor... knowing that would help my OCD. :)

**Comment by amanbha** [comment]
@codeputer  I will answer the POST/PUT part now :) . The POST call is into Dapr, and Dapr calls into Actor service as a PUT.

**Comment by codeputer** [comment]
LOL! I know that part!! I haven't found out how or when that occurs!  I want to find that part, as it would tell me how the POST gets into the application, and how we might put a hook there to run the middleware!  I'm busy for at least a week, as I'm transitioning off a contract (FU Corvid)

**Comment by codeputer** [comment]
Getting back to this... and I stuck on this question, but I think I understand most of the plumbing:
given that this code works (see below) - where does Dapr setup the configuration to listen on port 3500 (default Actor port), as well as 5000 (HTTP port).. I'm sure its via the DaprHttpInterceptor, and that is configured in the ActorRuntime, which is setup when an Actor is registered.... but the routes still have to be configured for a port I'm thinking..... or are routes open to all ports?

//test to show that middle ware is active posting to MapPOST end point
            var request = new HttpRequestMessage(HttpMethod.Post, "http://localhost:5000/AppPortEndPoint")
            {
                Content = new StringContent("", Encoding.UTF8)
            };
            request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/x-www-form-urlencoded");
            var response = await httpClient.SendAsync(request);
            response.EnsureSuccessStatusCode();

            //json payload direct to actor
            string JsonPayload = "{\"PropertyA\":\"ValueA\",\"PropertyB\":\"ValueB\"}";
            request = new HttpRequestMessage(HttpMethod.Post, "http://localhost:3500/v1.0/actors/DemoActor/123/method/SaveData")
            {
                Content = new StringContent(JsonPayload, Encoding.UTF8)
            };
            request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            response = await httpClient.SendAsync(request);
            response.EnsureSuccessStatusCode();

**Comment by codeputer** [comment]
So a request sent to 3500 somehow transferred to port 5000... which likely means the URL is matched to the route without regard to the port? If that is the case, why is it bypassing the middleware?

![ActorRouteon3500](https://user-images.githubusercontent.com/611541/81481736-62dbba80-91ef-11ea-89cf-79bc33bbb037.png)

**Comment by codeputer** [comment]
So, thinking about it, the side-car must receive the 3500 request, and then direct to the appropriate container that is hosting that actor????  Which means all traffic to the service is hosting the actor is on the port specified (default is 5000)...

So I'm back to why the middle ware is not being invoked, when the POST comes in.

I'm thinking the UserRouter (not UserRouting) is prior to UseRouting, and the middleware is not invoked, as the routing service finds a match before the middleware is invoked?

If all that is correct, it means that the middleware route has to be prior to the routes created when actor is registered... which is an after lunch quest i'm thinking

**Comment by codeputer** [comment]
Nearly there, but the response is encoded, and Twilio can decode (or wont).. the string I sent over very simply was "<XML>"

![ActorResponseEncoded](https://user-images.githubusercontent.com/611541/81505745-d55f9f80-92ae-11ea-8867-6d1745e47102.png)

**Comment by amanbha** [comment]
@codeputer The middleware is not getting executed because of the way middlewares are being added.  I will fix this for next release.  https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Actors.AspNetCore/DaprActorSetupFilter.cs#L30

**Comment by codeputer** [comment]
@amanbha The CloudEvents middleware is mainly for an incoming event, and the outgoing is only needed to indicate that the message was received (but not processed). Hence its not worried about the reply as much as I am for the Twilio reply - which carries instructions as to what is suppose to happen next.

If that HTTP POST is sent directly to an Actor (non-remoting), the incoming request will bypass the middleware as defined in the example, because (2 days of  learning on this one) the routes are registered earlier in the pipeline (Actor routes are registered from the UseActor which is invoked in Program, while the middle ware routes are registered in Startup.)

My scenario is to POST from twilio directly to the Actor, and the POST is in URLEncoded format (Why Twilio does this is a question I would spend money on... but I consider it to be a major flaw in their design).  Registering the route early before the Actors covers both Use Cases - post to a controller, or post to an Actor - will always invoke the middleware.  So a CloudEvent posted to an actor, as the code stands, will fail - because the middle ware will be bypassed).  

My current problem is that the response (as you have indicated) is an assumption that I'm returning JSON, and Twilio is anticipating XML.  Hence I used a String as a return on my method, which gets returned by the Actor as encoded JSON.  IMO, I think the reflection should detect there is non-class return, and if so, be simply transferred across as a string - and allow the returning endpoint determine if the reply is in the correct format).

In my code repo (forked from SDK.NET) I put in the code to create the registrations earlier, it needs to be cleaned up, but I found that aspect interesting, and depending on how that should be handled  should be updated in the documentation.  To be clear, that means if you are posting to an Actor, middle ware will not be invoked.  If this not acceptable, then I documented how I changed my middle ware to register early in my forked repo (which I think you could pull to see what I did).

My suggestion would be to allow me to attribute the method, and that attribute override the default serializor.  So fare I can't add the same logic to handle the response in the middle ware.  An example of how to do so, would help.

**Comment by amanbha** [comment]
The PR to fix middleware  chaining is merged which closed the issue, reopening it to address the questions by @codeputer
