### ISSUE TITLE
when my actor instance crash down，how can i transition actor status？ except frequently call statemanager

### ISSUE THREAD

**Issue by sd797994** [dapr/dotnet-sdk#306]
## Ask your question here
in my case i have some goodsserver pod (pods>=2) in my k8s cluster to provider goods api for customer call, i want to use dapr actor to hander goods stock deduction，like this:
```
    public class GoodsInfo
   {
       public int GoodsId { get; set; }
       ...
       public int Stock { get; set; }
   }
    public interface IGoodsService : IActor
    {
        Task<ApiResult> DeductStock(DeductStock input);
    }
    public class GoodsService : Actor, IGoodsService
    {
        Task<ApiResult> DeductStock(DeductStock input)
        {
             //in correct example there will call mssql or other persistent device to get goodsinfo
             var goods = EF.GoodsInfo.first(x=>x.GoodsId==input.id);
             if(goods.stock>=input.purchasevolume)
             {
                goods.stock -= input.purchasevolume;
                EF.savechange();//save in persistent device or 
               return ApiResult.getok();
             }
            else{
               return ApiResult.geterr('Insufficient inventory!');
            }
        }
    }
```
how should I design a business model ，as small as possible to call ef or dapr-statemanager to save state?  only when actor are recycled or application are crash down(k8s pod dispatch) the actor's state to save(i try to use method OnDeactivateAsync, but it does not work as expected)

**Comment by amanbha** [comment]
OnDeactivateAsync is not guaranteed to be called every time.
You can perform the savestate operations in a method or reminder call because outside of these calls, your state will not be modified.

**Comment by amanbha** [comment]
@sd797994 feel free to reactivate if you have more questions.
