### ISSUE TITLE
Custom type named Actor's RegisterReminderAsync and RegisterTimerAsync method calls failing

### ISSUE THREAD

**Issue by fduman** [dapr/dotnet-sdk#310]
## Expected Behavior

On demo project, calling RegisterReminderAsync and RegisterTimerAsync methods should run without throwing exception.

## Actual Behavior

When using custom actor type name attribute this calls throws exception as actor not found

## Steps to Reproduce the Problem

- Create an actor
- Apply custom type name attribute on actor
- Implement RegisterReminderAsync and RegisterTimerAsync
- Call RegisterReminderAsync and RegisterTimerAsync with correct parameters

I have a PR for this issue.

**Comment by amanbha** [comment]
@fduman Thanks for reporting and contributing, me and @LMWF will review the PR.
