### ISSUE TITLE
Actors not registering when aspcore run using IIS Express.

### ISSUE THREAD

**Issue by plaisted** [dapr/dotnet-sdk#316]
Win10/64
daprd v0.7.1
placement v0.7.1
netcoreapp3.1 / Dapr.Actors.AspNetCore 0.7.0-preview01

## Expected Behavior
* Start aspcore hosting actor in Visual Studio using default IIS Express launching.
* Start daprd sidecar pointing to aspcore site.
* Call daprd sidecar to invoke actor method.
* aspcore actor created and called.

## Actual Behavior
When daprd called, error is returned:
`{"errorCode":"ERR_ACTOR_INVOKE_METHOD","message":"error finding address for actor type DemoActor with id 123"}`

Switching from IIS Express to running directly on same port resolves the issue and call is successful.

## Steps to Reproduce the Problem

- Start placement.exe (no args)
- Change IIS Express port to 5000 in launch settings. Start aspcore site with DemoActor registered (example application), 
- Start daprd: `daprd -placement-address localhost:50005 -app-id test -app-port 5000 -metrics-port 9091 -log-level debug`
- Call daprd to run actor method: `curl http://localhost:3500/v1.0/actors/DemoActor/123/method/TestNoArgumentNoReturnType`
- Call fails (no errors in logs of any application, including on startup).
- Stop aspcore site.
- Stop daprd.
- Switch launch settings to project, ensure default http port 5000 used. Run site.
- Start daprd using same args.
- Call daprd with same URL
- Call succeeds, HTTP 200 response.

Note: calling http://localhost:5000/dapr/config using both hosting methods returns same response:
`{"entities":["DemoActor"]}`

I don't think many real hosting scenarios would use IIS / IIS Express but it's the default when creating a new aspcore.net project. Also no errors logged in any of the applications so confusing to troubleshoot cause.

**Comment by plaisted** [comment]
Dug in a little deeper, this is due to IIS Express handling binding different than just using Kestrel.

Using kestrel with the default application URL (`http://localhost:5000`) also allows connections from `http://127.0.0.1:5000`. Kestrel behind IIS Express does not, connections must be done using `localhost:5000`.

I'll keep this issue open to suggest the sample project launchSettings.json be updated to use IP instead of localhost to unsure the project works if launched by IIS Express.

**Comment by amanbha** [comment]
@plaisted Thanks for opening and adding the workaround. Would you like to do a PR for this?

**Comment by amanbha** [comment]
@plaisted Does adding comments in launchSettings.json for IIS good for this issue?

**Comment by plaisted** [comment]
Apologies for not responding. I am unable to PR due to not having an employer approved CLA (been working on that). I think a note in documentation about not using IIS Express (or needing to update launchSettings.json if you do) would probably be good. This would affect all of the aspcore Dapr setups (not just Actors) since the Dapr side car uses loopback IP instead of localhost.

**Comment by amanbha** [comment]
Thanks @plaisted we will update the docs (or launchsettings.json)

**Comment by amanbha** [comment]
@plaisted Created the PR for this https://github.com/dapr/dotnet-sdk/pull/355 Please take a look at it and let me know if you have any comments/suggestions.
