### ISSUE TITLE
GrpcService demo with Dapr

### ISSUE THREAD

**Issue by jjindrich** [dapr/dotnet-sdk#317]
Hi team, please can you help me how to implement simple gRpc server behind Dapr ? We can use it Greeting gRpc service (https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio#create-a-grpc-service). What I need is to understand how to modify server to be accessible from Dapr sidecar - how to publish endpoint. I don't want to publish REST api on server side (only gRpc). Next how can I use Dapr state store ?

**Comment by jjindrich** [comment]
I run grpc server with Dapr, but I don't know how to invoke method with grpc.
Server is running:
dapr run --app-id jjgrpcserver --app-port 5000 --protocol grpc --grpc-port 50000 dotnet .\jjgrpc-server.dll

I don't know how to call SayHello method in my grpc service

**Comment by amanbha** [comment]
@jjindrich For Dapr to invoke your service over gRPC, you will have to implement gRPC server as per this proto https://github.com/dapr/dapr/blob/release-0.7/dapr/proto/daprclient/v1/daprclient.proto#L24

**Comment by jjindrich** [comment]
Thank, you is there any sample how to implement it?

**Comment by jjindrich** [comment]
Shared this demo https://github.com/GennadiiSvichinskyi/test-grpc-dapr
