### ISSUE TITLE
how to use autofac in actorservice?

### ISSUE THREAD

**Issue by sd797994** [dapr/dotnet-sdk#321]
in asp.net core we can use ioc containers like autofac  to injection services，how can i use autofac or other ioc framework to  injection services in actorservice?
`public class MyActorService : Actor, IMyActorService`
`{`
    `//how to injection services to constructor??`
    `public MyActorService(ActorService actorService, ActorId actorId) : base(actorService, actorId)`
`}`

**Comment by codeputer** [comment]
Autofax is dependency injunction part of IOC, while AOP, as I understand it, is totally different.

I'm interested in the dependency injection.

Also, although we have an SDK proxy that feels like calling an Actor is a local library, under the covers are service and data contracts that are used in the serialization and messaging required to transport the request.  AOP, and it's introduction in the  build and compilation process is at (IMO) at odds with the reflection going on in the plumbing for Actors.

**Comment by amanbha** [comment]
please see following to inject any dependency into Actors
https://github.com/dapr/dotnet-sdk/issues/171

**Comment by sd797994** [comment]
> 请参阅以下内容，将任何依赖项注入Actor
> [＃171](https://github.com/dapr/dotnet-sdk/issues/171)
thanks, bro, it's works~
