### ISSUE TITLE
DaprClient.InvokeMethodAsync throwing an exception: Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: Connection refused")

### ISSUE THREAD

**Issue by simonrhart** [dapr/dotnet-sdk#323]
## Expected Behavior

I was expecting a worker .NET core 3.1 service to be able to call another Dapr service via the DaprClient class using the dapr app name.

## Actual Behavior

Attempting to invoke the following code:
`
            Dapr.Client.Http.HTTPExtension httpExtension = new Dapr.Client.Http.HTTPExtension()
            {
                Verb = HTTPVerb.Post
            };

            while (!stoppingToken.IsCancellationRequested)
            {
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);

                // construct the location dto
                LocationDto location = new LocationDto();
                location.Date = DateTime.Now;
                location.Lat = "71.72469";
                location.Long = "-103.07681";
                 
                try
                {
                    await _client.InvokeMethodAsync<LocationDto>("location-api", "api/v0.1/gpslocator/location", location, httpExtension);
                }
                catch(Exception ex)
                {
                    _logger.LogCritical(ex, "Unable to communicate with location-api");
                }
                await Task.Delay(1000, stoppingToken);
            }
`
Results in the following exception log:

`
   Unable to communicate with location-api
Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: Connection refused")
   at Dapr.Client.DaprClientGrpc.MakeGrpcCallHandleError[TResponse](Func`2 callFunc, CancellationToken cancellationToken)
   at Dapr.Client.DaprClientGrpc.MakeInvokeRequestAsync(String appId, String methodName, Any data, HTTPExtension httpExtension, CancellationToken cancellationToken)
   at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TRequest](String appId, String methodName, TRequest data, HTTPExtension httpExtension, CancellationToken cancellationToken)
   at AtomPro.Location.Worker.Worker.ExecuteAsync(CancellationToken stoppingToken) in /src/AtomPro.Location.Worker/Worker.cs:line 54
[40m[32minfo[39m[22m[49m: AtomPro.Location.Worker.Worker[0]
      Worker running at: 06/05/2020 14:07:45 +00:00
`

The service that I am calling works if calling it via HTTP directly via Dapr (port 3500) or directly into the service. It seems this is a .NET SDK problem

The service I am calling is also a .NET core 3.1 ASP.NET service and has a route that looks like this:

`   [Route("api/v0.1/[controller]")]
    [ApiController] 
    public class GpsLocatorController : ControllerBase
    {
    }
`
The operation in this controller looks like this:
`
       [HttpPost]
        [Route("location")]
        public async Task<IActionResult> PublishLocation(LocationDto location, [FromServices] DaprClient daprClient)
        {
        }
`

The same behaviour is observed when running in Kubernetes or running locally using the Dapr.exe process command line.

Thanks for your help.

**Comment by amanbha** [comment]
@simonrhart Could y ou share the commands you sued to run these apps on local machine?
Also please share the http call which you made?

cc @LMWF

**Comment by LMWF** [comment]
@simonrhart does this work on subsequent calls or does it fail forever?

```
      await _client.InvokeMethodAsync<LocationDto>("location-api", "api/v0.1/gpslocator/location", location, httpExtension);
```

**Comment by simonrhart** [comment]
> @simonrhart Could y ou share the commands you sued to run these apps on local machine?
> Also please share the http call which you made?
> 
> cc @LMWF
@amanbha 

Aman,

Hi, Sure, to run locally I used the following command for the Web API: 
dapr run --app-id location-api --app-port 5001 dotnet run

For the worker I issued this command: 
dapr run --app-id location-worker --app-port 5000 dotnet run

**Comment by simonrhart** [comment]
> @simonrhart does this work on subsequent calls or does it fail forever?
> 
> ```
>       await _client.InvokeMethodAsync<LocationDto>("location-api", "api/v0.1/gpslocator/location", location, httpExtension);
> ```
> 
> Also can you show the output of `dapr version` and the first few lines of output after your dapr run command?

@LMWF 

Leon, please see below the log output when running the API service locally:

`Starting Dapr with id location-api. HTTP Port: 52842. gRPC Port: 52843
[93;1m== DAPR == time="2020-06-08T11:04:45.8482188+01:00" level=info msg="starting Dapr Runtime -- version 0.7.1 -- commit 16838e8" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:45.8482188+01:00" level=info msg="log level set to: info" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:45.8482188+01:00" level=info msg="metrics server started on :52844/" app_id=location-api instance=sihart-zbook scope=dapr.metrics type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:45.8582181+01:00" level=info msg="loading default configuration" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:45.8582181+01:00" level=info msg="standalone mode configured" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:45.8582181+01:00" level=info msg="app id: location-api" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:45.8582181+01:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:45.8602204+01:00" level=info msg="found component statestore (state.redis)" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:45.8602204+01:00" level=info msg="found component messagebus (pubsub.redis)" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:45.8612218+01:00" level=info msg="application protocol: http. waiting on port 5001.  This will block until the app is listening on that port." app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
[0m
[94;1m== APP ==       Now listening on: http://localhost:5001
[0m
[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
[0m
[94;1m== APP ==       Application started. Press Ctrl+C to shut down.
[0m
[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
[0m
[94;1m== APP ==       Hosting environment: Development
[0m
[94;1m== APP == info: Microsoft.Hosting.Lifetime[0]
[0m
[94;1m== APP ==       Content root path: C:\repositories\atompro\src\AtomPro.Location.Api
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.3329888+01:00" level=info msg="application discovered on port 5001" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4426798+01:00" level=info msg="application configuration loaded" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4804512+01:00" level=info msg="app is subscribed to the following topics: []" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4804512+01:00" level=info msg="Initialized service discovery to standalone" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4804512+01:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=location-api instance=sihart-zbook scope=dapr.runtime.actor type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4804512+01:00" level=info msg="starting connection attempt to placement service at localhost:6050" app_id=location-api instance=sihart-zbook scope=dapr.runtime.actor type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4804512+01:00" level=info msg="enabled monitoring middleware." app_id=location-api instance=sihart-zbook scope=dapr.runtime.grpc.api type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4804512+01:00" level=info msg="API gRPC server is running on port 52843" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4804512+01:00" level=info msg="enabled monitoring middleware." app_id=location-api instance=sihart-zbook scope=dapr.runtime.grpc.internal type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4814536+01:00" level=info msg="internal gRPC server is running on port 52848" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4814536+01:00" level=info msg="enabled cors http middleware" app_id=location-api instance=sihart-zbook scope=dapr.runtime.http type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4814536+01:00" level=info msg="enabled proxy http middleware" app_id=location-api instance=sihart-zbook scope=dapr.runtime.http type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4814536+01:00" level=info msg="enabled tracing http middleware" app_id=location-api instance=sihart-zbook scope=dapr.runtime.http type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4814536+01:00" level=info msg="http server is running on port 52842" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4814536+01:00" level=info msg="local service entry announced" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4814536+01:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 10623.2355ms" app_id=location-api instance=sihart-zbook scope=dapr.runtime type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4864482+01:00" level=info msg="established connection to placement service at localhost:6050" app_id=location-api instance=sihart-zbook scope=dapr.runtime.actor type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4910154+01:00" level=info msg="placement order received: lock" app_id=location-api instance=sihart-zbook scope=dapr.runtime.actor type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4910154+01:00" level=info msg="placement order received: update" app_id=location-api instance=sihart-zbook scope=dapr.runtime.actor type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4910154+01:00" level=info msg="actors: placement tables updated" app_id=location-api instance=sihart-zbook scope=dapr.runtime.actor type=log ver=0.7.1
[0m
[93;1m== DAPR == time="2020-06-08T11:04:56.4910154+01:00" level=info msg="placement order received: unlock" app_id=location-api instance=sihart-zbook scope=dapr.runtime.actor type=log ver=0.7.1
[0m
Updating metadata for app command: dotnet run
You're up and running! Both Dapr and your app logs will appear here.`

**Comment by simonrhart** [comment]
Hi chaps,

I have figured out the problem, although not sure why this is. If I start the worker process without an app-port specified in the cli it works! I don't actually need a port exposed because this process is a worker, it calls the web api via the SDK using the device discovery features.

I have not tried this in Kubernetes yet, so assume if removing the app port annotation from the yaml file it will also work. Suggest though this seems like it's a bug or should provide some meaningful exception.

Thanks
Simon

**Comment by amanbha** [comment]
Yes, @simonrhart Dapr waits for the app to respond on the port if the port is specified. ITs pringted in the logs:
```
DAPR == time="2020-06-08T11:04:45.8612218+01:00" level=info msg="application protocol: http. waiting on port 5001. This will block until the app is listening on that port."
```

From the SDK perspective, it can't figure this out, to it the call is failing, the reason could be anything.

**Comment by amanbha** [comment]
Closing this for now, please reopen if more help is needed.

**Comment by LMWF** [comment]
We have an issue open to make that app port log more actionable buy the user.

**Comment by simonrhart** [comment]
Thanks guys
