### ISSUE TITLE
How to call HTTP get request from dapr

### ISSUE THREAD

**Issue by pankajarav** [dapr/dotnet-sdk#344]
Hi, I want to call HTTP get request from **.net core console application** and if request will get fail then it should retry it.I did not find any example regarding this.Please help me.

**Comment by amanbha** [comment]
@pankajarav For service invocation, the example is shown here https://github.com/dapr/dotnet-sdk/blob/master/samples/Client/DaprClient/Program.cs#L111
Retries would be custom to your app logic, handle the exception and retry from it.

**Comment by amanbha** [comment]
Please fell free to reopen if you have further questions.
