### ISSUE TITLE
Secret Store configuration provider doesn't/cannot work

### ISSUE THREAD

**Issue by amolenk** [dapr/dotnet-sdk#345]
## Expected Behavior

I can use the Dapr secret configuration provider to get secrets from Azure Key Vault.

## Actual Behavior

The configuration provider tries to load the secrets (configured using the the DaprSecretDescriptors) as soon as the application starts. To do this it makes a call to the Dapr sidecar. However, the sidecar does not accept any incoming connections yet because it's still blocking until the app starts listening. So now we're basically in a deadlock situation with the sidecar waiting for the app, and the app cannot continue because the sidecar doesn't respond:

```
== DAPR == time="2020-07-21T16:29:12.794225+02:00" level=info msg="application protocol: http. waiting on port 5000.  This will block until the app is listening on that port." app_id=routing instance=MacBook-Pro.localdomain scope=dapr.runtime type=log ver=0.9.0

== APP == Unhandled exception. Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: Connection refused")

== APP ==    at Dapr.Client.DaprClientGrpc.MakeGrpcCallHandleError[TResponse](Func`2 callFunc, CancellationToken cancellationToken) in /Users/sander/Git/dapr-dotnet-sdk/src/Dapr.Client/DaprClientGrpc.cs:line 562

== APP ==    at Dapr.Client.DaprClientGrpc.GetSecretAsync(String storeName, String key, Dictionary`2 metadata, CancellationToken cancellationToken) in /Users/sander/Git/dapr-dotnet-sdk/src/Dapr.Client/DaprClientGrpc.cs:line 536

== APP ==    at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.LoadAsync()

== APP ==    at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.Load()

== APP ==    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)

== APP ==    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()

== APP ==    at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()

== APP ==    at Microsoft.Extensions.Hosting.HostBuilder.Build()

== APP ==    at ControllerSample.Program.Main(String[] args) in /Users/sander/Git/dapr-dotnet-sdk/samples/AspNetCore/ControllerSample/Program.cs:line 25
```

## Steps to Reproduce the Problem

I've taken the Dapr AspNetCore Controller sample and added an Azure Key Vault secret store to it. I then added a reference to the (0.9.0-preview01 version) of the `Dapr.Extensions.Configuration` NuGet package.

In `Program.cs` I add the Dapr configuration provider:

```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((ctx, builder) =>
        {
            builder.AddDaprSecretStore("azurekeyvault",
                new DaprSecretDescriptor[]
                {
                    new DaprSecretDescriptor("Foo")
                },
                new DaprClientBuilder().Build());
        })
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
``` 

I run the app in standalone mode:

```
dapr run --app-id routing --app-port 5000 --components-path ./components dotnet run
```

## Conclusion

I don't see how this could work as it is designed now, unless I'm really missing something 😉

Wouldn't it be better to fetch the secrets just-in-time (like `Microsoft.Extensions.Configuration.AzureKeyVault` does) instead of directly on startup? That would also have the added benefit of getting the latest version of the secret.

**Comment by amanbha** [comment]
@amolenk Then configuration provider will not work until app starts listening on the specified port as Dapr runtime waits on a response from app. This pull request shows how to workaround this https://github.com/dapr/dotnet-sdk/pull/262/files

@LMWF We should disable building and publishing the configuration provider until it can work and dapr can serve secrets without waiting for app to listen on port.

**Comment by cmendible** [comment]
The extension was meant to be used as any other configuration provider for .NET, but today the only way to make it work is to use a workaround such as the one I added in the PR mentioned by @amanbha.

**Comment by amanbha** [comment]
> The extension was meant to be used as any other configuration provider for .NET, but today the only way to make it work is to use a workaround such as the one I added in the PR mentioned by @amanbha.

Thanks @cmendible Could you please share the other scenarios, outside of aspnetcore, because currently users are running into the issue https://github.com/dapr/dotnet-sdk/issues/345. So if there are no other scenarios for this extension then I would prefer to stop shipping it until it can be used without a workaround.

**Comment by amanbha** [comment]
@amolnek since this extension doesn't work as of now unless Dapr runtime supports calling apis unless the app has responded on app port.
