### ISSUE TITLE
Subscribe callback should be able to return response object

### ISSUE THREAD

**Issue by LMWF** [dapr/dotnet-sdk#346]
This is to track corresponding changes in the .net repro for the following:
https://github.com/dapr/dapr/issues/1757

**Comment by amanbha** [comment]
@LMWF This doesn;t need a change in the sdk as .net sdk doesn't provide a callback. Pulling in the new protos from the dapr runtime would be enough for this. Protos would be pulled in multi-pubusb work as well.
