### ISSUE TITLE
deactivation error under high RPS

### ISSUE THREAD

**Issue by youngbupark** [dapr/dotnet-sdk#350]
Moving from https://gitter.im/Dapr/actors?at=5f1af57349bae20601180ea7

We configured our C# Actor with a 10 minutes ActorIdleTimeout, as this actor population is always increasing (new orders coming in) and we do not need them in memory after a while.
```
actorRuntime.ConfigureActorSettings(a =>
                    {
                        a.ActorIdleTimeout = TimeSpan.FromMinutes(10);
                        a.ActorScanInterval = TimeSpan.FromSeconds(60);
                        a.DrainOngoingCallTimeout = TimeSpan.FromSeconds(35);
                        a.DrainRebalancedActors = true;
                    });
```
In stress conditions on a AKS cluster, we see these errors coming from the pods of the aforementioned actor.
```
time="2020-07-24T14:31:47.409449414Z" level=warning msg="failed to deactivate actor OrderActor||b40ac0ca-005d-4f29-a46d-cb31dff6b2f5: error from actor service: {\"error\": \"client error: dialing to the given TCP address timed out\"}" app_id=orderactor instance=orderactor-779b96d7fb-6qw29 scope=dapr.runtime.actor type=log ver=edge
```
Looking at # errors VS new actors introduced per second, It seems that most of the actors meant to be deactivated translate 1:1 to this error being logged.
Any hint on this?

**Comment by youngbupark** [comment]
@dabedin let's discuss the issue here.

**Comment by youngbupark** [comment]
@dabedin This issue comes when dapr sidecar fails to call deactivation callback endpoint of your actorservice. it means your actor service is not available to respond to deactivation request under high load. Can you please share logs of actorservice side? please set your asp.net actor service to the lowest log level.

**Comment by vinayada1** [comment]
@dabedin - Is this still an issue?

**Comment by vinayada1** [comment]
Closing due to no action.
