### ISSUE TITLE
Provide stable NuGet package releases

### ISSUE THREAD

**Issue by tomkerkhove** [dapr/dotnet-sdk#351]
## Describe the proposal
Provide stable NuGet package releases instead of only preview packages on NuGet.org.

**Comment by amanbha** [comment]
@tomkerkhove Dapr project is currently in alpha release. We will provide stable nuget packages once Dapr reaches a stable v1.0 version.

**Comment by tomkerkhove** [comment]
From a user perspective it's very odd that the runtime has stable releases but the SDK only has prereleases but one can only suggest.

**Comment by amanbha** [comment]
> From a user perspective it's very odd that the runtime has stable releases but the SDK only has prereleases but one can only suggest.

@tomkerkhove Dapr runtime doesn't have stable releases yet. It hasn't released a v1.0 version yet. Runtime is still in alpha stage.

**Comment by tomkerkhove** [comment]
I was more referring to that NuGet packages have the -preview suffix and the runtime just has stable releases in terms of SemVer but it's fine.
