### ISSUE TITLE
What's the best approach to debug actors in Visual Studio

### ISSUE THREAD

**Issue by tomkerkhove** [dapr/dotnet-sdk#353]
This might be a stupid question but if we need to run our apps with following command (based on [sample](https://github.com/dapr/dotnet-sdk/blob/master/docs/get-started-dapr-actor.md#run-actor)):
```shell
$ dapr run --app-id myapp --app-port 3000 dotnet MyActorService.dll
```

How do we debug the code in Visual Studio? Clearly I'm missing something.

**Comment by codeputer** [comment]
get it running first dapr..... then do this in visual studio...

Debug-Attach To Process  and look for the appname.dll  - so in your case - myapp.dll

So easy, not documented, and wow saves me SO much time.... do this once, and re-attach can be a short-cut - Ctrl-Alt-P I think

**Comment by amanbha** [comment]
Thanks @codeputer  for sharing, @tomkerkhove you can attach debugger to the process when launching with cli.
Please feel free to reopen if you have more questions.
There is a preview VS code extension for Dapr, it would evolve overtime, please feel free to open issues, feature requests for extension directly in https://github.com/microsoft/vscode-dapr#:~:text=Join%20GitHub%20today%20%20%20%20Name%20,3%20months%20ago%20%2022%20more%20rows%20

**Comment by tomkerkhove** [comment]
Any plans to provide integration for this in Visual Studio?

**Comment by tomkerkhove** [comment]
> get it running first dapr..... then do this in visual studio...
> 
> Debug-Attach To Process and look for the appname.dll - so in your case - myapp.dll
> 
> So easy, not documented, and wow saves me SO much time.... do this once, and re-attach can be a short-cut - Ctrl-Alt-P I think

This doesn't work for me 🤔 I presume you've used `dapr run` in a command line and attached to that or?

**Comment by amanbha** [comment]
> Any plans to provide integration for this in Visual Studio?

At this time, VS Code extension will be the priority to provide experience across Linux, Mac and windows.

**Comment by tomkerkhove** [comment]
Ok, thanks!

Using Docker compose and VS Container Tools fixed this for me.
