### ISSUE TITLE
Errors using the Actor Sample

### ISSUE THREAD

**Issue by samcov** [dapr/dotnet-sdk#391]
## Expected Behavior

For it to just work

## Actual Behavior

1. First it complained of not being able to connect to the service. I started it up with this command(started fine)
    dapr run --app-id myapp --app-port 5000 --dapr-http-port 5030 dotnet run

2. After debugging, I discovered that the Client defaulted to port 3500 and had no clue about port 5030, and was looking at an environment variable.
**Side Note**: Is there a better way to inform the client about which port to listen on?

3. So I set the environment variable in the Client as shown
    Environment.SetEnvironmentVariable("DAPR_HTTP_PORT", "5030");

4. Now I get the error: **"error finding address for actor type DemoActor with id abc"**, however, 
    a. It's registered as: actorRuntime.RegisterActor<DemoActor>();, no id of course
    b. It's created as: var actorId = new ActorId("abc");
    c. With proxy code: var proxy = ActorProxy.Create<IDemoActor>(actorId, "DemoActor");

5. This is basically the demo code run with the only change being setting the environment variable

**Note**: I'm running the slim environment without Docker

## Steps to Reproduce the Problem

See above

**Comment by amanbha** [comment]
@samcov Placement service is required to run actors, Slim environment doesn't setup placement service or a state store. If you are just getting started with Dapr, I would suggest to use dapr init without slim option, so that your environment gets setup correctly.
I am closing this, please feel free to reopen if you need more info.

**Comment by samcov** [comment]
If that's the case, then what is possible with the slim environment?

Which samples work and which don't, maybe I missed this in the readme.

**Comment by amanbha** [comment]
Please see following docs about slim and setting env without docker:

https://github.com/dapr/docs/tree/master/howto/self-hosted-no-docker#self-hosted-mode-without-containers

**Comment by samcov** [comment]
Thanks.
