### ISSUE TITLE
Widen the pit of success with AddDapr/AddDaprClient

### ISSUE THREAD

**Issue by amolenk** [dapr/dotnet-sdk#393]
## Describe the proposal

This was triggered while talking to @edwinvw about #390.
The whole `AddDapr`, `AddDaprClient` thing is a bit complicated for ASP.NET devs wanting to use Dapr service invocation.

ASP.NET Web APIs by default use camel case JSON for the responses. The S.T.JsonSerializer used by DaprClient uses Pascal casing and is case sensitive by default.

So, in order to succesfully implement a scenario with multiple .NET microservices where service A calls service B using Dapr service invocation, the developer needs to specify the correct JsonSerializerOptions in service A. For example:

```
services.AddDaprClient(builder => builder.UseJsonSerializationOptions(new JsonSerializerOptions
{
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
}));

services.Controllers().AddDapr();
```

If the `AddDaprClient` call is omitted, the service invocation itself will still succeed (because `services.Controllers.AddDapr()` also registers the `DaprClient`, but deserialization will fail (without any errors logged) because of the case sensitivity. I think this is confusing and hard to debug for developers.

Some ways to improve this:
- Use other default options for the JsonSerializer (`PropertyNameCaseInsensitive = true`)
- Or; allow the user to configure the DaprClient in the AddDapr() call.

**Comment by amanbha** [comment]
@amolenk Thanks for reporting this confusing behavior. I believe both the suggested ways to improve can be implemented. Would you like to contribute a PR for it?

**Comment by EdwinVW** [comment]
We can definitely create a PR. Should we also change the related _MarkerService_ behavior as stated in issue #390 (or do you want to look at this as a separate issue)?

**Comment by amanbha** [comment]
Thanks @EdwinVW lets create separate PRs addressing these 2 issues.

**Comment by EdwinVW** [comment]
PR is created (#394 ).
