### ISSUE TITLE
Support custom HTTP headers in DaprClient

### ISSUE THREAD

**Issue by amolenk** [dapr/dotnet-sdk#396]
## Describe the proposal
I've got a scenario where Service A invokes a method on Service B and Service B requires an `Authorization` HTTP header to be sent. Example:

``` csharp
await _daprClient.InvokeMethodAsync<BasketData>(
    "serviceB",
    $"api/v1/basket/{id}",
    new HTTPExtension { Verb = HTTPVerb.Get });
```

There's currently no way to pass the header to the `DaprClient`. Ideally, I'd want to be able to do something like this:

``` csharp
Dictionary<string, string> headers = new Dictionary<string, string>
{
    ["Authentication"] = "Bearer ..."
};

await _daprClient.InvokeMethodAsync<BasketData>(
    "serviceB",
    $"api/v1/basket/{id}",
    new HTTPExtension { Verb = HTTPVerb.Get, Headers = headers });
```

**Comment by amolenk** [comment]
I've looked a bit further into this and it should not be hard to implement. We just need to pass any header information as gRPC metadata to the sidecar. I'll try and create a PR.

**Comment by philliphoff** [comment]
Somewhat related, could there also be a way of extracting HTTP headers sent by an application with the response?  For example, if the response was an opaque set of bytes, the `Content-Type` response header might be needed in order to differentiate between multiple types of data.  Something of this sort:

```csharp

class HttpResponseExtension
{
   IDictionary<string, string> Headers { get; }
}

class MethodResponse<TResponse>
{
    TResponse Content { get; }

    HttpResponseExtension Metadata { get; }
}

class DaprClient
{
    abstract Task<MethodResponse<TResponse>> InvokeMethodWithResponseAsync<TRequest, TResponse>(string appId, string methodName, HTTPExtension requestMetadata, CancellationToken);
}

```

**Comment by amolenk** [comment]
@philliphoff The service that's being called may be an HTTP service, but it could also be a gRPC service. So I'd do it slightly different:

```
class MethodResponse<TResponse>
{
    TResponse Content { get; }
}

class HttpResponse<TResponse> : MethodResponse<TResponse>
{
    IDictionary<string, string> Headers { get; }
}

class DaprClient
{
    abstract Task<MethodResponse<TResponse>> InvokeMethodAsync<TRequest, TResponse>(string appId, string methodName, HTTPExtension requestMetadata, CancellationToken);
}
```

Alternatively, at that point it may even be better to make separate invoke methods for Http and gRPC, like `InvokeHttpMethod` and `InvokeGrpcMethod`. The abstraction is already a bit leaky due to the need for the `HttpExtension` object.

May I suggest opening a new issue for response headers? I'd like to keep this issue/PR focused on the request side.

**Comment by philliphoff** [comment]
> @amolenk May I suggest opening a new issue for response headers? I'd like to keep this issue/PR focused on the request side.

Opened #400.

**Comment by amolenk** [comment]
@vinayada1 Can you review? This is ready to be merged.
