### ISSUE TITLE
Visual Studio development of Dapr apps

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/dotnet-sdk#401]
Currently only the development of Dapr applications in VS Code and IntelliJ is documented:
https://github.com/dapr/docs/tree/master/howto#developer-tooling

There should also be something similiar for Visual Studio 2019:
* Enable debugging / "F5 experience" of Dapr applications in Visual Studio
* Ensure that this include a story of multiple Dapr applications inside one solution and starting multiple of them
* Ensure that the [Yeoman Dapr generator](https://github.com/dapr/generator-dapr) for C# Dapr applications is generating all things needed for efficient development in Visual Studio

If Visual Studio does not support a productive development, we need an extension approach, like we have for VSCode: https://github.com/microsoft/vscode-dapr

[Tye with Dapr integration](https://github.com/dotnet/tye/blob/master/docs/recipes/dapr.md) is going into this direction - but it is only experimental.

**Comment by ddobric** [comment]
When looking into Tye, have to say that Tye extrimely simplifies the deployment. For this reason, I propose similar concept in dapr.
For example:

~~~
dapr deploy <path>
~~~

This would be a great simplification.

**Comment by vinayada1** [comment]
Thanks. Could you please send your feedback on https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019?

**Comment by Fabian-Schmidt** [comment]
Hi, I have played around with Visual Studio and Dapr applications.
I found two options to achive a F5 debug experience in Visual Studio.

# Dotnet app starting Dapr

Modify your .NET app to start Dapr process

Need Nuget package `System.CommandLine`.

```C#
public static void Main(string[] args) {
var rootCommand = new RootCommand
{
    new Option<string[]>("--DAPR_CMD")
};
rootCommand.Handler = CommandHandler.Create((string[] DAPR_CMD) =>
{
    if (DAPR_CMD != null && DAPR_CMD.Length > 0)
    {
        var cmd = DAPR_CMD[0];
        var cmdArgs = DAPR_CMD[1..];
        if (!string.IsNullOrWhiteSpace(cmd))
        {
            DaprProcess = new System.Diagnostics.Process
            {
                StartInfo =
                {
                    FileName = cmd,
                    Arguments = string.Join(' ', cmdArgs),
                }
            };
            DaprProcess.Start();
        }
    }
});
rootCommand.Invoke(args);
```

The necessary `launchSettings.json`

```JSON
"Dapr": {
  "commandName": "Project",
  "commandLineArgs": "--DAPR_CMD dapr run --app-id mydaprapp --components-path ./components/ --app-port 5000 --dapr-http-port 5005 --dapr-grpc-port 5006",
  "launchUrl": "swagger",
  "environmentVariables": {
    "DAPR_HTTP_PORT": "5005",
    "DAPR_GRPC_PORT": "5006",
    "ASPNETCORE_ENVIRONMENT": "Development"
  },
  "dotnetRunMessages": "true",
  "applicationUrl": "https://localhost:5001;http://localhost:5000"
}
```

# Use VS extension

Need [PowerShell 7 / Core](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows) installed (Example: `dotnet tool install --global PowerShell`)

Need the Visual Studio extension [Microsoft Child Process Debugging Power Tool](https://marketplace.visualstudio.com/items?itemName=vsdbgplat.MicrosoftChildProcessDebuggingPowerTool) installed.

Activate `Child Process Debugging Settings` and configure:

| Enabled | Process name              | Action          | Debugger Type                   |
| ------- | ------------------------- | --------------- | ------------------------------- |
| Yes     | `<All other processeses>` | Do not debug    | `<Inherit from parent process>` |
| Yes     | dapr.exe                  | Attach debugger | Native                          |
| Yes     | dotnet.exe                | Attach debugger | Native                          |
| Yes     | myapp.exe                 | Attach debugger | Managed (.NET Core, .NET 5+)    |

The necessary `launchSettings.json`

```JSON
"Dapr-PWSH": {
  "commandName": "Executable",
  "executablePath": "pwsh",
  "commandLineArgs": "-Command \"dapr run --app-id mydaprapp --components-path ./components/ --app-port 5000 --dapr-http-port 5005 --dapr-grpc-port 5006 -- dotnet run --no-build\"",
  "workingDirectory": ".",
  "environmentVariables": {
    "ASPNETCORE_ENVIRONMENT": "Development"
  },
  "nativeDebugging": true
}
```

**Comment by wjkhappy14** [comment]
thks

**Comment by DanielHazlewood** [comment]
Could we include something in the documentation for this? So far only IntelliJ and VSCode is documented.

> Hi, I have played around with Visual Studio and Dapr applications. I found two options to achive a F5 debug experience in Visual Studio.
> 
> # Dotnet app starting Dapr
> Modify your .NET app to start Dapr process
> 
> Need Nuget package `System.CommandLine`.
> 
> ```cs
> public static void Main(string[] args) {
> var rootCommand = new RootCommand
> {
>     new Option<string[]>("--DAPR_CMD")
> };
> rootCommand.Handler = CommandHandler.Create((string[] DAPR_CMD) =>
> {
>     if (DAPR_CMD != null && DAPR_CMD.Length > 0)
>     {
>         var cmd = DAPR_CMD[0];
>         var cmdArgs = DAPR_CMD[1..];
>         if (!string.IsNullOrWhiteSpace(cmd))
>         {
>             DaprProcess = new System.Diagnostics.Process
>             {
>                 StartInfo =
>                 {
>                     FileName = cmd,
>                     Arguments = string.Join(' ', cmdArgs),
>                 }
>             };
>             DaprProcess.Start();
>         }
>     }
> });
> rootCommand.Invoke(args);
> ```
> 
> The necessary `launchSettings.json`
> 
> ```json
> "Dapr": {
>   "commandName": "Project",
>   "commandLineArgs": "--DAPR_CMD dapr run --app-id mydaprapp --components-path ./components/ --app-port 5000 --dapr-http-port 5005 --dapr-grpc-port 5006",
>   "launchUrl": "swagger",
>   "environmentVariables": {
>     "DAPR_HTTP_PORT": "5005",
>     "DAPR_GRPC_PORT": "5006",
>     "ASPNETCORE_ENVIRONMENT": "Development"
>   },
>   "dotnetRunMessages": "true",
>   "applicationUrl": "https://localhost:5001;http://localhost:5000"
> }
> ```
> 
> # Use VS extension
> Need [PowerShell 7 / Core](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows) installed (Example: `dotnet tool install --global PowerShell`)
> 
> Need the Visual Studio extension [Microsoft Child Process Debugging Power Tool](https://marketplace.visualstudio.com/items?itemName=vsdbgplat.MicrosoftChildProcessDebuggingPowerTool) installed.
> 
> Activate `Child Process Debugging Settings` and configure:
> 
> Enabled	Process name	Action	Debugger Type
> Yes	`<All other processeses>`	Do not debug	`<Inherit from parent process>`
> Yes	dapr.exe	Attach debugger	Native
> Yes	dotnet.exe	Attach debugger	Native
> Yes	myapp.exe	Attach debugger	Managed (.NET Core, .NET 5+)
> The necessary `launchSettings.json`
> 
> ```json
> "Dapr-PWSH": {
>   "commandName": "Executable",
>   "executablePath": "pwsh",
>   "commandLineArgs": "-Command \"dapr run --app-id mydaprapp --components-path ./components/ --app-port 5000 --dapr-http-port 5005 --dapr-grpc-port 5006 -- dotnet run --no-build\"",
>   "workingDirectory": ".",
>   "environmentVariables": {
>     "ASPNETCORE_ENVIRONMENT": "Development"
>   },
>   "nativeDebugging": true
> }
> ```

**Comment by toresenneseth** [comment]
Just starting to explore Dapr, and came across [Dapr sidekick](https://github.com/man-group/dapr-sidekick-dotnet) which seems to make debugging in VS very easy. Might get me into trouble...don't know yet :)
