### ISSUE TITLE
STATE - Meta data in all Get operations ? 

### ISSUE THREAD

**Issue by perokvist** [dapr/dotnet-sdk#412]
Should these operations also support passing meta data ?
- GetStateAndETagAsync
- GetStateEntryAsync

Looking at the Cosmos state component, it seems that all calls need meta data if custom partition is used.

**Comment by perokvist** [comment]
This seems unchanged in 0.12 SDK
The documentation for Cosmos hints that meta/partitionKey should be used.

https://docs.dapr.io/operations/components/setup-state-store/supported-state-stores/setup-azure-cosmosdb/#partition-keys

**Comment by rynowak** [comment]
Thanks @perokvist
