### ISSUE TITLE
Actors HTTP handlers don't work with some common frontend server patterns

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#434]
## Expected Behavior

Actors HTTP handlers that are registered by the runtime can be called from the Dapr sidecar without much user knowledge.

## Actual Behavior

Certain use cases for routing don't work with the way Actors is wired up. This requires a little bit of explanation to make sense, but I assure you it does 😆 

It's important to understand how the actor runtime communicates with the Dapr sidecar - it injects HTTP handlers into the application in way that *tries* to be transparent to the developer. The tool that's used is `IStartupFilter`- specifically to inject an additional router into the HTTP pipeline (at the end).

Using Actors in ASP.NET Core is **as-if** the user wrote:

```C#
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                // application endpoints go here
            });

            // this is not a mistake, routing is configured again
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                  // actors goes here
            });
```

This is how Actors tries to be transparent to the user. This breaks when the user configures a *route of last resort* - for instance in a server-side blazor project.

This is a common routing setup when an application is hosting a client-side SPA - the application handles URLs that don't match a "server side" route by passing them off to the endpoint that serves the SPA. This allows the client-side framework to handle deep linking, and also use all of it's client-side goodies for "not found" pages.

```C#
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapSubscribeHandler();
                endpoints.MapHealthChecks("/healthz");
                endpoints.MapControllers();
                endpoints.MapBlazorHub();
                endpoints.MapFallbackToPage("/_Host"); // YOU SHALL NOT PASS
            });

            // this is not a mistake, routing is configured again
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                  // actors goes here
            });
```

There isn't really a good solution users can apply (without a bug fix) other than hosting Actors in a different application.

This **isn't** a problem with other Dapr functionality, because it's part of the users processing pipeline explicitly (see above, this sample was already using pub/sub).

## Steps to Reproduce the Problem

Create a server side blazor project (`dotnet new blazorserver`)

Add Actors

Your actors will fail to enregister with the runtime, because the application is returning HTML from `/dapr/config`

**Comment by vinayada1** [comment]
@rynowak - Could you please add a specific example of how the new way of registering actors would look like?

**Comment by rynowak** [comment]
## Proposal

Here's a repo with a sample of what it would look like: https://github.com/rynowak/actors-in-startup

This design mockup addresses a few problems:

- Actors use an outdated host to register functionality `IWebHostBuilder` has been superseded by `IHostBuilder`
- There's no unified way to set serializer settings for ALL Dapr functionality - there are 3-4 places to do it.
- There's no way to apply authentication, CORS, or other policies to the Actors endpoints because they are hidden from the user
- The issue described by this bug

There would be a change in the recommended pattern for registering the Dapr client - but we could leave the old one there to avoid a breaking change.

## Registering Actors

https://github.com/rynowak/actors-in-startup/blob/266a76a1ad3255d6d0b979f6eae6c0f6b8f37a63/Startup.cs#L25-L41

```C#
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();

            services.AddDapr(options =>
            {
                options.JsonSerializerOptions = new JsonSerializerOptions()
                {
                    // Configure custom JSON settings that apply to ALL dapr features.
                };
            })
            .AddActors(options =>
            {
                // Configure actor types here
                options.Actors.RegisterActor<MyActorType>();
            });
        }
```

Actors would be registered in the `ConfigureServices` method.

This is in general where frameworks are configured in ASP.NET Core. Users are more familiar with Startup.cs than with host builder and Program.cs

## Registering Actors Endpoints

https://github.com/rynowak/actors-in-startup/blob/266a76a1ad3255d6d0b979f6eae6c0f6b8f37a63/Startup.cs#L64-L73

```C#
            app.UseEndpoints(endpoints =>
            {
                // Register handlers for Actors
                endpoints.MapActorsHandler();


                // Register handler for subscribe endpoint (pub/sub)
                endpoints.MapSubscribeHandler();


                endpoints.MapRazorPages();
            });
```

The HTTP handlers for Actors would be wired up in the `UseEndpoints` section of `Configure` (where we register pub/sub today). In general we've found with ASP.NET Core that hiding HTTP functionality from users doesn't really work (hence this bug). It's better for everything that responds to HTTP to be explicit and configurable.

The major drawback is that register Actors requires two gestures. We can make `MapActorsHandler` throw an exception if the code in `ConfigureServices` is not present, but we can't do the reverse.  However this pattern (Add services + add something in the request pipeline) is very common.
