### ISSUE TITLE
Expose internal serialization/deserialization logic 

### ISSUE THREAD

**Issue by akkie** [dapr/dotnet-sdk#441]
Dapr allows to build gRPC enabled APIs by implementing the [AppCallback](https://github.com/dapr/dotnet-sdk/blob/e93357cb9de0e2e1bea7b8ac0f7a51e8215cfb09/src/Dapr.Client/Protos/dapr/proto/dapr/v1/appcallback.proto#L21) service and implementing the [OnInvoke](https://github.com/dapr/dotnet-sdk/blob/e93357cb9de0e2e1bea7b8ac0f7a51e8215cfb09/src/Dapr.Client/Protos/dapr/proto/dapr/v1/appcallback.proto#L23) method. These method accepts the [InvokeRequest](https://github.com/dapr/dotnet-sdk/blob/e93357cb9de0e2e1bea7b8ac0f7a51e8215cfb09/src/Dapr.Client/Protos/dapr/proto/common/v1/common.proto#L49) message and returns the [InvokeResponse](https://github.com/dapr/dotnet-sdk/blob/e93357cb9de0e2e1bea7b8ac0f7a51e8215cfb09/src/Dapr.Client/Protos/dapr/proto/common/v1/common.proto#L74) message. Both messages encode the data as `google.protobuf.Any`. If I will call such API with the DaprClient, Dapr internally uses  the [TypeConverters](https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Client/TypeConverters.cs#L15) class, which contains the serialization/deserialization logic and which is able to convert my type to `google.protobuf.Any`. Unfortunately, the [TypeConverters](https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Client/TypeConverters.cs#L15) can only be used internally and so the code must be copied to use the same serialization/deserialization logic.

An example can be found here: https://github.com/PlanBGmbH/dapr-vote/blob/master/notifications/Services/DaprService.cs 
It uses the same code as Dapr users internally: https://github.com/PlanBGmbH/dapr-vote/blob/master/proto/Converters.cs

For this I propose a serializer implementation that can also be used outside Dapr and which can be injected into services for reuse. I've opened a PR for that: https://github.com/dapr/dotnet-sdk/pull/440

**Comment by rynowak** [comment]
We're going to address this feedback by removing the `TypeConverters.ToAny` method and making sure all of the DaprClient APIs support raw bytes. 

We don't want to implement unique serialization behaviors inside Dapr, and make it explicit and clear what we're doing when we call serialization logic inside the SDK. This level of understanding is important for Dapr's goals, in particular to support interoperability with other languages.

**Comment by rynowak** [comment]
Renaming the title to track the action we're going to take.

**Comment by rynowak** [comment]
We're going to track the action with https://github.com/dapr/dotnet-sdk/issues/442 - which contains the actual proposal.
