### ISSUE TITLE
error finding address for actor type TestService with id abc

### ISSUE THREAD

**Issue by a641545621** [dapr/dotnet-sdk#454]
dapr --version
CLI version: 0.11.0 
Local test normal operation,But running on Kubernetes returns the following error

Kubernetes
{
"errorCode": "ERR_ACTOR_INVOKE_METHOD",
"message": "error finding address for actor type TestService with id abc"
}

redis.yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: tomoneycat
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: x.x.x.x:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
![1](https://user-images.githubusercontent.com/33652128/97850513-18b33c00-1d2f-11eb-8fca-f8625fd61b50.jpg)
![2](https://user-images.githubusercontent.com/33652128/97850523-1c46c300-1d2f-11eb-8281-11abb4a5b43a.jpg)

When I use daprclient, it can be saved
  var jsonOptions = new JsonSerializerOptions()
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                PropertyNameCaseInsensitive = true,
            };

            var client = new DaprClientBuilder()
                .UseJsonSerializationOptions(jsonOptions)
                .Build();
            var data = new MyData()
            {
                PropertyA = "PropertyA",
                PropertyB = "PropertyB"
            };

            await client.SaveStateAsync("statestore", "abc", data);

![3](https://user-images.githubusercontent.com/33652128/97850718-5fa13180-1d2f-11eb-91e3-6777a3557855.jpg)

**Comment by vinayada1** [comment]
Was this something that was working and stopped working or is this something you are trying for the first time?

**Comment by a641545621** [comment]
Yes, I deployed on Kubernetes for the first time

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '30'
  creationTimestamp: '2020-10-27T07:21:28Z'
  generation: 36
  labels:
    app: dapr-server
  name: dapr-server
  namespace: tomoneycat
  resourceVersion: '2105912393'
  selfLink: /apis/apps/v1/namespaces/tomoneycat/deployments/dapr-server
  uid: 66f9cb58-39b0-40b0-88bd-ed71bb1b5536
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dapr-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dapr.io/app-id: daprserver
        dapr.io/enabled: 'true'
      labels:
        app: dapr-server
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: 'http://+:80'
            - name: DOTNET_RUNNING_IN_CONTAINER
              value: 'true'
            - name: DAPR_HTTP_PORT
              value: '3500'
          image: 'registry-vpc.cn-shenzhen.aliyuncs.com/tomoneycat/dapr-server:laster'
          imagePullPolicy: Always
          name: dapr-server
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-11-02T07:18:20Z'
      lastUpdateTime: '2020-11-02T07:18:20Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-10-29T09:02:15Z'
      lastUpdateTime: '2020-11-02T07:28:33Z'
      message: ReplicaSet "dapr-server-55b74dfc56" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 36
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

Startup log
time="2020-11-02T07:28:25.662011598Z" level=info msg="starting Dapr Runtime -- version 0.11.3 -- commit a1a8e11" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.66207061Z" level=info msg="log level set to: info" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.662355592Z" level=info msg="metrics server started on :9090/" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.metrics type=log ver=0.11.3
time="2020-11-02T07:28:25.662582754Z" level=info msg="loading default configuration" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.662633116Z" level=info msg="kubernetes mode configured" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.662649055Z" level=info msg="app id: daprserver" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.662679261Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.663054417Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.security type=log ver=0.11.3
time="2020-11-02T07:28:25.663105423Z" level=info msg="authenticator created" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.676535746Z" level=info msg="Initialized name resolution to kubernetes" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.678763884Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.68673477Z" level=info msg="waiting for all outstanding components to be processed" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.689300339Z" level=info msg="component loaded. name: statestore, type: state.redis" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.689347607Z" level=info msg="all outstanding components processed" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.689467218Z" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.actor type=log ver=0.11.3
time="2020-11-02T07:28:25.689551985Z" level=info msg="enabled gRPC tracing middleware" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.grpc.api type=log ver=0.11.3
time="2020-11-02T07:28:25.689571888Z" level=info msg="enabled gRPC metrics middleware" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.grpc.api type=log ver=0.11.3
time="2020-11-02T07:28:25.689611188Z" level=info msg="API gRPC server is running on port 50001" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.689657634Z" level=info msg="enabled gRPC tracing middleware" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.grpc.internal type=log ver=0.11.3
time="2020-11-02T07:28:25.689669244Z" level=info msg="enabled gRPC metrics middleware" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.grpc.internal type=log ver=0.11.3
time="2020-11-02T07:28:25.689677696Z" level=info msg="sending workload csr request to sentry" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.grpc.internal type=log ver=0.11.3
time="2020-11-02T07:28:25.689629563Z" level=info msg="starting connection attempt to placement service: dapr-placement.dapr-system.svc.cluster.local:80" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.actor type=log ver=0.11.3
time="2020-11-02T07:28:25.696091482Z" level=info msg="established connection to placement service at dapr-placement.dapr-system.svc.cluster.local:80" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.actor type=log ver=0.11.3
time="2020-11-02T07:28:25.697074088Z" level=info msg="placement order received: lock" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.actor type=log ver=0.11.3
time="2020-11-02T07:28:25.697201006Z" level=info msg="placement order received: update" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.actor type=log ver=0.11.3
time="2020-11-02T07:28:25.697221681Z" level=info msg="placement tables updated, version: 0" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.actor type=log ver=0.11.3
time="2020-11-02T07:28:25.697268728Z" level=info msg="placement order received: unlock" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.actor type=log ver=0.11.3
time="2020-11-02T07:28:25.712722207Z" level=info msg="certificate signed successfully" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.grpc.internal type=log ver=0.11.3
time="2020-11-02T07:28:25.713003092Z" level=info msg="internal gRPC server is running on port 50002" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.713084493Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2020-11-03 07:43:25 +0000 UTC" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.grpc.internal type=log ver=0.11.3
time="2020-11-02T07:28:25.713316161Z" level=info msg="enabled cors http middleware" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.http type=log ver=0.11.3
time="2020-11-02T07:28:25.713352256Z" level=info msg="enabled metrics http middleware" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.http type=log ver=0.11.3
time="2020-11-02T07:28:25.713372827Z" level=info msg="enabled tracing http middleware" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.http type=log ver=0.11.3
time="2020-11-02T07:28:25.713404996Z" level=info msg="http server is running on port 3500" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-02T07:28:25.71343479Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 50.800942ms" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime type=log ver=0.11.3
time="2020-11-03T00:26:55.713325361Z" level=info msg="renewing certificate: requesting new cert and restarting gRPC server" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.grpc.internal type=log ver=0.11.3
time="2020-11-03T00:26:55.713468793Z" level=info msg="sending workload csr request to sentry" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.grpc.internal type=log ver=0.11.3
time="2020-11-03T00:26:55.736053719Z" level=info msg="certificate signed successfully" app_id=daprserver instance=dapr-server-55b74dfc56-dxwks scope=dapr.runtime.grpc.internal type=log ver=0.11.3

**Comment by a641545621** [comment]
dapr.io/app-id: daprserver
dapr.io/app-port: '80'
dapr.io/enabled: 'true'

Dapr.io/app-port: '80' is missing in the service deployment file yaml
