### ISSUE TITLE
Resurrect .NET configuration provider

### ISSUE THREAD

**Issue by amolenk** [dapr/dotnet-sdk#462]
When https://github.com/dapr/dapr/issues/1493 is fixed (which is nearing completion), the .NET configuration provider can be resurrected.

Even better, when dapr/components-contrib#310 is merged there'll be a new BulkGetSecret operation to get all the secrets in a single call. This will allow us to create a configuration provider that works similar to the KeyVault configuration provider (get all the secrets on start-up and refresh once in a while), and not require the user to specify secret keys when registering the provider.

I can submit a PR once the other fixes have been merged.

**Comment by cmendible** [comment]
Hi @amanbha can you asign this one to me?
