### ISSUE TITLE
Dapr Client InvokeMethodAsync should be able to return HttpResponseMessage

### ISSUE THREAD

**Issue by techgeek03** [dapr/dotnet-sdk#466]
## Describe the proposal
As of now `InvokeMethodAsync` trows exception for every HTTP Status code that is not success (2xx). However there are valid cases and scenarios where 400 (Bad Request) and 404 (Not Found) are expected result; for example when `ServiceA` calls `ServiceB` and `ServiceB` returns 400 with `Problem Details` explaining the reasons why the called failed. Maybe `ServiceA` wants to log the body etc. 

Having try/catch blocks in this case makes the code unreadable :) 

Short term `InvokeMethodAsync` can have an overload that returns `HttpResponseMessage`.
Long term consider returning opinionated response that can handle such cases. For example 404 can return null as response, 400 can return `ProblemDetails`

You can consider looking at `Refit` https://github.com/reactiveui/refit on the way it handles the responses.

**Comment by amolenk** [comment]
Have you looked at `InvokeMethodWithResponseAsync`? This will give you an `InvocationResponse<TResponse>` as the result which contains the HTTP status code as well as the response body.

**Comment by rynowak** [comment]
Thanks for the feedback, this is something we're considering. I'm close this issue but we're taking your feedback into account, and I agree it would be great to have a way to use the `System.Net.Http` APIs to interact with invoke.

We're tracking these ideas with #526
