### ISSUE TITLE
missing `SubscribeEvent` event

### ISSUE THREAD

**Issue by cilerler** [dapr/dotnet-sdk#469]
It looks like DaprClient doesn't have a SubscribeEvent event.

Please provide a sample code in [here](https://github.com/dapr/dotnet-sdk/blob/master/samples/Client/DaprClient/Program.cs) that demonstrates how to handle SubscribeEvent, including usage of ACK and NACK.

_By the way, it would be nice to use RabbitMQ as a queue backend instead of Redis to ensure the distinction of the services used._

**Comment by cilerler** [comment]
@vinayada1 This issue shouldn't be labeled as `documentation`. The client doesn't have `SubscribeEvent` in [here](https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Client/DaprClient.cs); it is a missing implementation, and I don't think it is intentional.

**Comment by vinayada1** [comment]
@cilerler - Are you looking for this?
https://github.com/dapr/dotnet-sdk/blob/47b59b4a97f73a386d74fa900effd06527735224/samples/AspNetCore/ControllerSample/Controllers/SampleController.cs#L67

or

https://github.com/dapr/dotnet-sdk/blob/47b59b4a97f73a386d74fa900effd06527735224/samples/AspNetCore/RoutingSample/Startup.cs#L86

**Comment by cilerler** [comment]
Thanks, @vinayada1. It is partially correct.  However, ACK and NACK practices do not exist in those scenarios.

Let me give you a real-life scenario; 
Let's say you publish a message from a client for pubsub scenario.
Subscriber node received it, and right at that point system crashed. The data you retrieved from pubsub will be gone forever.  

On RabbitMQ, you have to send ACKNOWLEDGE to delete the message from the server.  Otherwise, it will get back to the queue upon timeout. Without confirmations, there will be a data loss. More info can be found [here](https://www.rabbitmq.com/confirms.html)

Please let me know if you need further details.

**Comment by yaron2** [comment]
hi @cilerler, Dapr supports ACK NACK: https://v1-rc1.docs.dapr.io/reference/api/pubsub_api/#expected-http-response

In general, if your app receives the event and your app crashes before returning a response to Dapr, the event will not be ACKed and will get redelivered.

**Comment by cilerler** [comment]
@yaron2 Thanks, that is definitely what I was looking for.

> In general, if your app receives the event and your app crashes before returning a response to Dapr, the event will not be ACKed and will get redelivered.

The scenario you mentioned is one part of the story.  The second scenario that I was looking for is, instead of a crash, a failed response on purpose by the app to force re-queue, which falls to `RETRY` from the link you sent.  Thanks again.
