### ISSUE TITLE
ActorId is not serializable via Actor "remoting" invoke

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#477]
## Expected Behavior

`ActorReference` and `ActorId` can be serialized between different Actor implementations using "remoting". It's a common design pattern in actor systems for actors to exchange addresses with each other.

This issue is similar to #444 but with a different repo. We addressed the problem for the System.Text.Json serializer, but not for DataContract serializer.

## Actual Behavior

`ActorId` (and thus `ActorReference`) is not serializable via Actor "remoting" method invocation. 

If you attempt to send an `ActorReference` a "remoting" method invocation - the resulting `ActorId` has a null ID - despite the fact that `ActorId` doesn't allow null in its constructor. (Note, DCS bypasses constructors, which is why it has this result).

## Steps to Reproduce the Problem

Create an Actor system that uses "remoting". Send one of the Actors an `ActorReference` of the other. The resulting `ActorReference` has an `ActorId` with an id value of `null`.

## Release Note

RELEASE NOTE: **Fix** bug in actor serialization of `ActorId`.

**Comment by RadoslavGatev** [comment]
I just hit this bug on 0.12.0-preview01. The workaround, for now, is to pass a string instead of ActorId.
