### ISSUE TITLE
Update branding to reflect RC instead of preview

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#482]
## Expected Behavior

Since Dapr is in RC we should use RC branding in the package names. We should update the versions to say `1.0.0-rc-1` or similar.

## Actual Behavior

The newest packages are branded **0.12.0-preview01** 

https://www.nuget.org/packages/Dapr.Client/0.12.0-preview01

## Steps to Reproduce the Problem

Look at nuget.org 😆 

## Release Note

RELEASE NOTE: **Update** branding of .NET SDK libraries to reflect 1.0.0 RC

**Comment by vinayada1** [comment]
Discussed this offline and we have decided to name the sdk packages to align with the Dapr runtime release naming convention. However, we will not go back and change the existing packages already released.
