### ISSUE TITLE
ETag is empty

### ISSUE THREAD

**Issue by jjindrich** [dapr/dotnet-sdk#491]
Hi, I'm using State store (Azure Cosmos) in my application. When I call GetStateEntry, ETag is empty.
var state = await daprClient.GetStateEntryAsync<ArticleItem>(StoreName, vote.articleid)
state.ETag is empty

I need to avoid optimistic concurency. I need to get exception in case of another process updated entity.

I'm using this commands to save data:
var options = new StateOptions() {Concurrency = ConcurrencyMode.FirstWrite};
await state.SaveAsync(options);

RELEASE NOTE: rc1

**Comment by rynowak** [comment]
> I'm using this commands to save data:

```
var options = new StateOptions() {Concurrency = ConcurrencyMode.FirstWrite};
await state.SaveAsync(options);
```

I realize that you mentioned the SDK didn't include an ETag - however when you *do* have the ETag you'll want use `TrySaveAsync` to ensure that it is passed to the state store.

**Comment by jjindrich** [comment]
Thanks, I tried to use for saving data:
```
var options = new StateOptions() {Concurrency = ConcurrencyMode.FirstWrite};
await state.TrySaveAsync(options);
```
But the problem remain. Data are overriden.

**Comment by vinayada1** [comment]
You might want to use the GetStateAndETagAsync API to get the state entry and the etag and as @rynowak suggested, TrySaveStateAsync API to save.

**Comment by jjindrich** [comment]
@vinayada1 thanks for that. Can you help me how to use it ? state.TrySaveAsync doesn't exists
```
var state = await daprClient.GetStateAndETagAsync<MyItem>(StoreName, key);
...
var options = new StateOptions() {Concurrency = ConcurrencyMode.FirstWrite};
await state.TrySaveAsync(options);
```

**Comment by vinayada1** [comment]
@jjindrich: Please take a look at the sample in the linked PR. I will check this in for future reference

**Comment by jjindrich** [comment]
Excellent, many thanks !
