### ISSUE TITLE
Migration guide for 1.0.0-rc2

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#505]
## Summary

This issue lists breaking changes that are coming in the 1.0.0-rc2 release and explains how to migrate code to the new release.

## Issues:

- #171 - Dependency injection for Actors
- #414 - Dapr Actors should not use BinaryFormatter 
- #421 - HTTPExtension feedback 
- #422 - InvokeMethodAsync reports cancellation using RpcException instead of OperationCanceledOperation (sic)
- #435 - Timers invocation fails after app restarts 
- #461 - ActorTypeInfo constructor should be private 

### Exception handling for cancelled requests

All of the methods on `DaprClient` now properly report cancellation by throwing an `OperationCanceledException`. This behavior was incorrect before - but fixing it is still a breaking change. This is beneficial because in most cases you don't actually want to handle cancellation, you want to propagate it to the caller.

**Before**

```C#
try
{
    await daprClient.InvokeMethodAsync<Transaction>("bank", "validate", transaction, cancellationToken: ct);
}
catch (InvocationException) // would catch cancellation as well as other errors
{
}
```

```C#
try
{
    await daprClient.InvokeMethodAsync<Transaction>("bank", "validate", transaction, cancellationToken: ct);
}
catch (InvocationException) // no longer catches cancellation
{
}
catch (OperationCanceledException) // cancellation is handled separately
{
}
```

### HTTPExtension -> HttpInvocationOptions

The `HTTPExtension` and related features have been renamed to be more consistent with both .NET and other parts of the Dapr API. These APIs still have the same functionality but the types are different.

- Replace `HTTPExtension` with `HttpInvocationOptions`
- Replace `HTTPExtension.Verb` with `HttpInvocationOptions.Method`
- Replace `HTTPVerb` with `System.Net.Http.HttpMethod`

### Actor Registration

Actor registration has been streamlined along with the addition of support for the ASP.NET Core dependency injection abstraction. It no longer takes additional configuration to use dependency injection with actors.

By convention, Actors are registered in `CreateWebHostBuilder` in `Program.cs`. There are some small difference to the `UseActors` api. The options type now contains a collection of actors that support all of the normal collection operations in addition to `RegisterActor`.

Advanced configuration settings for the actor runtime are directly on the options type now instead of using a callback.

Actors get access to services from the dependency injection container. These can be registered in `Program.cs` using `ConfigureServices` (shown here) or in `Startup.cs` in `ConfigureServices`.

```C#
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .ConfigureServices(services => 
        {
            // Services registered here are available for Actor types to accept in their
            // constructor.
            services.AddSingleton<BankService>();
        })
        .UseActors(options =>
        {
            options.Actors.RegisterActor<DemoActor>();

            options.ActorIdleTimeout = TimeSpan.FromMinutes(10);
        });
```

### Actor Constructors

The constructors of Actor types have been simplified. Now that dependency injection is supported by default we wanted to reduce the number of parameters that were required, since you will likely be adding parameters. Since we were making changes here already this seemed like a good chance to do some cleanup.

- `ActorService` renamed to `ActorHost`. 
- `ActorId` is now passed as part of `ActorHost` rather than a separate parameter.

**Before**

```C#
public MyActor(ActorService service, ActorId id)
  : base(service, id)
{
}
```

**After**

```C#
public MyActor(ActorHost host) // Feel free to add your own parameters!
  : base(host)
{
}
```

### Timer registration

The `RegisterTimerAsync` method now accepts a `string` method name and `byte[]` state payload instead of a `Func<object, Task>` callback and `object` payload.

Unfortunately this isn't an improvement in usability, but the changes are necessary to properly implement the contract of actors without severe edge cases. The expectation of timers is that still fire in the event that the application has crashed in between registering the timer and its due time. This means that the timer must be able to store and retrieve all of the data needed to call the callback - which means that we cannot use delegates.

Here's an example of a use case that was broken:

```C#
var widget = new Widget();
var db = new WidgetDbContext();
return this.RegisterTimerAsync(
                "MyTimer", 
                async state => 
                { 
                     var w = (Widget)state;
                     db.Widgets.Add(w); 
                     await db.SaveChangesAsync(); 
                },
                widget, 
                TimeSpan.FromSeconds(5),
                TimeSpan.FromSeconds(5)); 
```

This example uses a C# lambda to close over state from the surrounding context. There's no way that we could guarantee this code has reproducible results in the event of an app crash. 

The changes are intended to signal to users what will work well. You need to pass a method name - so that we can lookup the method later and call it. You can pass state, but it has to be a `byte[]` (we recommend using `JsonSerializer.SerializeToUtf8Bytes()`).

Here's the same example but it's now resilient.

```C#
public async Task SaveWidgetLater()
{
    var widget = new Widget();
    return this.RegisterTimerAsync(
                nameof(SaveWidgetCallback), 
                JsonSerializer.SerializeToUtf8Bytes(widget),
                TimeSpan.FromSeconds(5),
                TimeSpan.FromSeconds(5)); 
}

private async Task SaveWidgetCallback(byte[] bytes)
{
    var widget = JsonSerializer.Deserialize<Widget>(bytes);
    using (var db = new WidgetDbContext())
    {
        db.Widgets.Add(widget);
        await db.SaveChangesAsync(); 
    }
}
```

### Exception Handling for strongly-typed Actor method invocation

Previously actor methods (when invoked in a strongly typed way) would include the full exception details in the repsonse, including constructing the same type of exception on the client side.

```C#
var proxy = ActorProxy.Create<IDemoActor>(actorId, "DemoActor");
try
{
    // attempt to withdraw 1 billion dollars
    await proxy.Withdraw(1_000_000_000m)
}
catch (OverdraftException)
{
}
```

While this behavior is convenient, it uses the `BinaryFormatter` serializer which is [rife with security flaws](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide). There is unfortunately no truly safe way provided by .NET to serialize arbitrary exception types. There's a design underway here: https://github.com/dotnet/runtime/issues/43482 - if you'd like to see an experience like this come back to Actors, because go upvote and give your two cents on that issue.

For right now when an actor method throws an exception, the exception thrown on the caller side will be `ActorInvokeException`

```C#
var proxy = ActorProxy.Create<IDemoActor>(actorId, "DemoActor");
try
{
    // attempt to withdraw 1 billion dollars
    await proxy.Withdraw(1_000_000_000m)
}
catch (ActorInvokeException ex) when (ex.ActualExceptionType == typeof(OverdraftException).FullName)
{
}
```

We're open to improvements here - please share your code samples and ideas about how this can be better. 

### ActorTypeInfo now has a private constructor

We don't expect this to impact anyone - this was an API that isn't intended for users.

**Comment by vinayada1** [comment]
LGTM

**Comment by vinayada1** [comment]
Added docs
