### ISSUE TITLE
Allow users to plug-in custom serialization for remoting calls.

### ISSUE THREAD

**Issue by amanbha** [dapr/dotnet-sdk#51]

**Comment by behoyh** [comment]
Does this include users being able to make deserialization as strict or as flexible as desired?

**Comment by amanbha** [comment]
@behoyh  yes, it would use a user provided Serializer/Deserializer so it can do whatever it wants.

**Comment by behoyh** [comment]
I have an idea for how this should work... where do you say would be the best step in the Actor process to plug in the serializer?

**Comment by amanbha** [comment]
@behoyh It would be needed both on the client and service side. On the service side it can be plugged in when (registering the Actor)[https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Actors/Runtime/ActorRuntime.cs#L45]. On the client side it can be plugged in while creating a ActorProxy. May be we need to introduce a ActorProxyFactory, user will create a ActorPrpoxyFactory  which will take a serializer/deserializer and then use that factory to create ActorProxies.

**Comment by behoyh** [comment]
Very cool. How does the client register the ActorProxy? It sounds like the client might know too much about the request before it is sent.

**Comment by amanbha** [comment]
> Very cool. How does the client create the ActorProxy? It sounds like the client might know too much about the request before it is sent.
> 
> I was thinking the request could be mapped to the service on a best effort basis based on how stringent the custom serializer/deserializer supplied by the user was.
> 
> Perhaps a warning could be emitted following a failed / incomplete mapping and a separate listener can act on that.

The serializer/deserializer needs to work both for request/response both on client and service side, so we will have to plug them in on both the sides. When you say failed/incomplete warning, is that a compile time or runtime thing?

**Comment by behoyh** [comment]
Oh right, I see it now. Would the serializer be required if there was deserializer specified?

Ideally I would have that as a runtime thing in Prometheus format and allow a separate structured logger pick it up.

**Comment by amanbha** [comment]
> Oh right, I see it now. Would the serializer be required if there was deserializer specified?
> 
> Ideally I would have that as a runtime thing in Prometheus format and allow a separate structured logger to pick it up.

Yes both the things will be required.
The flow would be:
1. Serialize on Client side and send the request.
2. On the service side, deserialize the request and call method on actor.
3. Get the return value(or exception) from actor method, serialize and send it as response to client.
4. On the client side, get the response, deserialize to return type (or exception) and  give it to user code.

**Comment by behoyh** [comment]
Got it. I will aim at implementing this!

**Comment by amanbha** [comment]
> Got it. I will aim at implementing this!

Great, thanks, looking forward tot he contribution!

**Comment by vinayada1** [comment]
Covered by other issues related to serialization
