### ISSUE TITLE
Unable to send custom http headers using DaprClient 

### ISSUE THREAD

**Issue by marounb98** [dapr/dotnet-sdk#512]
## Expected Behavior

I am using service invocation in order to call an endpoint that require a specific http header.I am using DaprClient to accomplish this. 
In other terms, microservice A want to invoke a method on microservice B that require a specific http header.

## Actual Behavior
 The issue was that the endpoint i am calling needs specific http headers in order to function, this is why dapr is returning a bad request. However, I still did not figured out a way to send http headers to an invoked method using the DaprClient.
```
Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Bad Request")
   at Dapr.Client.DaprClientGrpc.MakeGrpcCallHandleError[TResponse](Func`2 callFunc, CancellationToken cancellationToken)
   at Dapr.Client.DaprClientGrpc.MakeInvokeRequestAsync(String appId, String methodName, Any data, HTTPExtension httpExtension, CancellationToken cancellationToken)
   at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TResponse](String appId, String methodName, HTTPExtension httpExtension, CancellationToken cancellationToken)
```
## Steps to Reproduce the Problem
I have tried the below and i am still getting the bad request error ( stated above)
```
var metaData = new Dictionary<string, string>();
metaData.Add("test","test");
var client =  _httpContextAccessor.HttpContext.RequestServices.GetRequiredService<DaprClient>();
var res = await client.InvokeMethodAsync<Dictionary<string,string>, object>("MyApp", "MyMethod", metaData, new HTTPExtension(){Verb = HTTPVerb.Get});
```

Dapr version:
```
CLI version: 0.8.0 
Runtime version: 0.8.0
```
dotnet version:
```
3.1.101
```

**Comment by amolenk** [comment]
This has been fixed. The HttpInvocationOptions (previously HTTPExtension) now let's you specify custom headers to send along with the request.

**Comment by rynowak** [comment]
Closing this because it's been answered, thanks @amolenk

**Comment by marounb98** [comment]
> Closing this because it's been answered, thanks @amolenk

yes okay thanks !
