### ISSUE TITLE
Add a ServiceProxy class for doing service invocation

### ISSUE THREAD

**Issue by darraghjones** [dapr/dotnet-sdk#519]
In much the same way that ActorProxy class is used to abstract dapr to allow strongly typed method calls, similar functionality should be possible for remote service invocation using a ServiceProxy. 

e.g.

```
IMyService helloWorldClient = ServiceProxy.Create<IMyService>(appId);

string message = await helloWorldClient.HelloWorldAsync();
```

This is also consistent with Service Fabric.

**Comment by rynowak** [comment]
Hi @darraghjones thanks for the suggestion.

I'm closing this as out of scope. This would be a really large undertaking, and it seems to me like this problem is already adequately solved by libraries like Refit - or gRPC in general.

**Comment by darraghjones** [comment]
fair enough. is there any intention to try and keep parity (and consistency) with service fabric APIs? 
this was originally demonstrated as a 'feature' when dapr was originally launched
