### ISSUE TITLE
ModelBinding throws ArgumentNullException when state not found in store

### ISSUE THREAD

**Issue by amolenk** [dapr/dotnet-sdk#524]
## Expected Behavior

In the sample below, I'd expect `forecast` to be `null` when the value isn't found in the underlying data store.

```c#
[HttpGet("{city}")]
public ActionResult<WeatherForecast> Get([FromState("statestore", "city")] WeatherForecast forecast)
{
    if (forecast == null)
    {
        return NotFound();
    }

    return forecast;
}
```

## Actual Behavior

The code throws an `ArgumentNullException`. This happens at line 76 in dotnet-sdk/src/Dapr.AspNetCore/StateEntryModelBinder.cs (master):

```c#
bindingContext.ValidationState.Add(bindingContext.Result.Model, new ValidationStateEntry()
{
    // Don't do validation since the data came from a trusted source.
    SuppressValidation = true,
});
```

Here, `bindingContext.Result.Model` is `null`, which causes the exception. I guess we don't need to add the value to the validation state dictionary at all when it is `null`.

BTW if I use `StateEntry<WeatherForecast>` instead of `WeatherForecast`, everything works of course, because `StateEntry` itself is never `null`.

## Release Note
RELEASE NOTE:

**Comment by rynowak** [comment]
Thanks for the report - if there's an exception then this is definitely a bug. 

I think there's an interesting discussion to be had about the right semantics for when this happens. MVC's set of behaviors for model binding are pretty complex and idiosyncratic. 

Some options:

- Validation error + WeatherForecast is non-null
- Validation error + WeatherForecase is null
- no validation error + WeatherForecast is non-null

I think the best analog for consistency would be the behavior of `[FromBody]` because both of these constructs delegate their work to the JSON serializer. `[FromBody]` results in a null model object and a validation errors (bodies are never optional). We don't have a requirement or guarantee with `[FromBody]` binding to be able to construct the value like we do with standard modelbinding.

However, this means for users using `[ApiController]` that you'd see an HTTP 400 returned automatically with an error is the state key is not found. That doesn't seem like a helpful behavior since missing state is more like a 404 than a business validation failure.

Interested in hearing more thoughts (with examples).

**Comment by vinayada1** [comment]
I tried this with: https://github.com/dapr/dotnet-sdk/blob/master/samples/AspNetCore/ControllerSample/Readme.md#code-samples

[HttpGet("{account}")]
public ActionResult<Account> Get(StateEntry<Account> account)
{
    if (account.Value is null)
    {
        return NotFound();
    }

    return account.Value;
}

I do not see an ArgumentNullException. I see the client gets back:-
~ % curl http://127.0.0.1:5000/17

{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"|a1d5b431-44e61411f246ee60."}%

What am I missing?

**Comment by amolenk** [comment]
The issue only occurs when binding directly to the specific type (`Account` in your example) instead of `StateEntry`/`StateEntry<T>`

**Comment by vinayada1** [comment]
@amolenk - Sorry I meant to paste the code below which is getting invoked which looks the same as your example except for the class name:
[HttpGet("{account}")]
        public ActionResult<Account> Get([FromState(StoreName)] StateEntry<Account> account)
        {
            Console.WriteLine("@@@@@ Here");
            if (account.Value == null)
            {
                return this.NotFound();
            }

            return account.Value;
        }

**Comment by amolenk** [comment]
Hi @vinayada1 

Try this:
```c#
[HttpGet("{account}")]
public ActionResult Get([FromState(StoreName)] Account account)
{
    Console.WriteLine("@@@@@ Here");
    if (account == null)
    {
        return this.NotFound();
    }
    return account.Value;
}
```

You're correct that the only change is the class. If you use `StateEntry`, that will never be `null` because it's wrapping the `null` value coming back from the underlying data store. The bug is only triggered if you directly ask for the `Account` instance, which will be `null` if not found in the store.

**Comment by vinayada1** [comment]
> Thanks for the report - if there's an exception then this is definitely a bug.
> 
> I think there's an interesting discussion to be had about the right semantics for when this happens. MVC's set of behaviors for model binding are pretty complex and idiosyncratic.
> 
> Some options:
> 
> * Validation error + WeatherForecast is non-null
> * Validation error + WeatherForecase is null
> * no validation error + WeatherForecast is null
> 
> I think the best analog for consistency would be the behavior of `[FromBody]` because both of these constructs delegate their work to the JSON serializer. `[FromBody]` results in a null model object and a validation errors (bodies are never optional). We don't have a requirement or guarantee with `[FromBody]` binding to be able to construct the value like we do with standard modelbinding.
> 
> However, this means for users using `[ApiController]` that you'd see an HTTP 400 returned automatically with an error is the state key is not found. That doesn't seem like a helpful behavior since missing state is more like a 404 than a business validation failure.
> 
> I lean towards "no validation error + WeatherForecast is null" as the best behavior, because everything else seems like a bad idea 😆
> 
> Interested in hearing more thoughts (with examples).

+1

**Comment by amolenk** [comment]
I agree that "no validation error + WeatherForecast is null" is the best scenario here. That way, the developer can choose how to handle it.
