### ISSUE TITLE
Reimagining service invocation for dotnet-sdk

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#526]
## Describe the proposal

One of the things that's evolved over the last year of Dapr's existence has been how the SDKs interface with service invocation. In particular the .NET, Java and Go SDKs use gRPC as an implementation detail to mediate between a client API surface (.NET in our case) and what's most likely an HTTP service being invoked on the other side. Invoke is interesting to talk about because it's one of the few places in Dapr where your code is probably on both sides of the interaction. 

The fundamental problem is that the .NET APIs we provide in this project aren't really *the truth* - the underlying system is defined by both the [Dapr API for service invocation](https://docs.dapr.io/reference/api/service_invocation_api/) and the callee (another web app). It's most likely that developer writing applications with Dapr wrote both sides of the operation when using service invocation (both the caller and callee).  The underlying Dapr APIs intend to be a passthrough that can preserve the semantics of the HTTP communication protocol in use - however the problem is that the SDK and the choice to use gRPC as a detail result in an *impedance mismatch* - we're not currently doing a good job being a passthough.

I think we could leverage more of users' existing experience and the .NET community's existing assets by making the standard `HttpClient` API surface featured more prominently in Dapr's samples and guidance. I want to start a discussion about this and see what kinds of changes make sense. This proposal includes some ideas about how we could make using Dapr with HTTP simpler within the scope of the .NET SDK without changes to Dapr's protocol or runtime.

## The current landscape

The current design approach is that the `DaprClient.InvokeMethodAsync` family of APIs map to use of the [Dapr gRPC APIs for service invocation](https://github.com/dapr/dapr/blob/master/dapr/proto/runtime/v1/dapr.proto#L22). The Dapr API for service invocation provides an abstraction over HTTP and gRPC - in theory a caller does not need to know what protocol is used in the callee. 

Remember that *the big idea* here is that we can provide a set of .NET APIs that *map to either HTTP or gRPC* on the remote end *without the caller needing to know*. I'll briefly enumerate some of the issues that we've found with this approach - I think for most serious users, you will have encountered one of these limitations.

### HTTP and gRPC are different

The headline problem is that the *style* of designing services in HTTP and gRPC are different, especially when you look at non-success cases. If it helps, think of gRPC as an opinionated subset of HTTP. 

It's a very typical pattern in HTTP services to use the response body to indicate semantic information for non-success cases. For instance ASP.NET Core MVC will automatically return business validation error messages using a [problem details](https://tools.ietf.org/html/rfc7807) JSON payload. It's execeedingly common for systems based on REST to choose a standard error payload format and use it consistently.

For gRPC - all you get is a status code and message in a true "error" response. You have a few options:

- Use a simple status code and message
- Use an advanced feature like [gRPC rich error model](https://jbrandhorst.com/post/grpc-errors/)
- Make error reporting for business rules part of the message itself (in-band errors)
  
They key insight is that we genuinely **can't** abstract over the differences between these error models. The result is that the caller *has to know* how the callee service will report errors, because it's protocol specific. So our abstraction doesn't really work if you think of it as an abstraction over the way users design services today.

### We're translating in the wrong direction

There's a known technique for allowing an HTTP caller to call a gRPC service called [gRPC Gateway](https://github.com/grpc-ecosystem/grpc-gateway). This is a tried and tested technology with real production use. It works well because many common use cases of gRPC are an opinionated subset of HTTP. So providing HTTP callers a way to call a gRPC API is straightforward.

Unfortunately we're currently attempting the opposite. Using gRPC as a client library to call HTTP callers causes some genuine technical problems trying to pack HTTP requests into gRPC messages. The design on the runtime side has gone though multiple iterations of how this works, and hasn't really reached a stable point - there are still some unresolved issues. Remember that we're making the common case (using the SDK with its defaults) rely on the most complicated case (HTTP service invoked via gRPC).

### Dapr for gRPC services is not mature yet 

While Dapr has *some* support for implementing services via gRPC - I think this needs to be heavily caveated. The approach via `AppCallback` is not what the average user would expect to if you told them Dapr supports gRPC. The average person who's familar with gRPC would expect to use the generated code for both services and clients provided by the gRPC implementation in their language of choice.

So while right now we're *trying* to provide an abstraction over gRPC services - it's likely that a mature gRPC programming experience for Dapr would have a different shape.

We've gotten this feedback through multiple channels but there's no github issue I can point to at the moment.

### Performance is worse when packing HTTP into gRPC

There are a few key claims that are typically made to assert that gRPC's performance is better than HTTP+JSON's. The main one is that Protobuf serialization is more compact and thus more efficient than JSON. 

While this is true for many use cases there are a few a major caveats:

- Protobuf requires length-prefixing on variable length fields (nested message, the `Any` type). This means that the entire payload needs to be held in contiguous memory. For .NET this *will* lead to LOH allocations for any message over 85kb and absolutely tank your performance in the calling application.
- The efficiency of Protobuf is a meaningful claim when your content is "Protobuf-native". If you're using another format embedded in Protobuf then this benefit is lost, because you had to produce that other format in the first place.

Since our main use case is serializing JSON inside a Protobuf message we're likely exhibiting a very high overhead inside the callee application to generate the message, for a similar outcome in wire size to just using HTTP+JSON.

### We're not leveraging the ecosystem aroung HttpClient

Feedback: #519 #466 #441

By creating our own client type we're building something complex with its own conventions and style. However, it's very unlikely that we can put enough investment into the `InvokeMethodAsync` family of APIs to give users the level of control and richness that the .NET standard library does. For instance the .NET `HttpClient` already has built-in support libraries to simplify using `Newtonsoft.Json` and `System.Text.Json`. Encouraging the use of `HttpClient` would make the majority of *Daprized* service invocation code look similar to exising code and be more incrementally adoptable.

Additionally, there are great frameworks built around advanced or opinionated usage of `HttpClient` or code generation that targets `HttpClient`. I'll briefly list a few here:

- [Refit](https://github.com/reactiveui/refit)
- [Autorest](https://github.com/Azure/autorest)
- [RestSharp](https://restsharp.dev/getting-started/getting-started.html#basic-usage)
- [NSwag](https://github.com/RicoSuter/NSwag)

## The proposal

The solution is actually quite simple from a code perspective. We would add a `DelegatingHandler` implementation that can rewrite URLs to their Daprized form. This could then be used with any `HttpClient` or `HttpMessageInvoker` based library. We would provide convenience APIs as necessary to make this easy to contruct and use.

There's a few options for how we could design this, one of the simplest ways would be via interpreting the hostname as an `app-id`.

For example:

```txt
http://bank/account/17 -> http://localhost:3500/v1.0/invoke/bank/method/account/17
```

This translation would be done inside the `HttpClient`'s processing pipeline. It doesn't require a service mesh or any other external technology. This is a similar approach to service discovery libraries like Steeltoe.

The advantage of this URL translation approach is that it's largely transparent to application code. Users are already familiar with configuring the base URL of an `HttpClient`. Once you configure the base URL **the URLs you use in your code are same as the routes you implemented in the other service**. Basically your code functions the same way it did before, but you're now leveraging Dapr's service discovery and tracing. I would also emphasize that most users already organize their code this for separation of concerns - creating/configuring the client is separate from using it in most real applications.

**I've added some samples in a repo here: https://github.com/rynowak/dapr-httpclient-extravaganza**

Example code:

```C#
// We'll want to make this part easier to figure out.
var bankClient = new HttpClient(new DaprInvokeHandler(new HttpClientHandler()))
{
    BaseUri = new Uri("http://bank"),
};

// Somewhere else in your application
var accountId = ...;
var account = await bankClient.GetAsJsonAsync($"/account/{accountId}");
```

This approach also works with libraries like Refit that totally abstract over `HttpClient`:

```C#
// Define an interface for the remote service
public interface IBank
{
    [Get("/accounts/{accountId}")]
    Task<Account> GetUser(string accountId);
}

// We'll want to make this part easier to figure out.
var bankClient = RestService.For<IBank>(new HttpClient(new DaprInvokeHandler(new HttpClientHandler()))
{
    BaseUri = new Uri("http://bank"),
});


// Somewhere else in your application
var accountId = ...;
var account = await bankClient.GetUser(acountId);
```

> :bulb: Note: you could also do something like: `BaseUri = new Uri(http://localhost:3500/v1.0/invoke/bank/method/")`. And then in theory the handler is not needed. But this ends up being fragile. Using a rooted path like `/account/17` would *escape* the Dapr invoke URL-space vs a non-rooted path `account/17` would would as desired.

## Next Steps

I'm going to put together a runnable sample of all of the above including a few more examples so people can view it and comment on the utility. 

I'm also very interested in thoughts from the community at-large on whether this approach would be an improvment. Do you like the existing design for invoke and things it's better than the approach outlined above? (and why) Are there issues you've run into that you don't think are solved by this?

I think the response to this idea and the feedback will determine our next steps.

**Comment by amolenk** [comment]
Really like the proposal!

The current implementation does not provide an elegant abstraction over HTTP and gRPC. Types like `HttpInvocationOptions` and multiple invoke methods for different scenarios (`InvokeMethodAsync`, `InvokeMethodWithResponseAsync`, `InvokeMethodRawAsync`) are all necessary to make it work, but they aren't natural to use for a C# developer who's used to HttpClient.

The question then becomes, what do we gain by adding this abstraction? Not much I think. You can use the Dapr instance as a protocol bridge, but this seems as an edge case to me. After all, if the SDK makes calling both HTTP and gRPC methods very easy and natural, why would I need a bridge?

I think the users are better served by providing great experiences for HTTP and gRPC separately, without worrying about abstractions. Your example focuses on HTTP and that seems to be the way to go, because as you said, the gRPC experience isn't there yet. For gRPC, I'd want to be able to use my own proto files and have the sidecar automatically call my gRPC method, without having to implement the Dapr specific proto file.

I love the simplicity of URLs like `http://bank/account/17`. Mainly because I think it's confusing that for HTTP, the `method` is actually the complete HTTP route.

I also think it's a big advantage that we'd be able to use existing tooling around HttpClient. I often use [Polly](https://github.com/App-vNext/Polly) in projects to add more elaborate retry handling and cache responses, which also has provides extensions for integration with HttpClient.

**Comment by codeputer** [comment]
I'm not familiar with the PR, but trying to create an abstraction over various protocols was tried ..and failed...WCF anyone?

Their is a place for HTTP versus a proxy call, but IMO that is only for ingress into DAPR, or egress to an external service HTTP API.

Within DAPR why would you choose between HTTP and a proxy over GRPC?

I personally look forward to hosting GRPC endpoints as the norm, living again with data and service contracts over the brittle (yet simple) no contract HTTP service endpoints for application deployment.

Let's us please learn from WCF and the confusion created when high level abstractions have too many configuration options..... It was both a very slow painful death of a tech.

My 2 cents...

Richard

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rynowak** [comment]
Thanks @amolenk and @codeputer for your feedback. I'm also wondering if you've hit specific use cases with the current approach that are difficult, or code samples that are awkward.

> The current implementation does not provide an elegant abstraction over HTTP and gRPC. Types like HttpInvocationOptions and multiple invoke methods for different scenarios (InvokeMethodAsync, InvokeMethodWithResponseAsync, InvokeMethodRawAsync) are all necessary to make it work, but they aren't natural to use for a C# developer who's used to HttpClient.

This is where my head is at. [There's a lot of different libraries](https://twitter.com/aVerySpicyBoi/status/1345835786109796352) that build on top of or supplant the `HttpClient` and `Http{Request, Response}Message` APIs. The more investment we put into these scenarios the more our APIs will resemble `HttpClient` or one of those other wrapper libraries. It doesn't seem like a good direction to move knowingly.

When we get feedback like "make this work with Newtonsoft.Json" - I feel like the best way to win is not to play. 

> I think the users are better served by providing great experiences for HTTP and gRPC separately, without worrying about abstractions. Your example focuses on HTTP and that seems to be the way to go, because as you said, the gRPC experience isn't there yet. For gRPC, I'd want to be able to use my own proto files and have the sidecar automatically call my gRPC method, without having to implement the Dapr specific proto file.

I have a pretty strong gut feeling about this as well. We're already seeing plenty of user demand for the standard gRPC programming model, and we haven't done the work in the runtime to light that up.

> I'm not familiar with the PR, but trying to create an abstraction over various protocols was tried ..and failed...WCF anyone?

I want to mention one thing about this - which is that the Dapr APIs (state, bindings, pub/sub, etc) are all surfaced as BOTH HTTP and gRPC. This has worked really well in general. It reduces maintenance for all of the *first-class* SDKs because they are easy to version/update. It enables users of platforms that don't have *first-class* SDKs to consume new features on day-1 because it's just an HTTP call.

However I think that invoke is a different case and deserves to be treated differently because it involves user code and existing protocols on both sides of the interaction.

**Comment by amolenk** [comment]
Here's an example from eShopOnDapr.

Current code:
``` c#
var daprClient = new DaprClientBuilder().Build();

var basketData = await daprClient.InvokeMethodAsync<BasketData>(
      "basket-service",
      $"api/v1/basket/{customerId}",
      new HttpInvocationOptions
      {
          Method = HttpMethod.Get,
          Headers = new Dictionary<string, string>
          {
              [HeaderNames.Authorization] = $"Bearer {accessToken}"
          }
      });
```

HttpClient code:
``` c#
// We'll want to make this part easier to figure out.
var basketClient = new HttpClient(new DaprInvokeHandler(new HttpClientHandler()))
{
    BaseUri = new Uri("http://basket-service"),
};
basketClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

// Somewhere else in your application
var basketData = await basketClient.GetAsJsonAsync($"api/v1/basket/{customerId}");
```

I like that setting up the client and using it are two distinct operations in the HttpClient code. It would look a bit different if the access token cannot be set as a default value of course, but I still prefer the use of HttpClient because devs can use existing skills.

**Comment by rynowak** [comment]
Tagging this as a potential breaking change.

**Comment by amolenk** [comment]
@rynowak Any thoughts yet on how this will impact the current service-invocation methods offered by `DaprClient`? For example, will classes like `HttpInvocationOptions` remain, or should users always use `HttpClient` for invoking an HTTP service method?

**Comment by rynowak** [comment]
I would unequivocally recommend users adopt `HttpClient` + the `System.Net.Http.Json` package (or whatever else you want).  If you dislike `HttpClient` (some do) there are numerous other libraries out there that layer on top and offer different flavors of APIs. 

Whether or not we remove or change the `InvokeMethodAsync` methods isn't really a settled matter yet. Removing them completely would be a really large change to do this close to the 1.0 release, so it's not something that I'm proposing. Do they go away in some future release? Maybe ... we'll see what users like. As a principle, I don't think libraries should provide ways of doing things that aren't recommended, but that's kinda where we're stuck.

---

I think we'll want to make some changes regardless, because we're going to use HTTP as the underlying transport for both HTTP endpoints and gRPC endpoints (all SDKs). Basically we're avoiding or removing the *HTTP over gRPC* code path. https://github.com/dapr/dapr/issues/2342

A lot of the complexity in the design is there because we didn't want to be coupled to `System.Net.Http` types for doing gRPC requests, and we needed to represent the different error models of HTTP and gRPC. However, with the changes to the approach that we're going with everything is going to be HTTP so this can be simplified and optimized for HTTP.

I'd be happy to take proposals or suggestions 😆 I've haven't cracked open the design of this yet.
