### ISSUE TITLE
Provide a single way to configure System.Text.Json serializer options for all Dapr Client and Actors features

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#532]
### The problem

We've gotten numerous pieces of feedback that the serializer options need to be configurable, and that there are too many places to configure them.

- #442 
- #441
- #476
- #362

The main issue is that the defaults don't work for certain types like F#'s unions in S.T.J. There are known workarounds for this, but it requires configuring the settings. It's unlikely that this problem will go away because in general writing a custom converter is the best solution for lack of serializer support. I'm sure we'll continue to find more cases and we need to allow users to unblock themselves.

### Proposal

The proposal is to add configuration of serializer options via DI. We'll introduce a new options type for Dapr's app-wide settings, and use DI-enabled entry points to get at the configuration. This means we'll need to change guidance for some features like `ActorProxy` which lead the user to a static entry point.

At the non-ASP.NET Core layer features like `DaprClientBuilder` will still have their own APIs for configuring settings, so usage of dotnet-sdk features in isolation will be the same as it is today.

**Comment by virtualcca** [comment]
Is there an update to this issue, now I try to use the dateonly type under Net7, and I will find that if you call through an actor, it will report an XML-related serialization failure (From DCS)

It stands to reason that under net7, STJ can already support dateonly

Now you can only temporarily use DateOnly to be converted to DateTime as an Actor's interface to external calls
