### ISSUE TITLE
Docker compose file sample for dapr and asp.net core application

### ISSUE THREAD

**Issue by ShankargoudPatil** [dapr/dotnet-sdk#534]
Hi , can someone please help me out get up and run dapr sidecar and asp.net core web API application, please suggest any change need to do in my docker compose file.                                                                              version: '3.4'
services:
  deviceapi:
    image: ${DOCKER_REGISTRY-}deviceapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
     - db
    networks:
     - my-dapr-network
  db:
     image: "mcr.microsoft.com/mssql/server"
     environment:
       SA_PASSWORD: "Cr0wc0n@123"
       ACCEPT_EULA: "Y"
     networks: 
      - my-dapr-network
  deviceapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "deviceservice",
     "-app-port", "5000",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50001",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      - deviceapi
    network_mode: "service:deviceapi"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - my-dapr-network
  redis:
    image: "redis:alpine"
    ports:
      - "6381:6379"
    networks:
      - my-dapr-network

networks:
    my-dapr-network:

**Comment by samcov** [comment]
They really need to document this more, but  for now, take a look at eShopOnDapr's docker-compose file, it may help.

https://github.com/dotnet-architecture/eShopOnDapr

**Comment by rynowak** [comment]
thanks @samcov - we will include this in the documentation.
