### ISSUE TITLE
InvokeBinding overload is missing unit tests

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#550]
We're missing a unit test on `DaprClient` for:

```C#
public Task<TResponse> InvokeBindingAsync<TRequest, TResponse>(...) 
```

We should have unit tests for all public entry points of the SDK even if they are similar to other methods.

**Comment by rynowak** [comment]
Found this while scanning through and looking for dead-code. We've had issues in the past with some of the APIs and ambiguities in overload resolution. Making sure all of them have tests is the best we can do to make sure we didn't set traps for users (uncallable APIs).

**Comment by mukundansundar** [comment]
@rynowak I can pick this up if it is still open

**Comment by rynowak** [comment]
Sure, feel free.

**Comment by ChrisProlls** [comment]
Let me give a try on this one :)
