### ISSUE TITLE
InvokeBinding doesn't provide an alternative way to work directly with raw data

### ISSUE THREAD

**Issue by mtaghavi2005** [dapr/dotnet-sdk#560]
## Expected Behavior
To be able to get binary data from Azure Blob Storage Binding, working directly with raw data for invoke binding in DaprClient is really needed.   

## Actual Behavior
There is no way to get raw data by calling InvokeBindingAsync and in case of receiving binary data the JSON Deserialization will raise the following exception:

System.Text.Json.JsonException: '%' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0. 

## Steps to Reproduce the Problem
1- Setup Azure BlobStorage Binding Component
https://docs.dapr.io/operations/components/setup-bindings/supported-bindings/blobstorage/
2- Call InvokeBindingAsync to get a binary blob (E.g. PDF file) from Azure Blob Storage.
```
   var metadataDictionary = new Dictionary<string, string>()
    {
        { "blobName", "dummy.pdf" },
    };

    var binaryArray = await _daprClient.InvokeBindingAsync<object, byte[]>("blobComponentName", "get", null, metadataDictionary);
```
  
## Release Note
As suggested in this issue #442 having a Raw method like InvokeMethodRawAsync would solve this issue. I gave it a try, and it could work fine.

**Comment by mtaghavi2005** [comment]
I know InvokeMethodRawAsync doesn't exist anymore (#544), but if you think having a raw method (InvokeBindingRawAsync) would be an appropriate solution, then I will create a pull request for it.

**Comment by rynowak** [comment]
Agreed, this would be something nice to add. A PR for this would be great. Can we try and agree on the method signature using this issue here? That will prevent you from doing unnecessary work.

**Comment by mtaghavi2005** [comment]
Awesome! I agree too. That would be great. 

My first thought was something like this :
```
 public override async Task<byte[]> InvokeBindingRawAsync(
        string name,
        string operation,
        byte[] data,
        IReadOnlyDictionary<string, string> metadata = default,
        CancellationToken cancellationToken = default)
```

But then I was thinking of having a Response Model (like InvokeBindingResponse) instead of returning only byte[], so that we can return metadata collection or the other useful information together with the data result. For example, by getting a blog from Blob Storage sometimes we need to have some metadata (like Last-Modified or Content-Type).
```
public sealed class InvokeBindingResponse
{
    public byte[] Data { get; set; }
    public IReadOnlyDictionary<string, string> Metadata { get; set; }
}

public sealed class InvokeBindingRequest
{
    public string Operation { get; set; }
    public byte[] Data { get; set; }
    public IReadOnlyDictionary<string, string> Metadata { get; set; }
}

```
 public override async Task<InvokeBindingResponse> InvokeBindingRawAsync(
        string name,
        InvokeBindingRequest request,
        CancellationToken cancellationToken = default)
```
What do you think?

**Comment by fabistb** [comment]
@rynowak please add it to our project. Thanks! -- @mtaghavi2005  is on our team.

**Comment by rynowak** [comment]
@fabistb - done

@mtaghavi2005 - thanks, that's a good starting point. I feel pretty positively about the second example but I'd suggest a few tweaks.

Is there a reason you wanted `name` and `operation split up? 

```C#
public sealed class InvokeBindingResponse
{
    public ReadOnlyMemory<byte> Data { get; set; }
    public IReadOnlyDictionary<string, string> Metadata { get; set; }
}

public sealed class InvokeBindingRequest
{
    public string BindingName { get; set; 
    public string Operation { get; set; }
    public ReadOnlyMemory<byte> Data { get; set; }
    public IReadOnlyDictionary<string, string> Metadata { get; set; }
}

 public abstract Task<InvokeBindingResponse> InvokeBindingRawAsync(
        InvokeBindingRequest request,
        CancellationToken cancellationToken = default);
```

Notable changes:

- I put the name and operation together, because it doesn't seem like they should be spread out like that
- Used `ReadOnlyMemory<byte>` instead of `byte[]` so that fewer copies need to happen

**Comment by rynowak** [comment]
@msfussell FYI

**Comment by rynowak** [comment]
hey @mtaghavi2005 - under normal circumstances, I'd prefer to let you send the PR since you offered it. However, for scheduling reasons it would be best I can just take care of this quickly so that we can turn it out. Sorry!

**Comment by mtaghavi2005** [comment]
> @fabistb - done
> 
> @mtaghavi2005 - thanks, that's a good starting point. I feel pretty positively about the second example but I'd suggest a few tweaks.
> 
> Is there a reason you wanted `name` and `operation split up?
> 
> ```cs
> public sealed class InvokeBindingResponse
> {
>     public ReadOnlyMemory<byte> Data { get; set; }
>     public IReadOnlyDictionary<string, string> Metadata { get; set; }
> }
> 
> public sealed class InvokeBindingRequest
> {
>     public string BindingName { get; set; 
>     public string Operation { get; set; }
>     public ReadOnlyMemory<byte> Data { get; set; }
>     public IReadOnlyDictionary<string, string> Metadata { get; set; }
> }
> 
>  public abstract Task<InvokeBindingResponse> InvokeBindingRawAsync(
>         InvokeBindingRequest request,
>         CancellationToken cancellationToken = default);
> ```
> 
> Notable changes:
> 
> * I put the name and operation together, because it doesn't seem like they should be spread out like that
> * Used `ReadOnlyMemory<byte>` instead of `byte[]` so that fewer copies need to happen

@rynowak  Thanks, sounds great! About BindingName I thought it is not going to be sent to the other Party, so it may not belong to the Request Object. It would be somehow much more similar to ExecuteStateTransactionAsync than InvokeMethodWithResponseAsync from the signature perspective. Because for both we need to firstly select the component block, and then we can pass our request to it.  It was just my thought, but generally, I don't have any problem with this change at all :)

**Comment by mtaghavi2005** [comment]
> hey @mtaghavi2005 - under normal circumstances, I'd prefer to let you send the PR since you offered it. However, for scheduling reasons it would be best I can just take care of this quickly so that we can turn it out. Sorry!

@rynowak No problem. That's totally fine. I appreciate your great support.

**Comment by farhadnowzari** [comment]
Hi,

I was wondering if this change is published into nuget.
I'm currently using Dapr.AspNetCore 1.4.0 and I'm still getting `System.Text.Json.JsonReaderException : '0xFF' is an invalid start of a value` on receiving raw files.

I'm using the Dapr LocalStorage binding and I can successfully save the file with the following command:
```
                await _daprClient.InvokeBindingAsync(_storageOptions.Type, "create", imageBytes, new Dictionary<string, string> {
                    {"fileName", "test.jpg"}
                });
```
but when I want to read it I get exception that it cannot deserialize it.
```
                    imageOriginalBytes = await _daprClient.InvokeBindingAsync<string, byte[]>(_storageOptions.Type, "get", null, new Dictionary<string, string> {
                        { "fileName", $"test.jpg" ?? "" }
                    });
```
