### ISSUE TITLE
415 unsupported media type on pubsub

### ISSUE THREAD

**Issue by LukePammant** [dapr/dotnet-sdk#581]
## Expected Behavior

When I use the DaprClient to publish an event the events handlers in my MVC app returns a 415. I would expect to be able to call PublishEventAsync, give it an object to serialize, and have dapr post the event to the subscriber with an "application/json" ContentType.

## Actual Behavior

I use the following code to publish an event:
```
await _daprClient.PublishEventAsync(_pubSubName, LoginCreated.Topic, new LoginCreated(user.Id, email, username));
```

When I examine the event that dapr is publishing the "datacontenttype" is "text/plain". 

The published dapr event body:

```
{
    "id": "0075754b-9ced-4308-95b4-2a69a24eeb38",
    "specversion": "1.0",
    "datacontenttype": "text/plain",
    "source": "authentication",
    "topic": "login-created",
    "pubsubname": "messagebus",
    "type": "com.dapr.event.sent",
    "data": "{\"id\":\"ce9b9dd1-baf5-4d55-a3ce-c2d3f30eea0f\",\"email\":\"test@testing.com\",\"username\":\"testuser\",\"createdDate\":\"2021-02-05T18:00:32.8255775Z\"}",
    "traceid": "00-5baf56a9be69f54c9f75f24b64203e9e-7eeabb778bb504f6-00"
}
```

If I examine the request after the `.UseCloudEvent()` middleware it's setting the request's ContentType to "text/plain" and setting the body to:

"{\u0022id\u0022:\u0022ce9b9dd1-baf5-4d55-a3ce-c2d3f30eea0f\u0022,\u0022email\u0022:\u0022test@testing.com\u0022,\u0022username\u0022:\u0022testuser\u0022,\u0022createdDate\u0022:\u00222021-02-05T18:00:32.8255775Z\u0022}"

MVC rejects the request w/ a 415 because "text/plain" isn't expected. You can also see that it encodes each of the quotes in a way that I'm not sure MVC/System.Text.Json knows how to parse even if the ContentType were set to "application/json".

My controller action is decorated with:
```
[Topic("messagebus", "login-created")]
[HttpPost("/login-created")]
public async Task<ActionResult<User>> NewUserCreated(LoginCreatedEvent evt)
{ 
   //...
}
```

## Steps to Reproduce the Problem

Publish an event. From the receiving app use `.UseCloudEvents()` and the the `[Topic]` attribute to decorate your controller method.

## Release Note
I'm using the master branch @ commit: https://github.com/dapr/dotnet-sdk/commit/bb891fa14f88c50e78942a77f64df4263e7b3dd1

I'm using dapr runtime 1.0.0-rc3 running in a local kubernetes cluster on Docker Desktop. 

RELEASE NOTE:

**Comment by vinayada1** [comment]
@LukePammant - What version of dotnet sdk are you using. You should be using 1.0.0-rc05 into which a related change has gone in

**Comment by LukePammant** [comment]
In my docker build file I'm pulling directly from master on this git repo. I will try using the nuget package instead and see what happens.

**Comment by rynowak** [comment]
This is something that was a relatively last minute change for the SDK - so depending on exactly what commit you have the result might be wrong. It will be helpful to see if this is passing or not with 1.0.0-rc05

**Comment by LukePammant** [comment]
Ugh I'm an idiot - I think docker was caching the layer where I pulled in the dotnet repo so it didn't have the very latest commit😞 

`RUN git clone https://github.com/dapr/dotnet-sdk.git` 

Ran a `docker build --no-cache` and it looks like my pubsub is working again.
