### ISSUE TITLE
Is that possible to make ActorHost into a interface and access it from IServiceProvider?

### ISSUE THREAD

**Issue by newbe36524** [dapr/dotnet-sdk#587]
I think it is better to make it abstract, just like IHttpAccesser in aspnet core. It is good for unit test.

In this way, there are no restrictions on constructors that I must add ActorHost as the first parameter.
I can resolve it in my services and pass it to base Actor class.

e.g. here is constructor I am using now.
```cs
public AccountActor(ActorHost actorHost,
    IClaptrapActorCommonService claptrapActorCommonService)
    : base(actorHost, claptrapActorCommonService)
{
}
```

```cs
public interface IClaptrapActorCommonService
{
    IClaptrapFactory ClaptrapFactory { get; }
    IClaptrapAccessor ClaptrapAccessor { get; }
    IClaptrapTypeCodeFactory ClaptrapTypeCodeFactory { get; }
    ILifetimeScope LifetimeScope { get; }
    ActorHost ActorHost { get; }
}
```

However, there is no way to resolve ActorHost from service provider in a lifetime scope.
If I can do that, I can make my constructor simpler as a single parameter constructor as below:

```cs
public AccountActor(IClaptrapActorCommonService claptrapActorCommonService)
    : base(claptrapActorCommonService)
{
}
```

**Comment by rynowak** [comment]
Can you give me some more information about what you're trying to accomplish? `ActorHost` has state associated with the instance and type of an Actor, so it's not likely to do what you want.

**Comment by rynowak** [comment]
Closing due to lack of response.
