### ISSUE TITLE
Remove usage of Newtonsoft.Json and use System.Text.Json

### ISSUE THREAD

**Issue by amanbha** [dapr/dotnet-sdk#59]
after move to .netcore 3.0, remove usage of NewtonsoftJson and use System.Text.Json so that Microsoft.Actions.Actors package has no external pkg dependency.

**Comment by gmanvel** [comment]
Should this porting guide be used when replacing ?
https://github.com/dotnet/corefx/blob/61024c30b966ee63c357a491370a2daf94c4c42f/src/System.Text.Json/porting_guide/README.md
