### ISSUE TITLE
Couldn't able to Debug from Vs code, /bin/sh: 1: daprd: not found

### ISSUE THREAD

**Issue by jayendranarumugam** [dapr/dotnet-sdk#611]
## Ask your question here
I'm trying to debug the `controllersample` from my local vs code , in WSL

This is my Launch.json

```
{

            "name": ".NET Core Launch (web) with Dapr",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "daprd-debug",            
            "program": "${workspaceFolder}/bin/Debug/net5.0/ControllerSample.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\\\bNow listening on:\\\\s+(https?://\\\\S+)"
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            },
            "postDebugTask": "daprd-down"
        },
``` 

this is my task

```
        {
            "type": "daprd",
            "label": "daprd-debug",
            "appId": "controller",
            "appPort": 5000,
            "dependsOn" : "build"
        },
        {
            "type": "daprd-down",
            "label": "daprd-down",
            "appId": "controller"
        }
```

But when I run I got like the below

Executing task: dotnet build /mnt/f/dapr/dotnet-sdk/examples/AspNetCore/ControllerSample/ControllerSample.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Dapr.Client -> /mnt/f/dapr/dotnet-sdk/bin/Debug/prod/Dapr.Client/netcoreapp3.1/Dapr.Client.dll
  Dapr.AspNetCore -> /mnt/f/dapr/dotnet-sdk/bin/Debug/prod/Dapr.AspNetCore/netcoreapp3.1/Dapr.AspNetCore.dll
  ControllerSample -> /mnt/f/dapr/dotnet-sdk/bin/Debug/examples/ControllerSample/netcoreapp3.1/ControllerSample.dll

Terminal will be reused by tasks, press any key to close it.

> Executing task: daprd-debug <

> Executing command: daprd --app-id "controller" --app-port "5000" --components-path "/home/jayendran/.dapr/components" --placement-host-address "localhost:50005" <

/bin/sh: 1: daprd: not found

Terminal will be reused by tasks, press any key to close it.

P.S I can able to run the application without having any issue,only debug is not working. Am I missing anything here?

**Comment by rynowak** [comment]
@philliphoff - is this related to the VSCode extension? Can you help here?

**Comment by philliphoff** [comment]
@rynowak Yes and no.  The extension expects that `daprd` is in the `PATH`, which recent Dapr versions no longer do upon installation.

@jayendranarumugam *Which* `PATH` it should be added to will depend on your platform and shell.  For example, on my Mac where I use ZSH, I added it to the `PATH` in my `~/.zshrc` file.

**Comment by rynowak** [comment]
> The extension expects that daprd is in the PATH, which recent Dapr versions no longer do upon installation.

Since this isn't the default anymore, should the logic change?

It sounds like there was a miscommunication about this if it requires extra setup on the users part that we don't do as part of Dapr.

**Comment by philliphoff** [comment]
There should be a better way of dealing with it, yes, which is [vscode-dapr#139](https://github.com/microsoft/vscode-dapr/issues/139).

To be fair, the Dapr installation *does* show a warning that you might want to add `daprd` to the `PATH`.

**Comment by jayendranarumugam** [comment]
@philliphoff I'm using WSL ubuntu20.04 LTS on my windows 10 machine, And my current path file (`/etc/environment`) is having the below value

`PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"`


I tried to add like 

```
export PATH=$PATH:/home/jayendran/.dapr/bin
source ~/.profile 
```
But still getting the same issue

**Comment by jornhd** [comment]
Same problem here (WSL ubuntu 20.04 on Win10). The weird thing is that if I go to ~/.dapr/bin and type daprd, it still says command not found, even though it is present: `-rwxrwxrwx 1 me me 85630976 Mar  3 20:41 daprd`

**Comment by rynowak** [comment]
Hi, if you're looking for help with this further I suggest asking at the https://github.com/dapr/cli repo or the https://github.com/microsoft/vscode-dapr repo. It's clear that this is not related to the .NET SDK for Dapr so I'm going to close.
