### ISSUE TITLE
Usage of nested configuration in Kubernetes Secret

### ISSUE THREAD

**Issue by Fabian-Schmidt** [dapr/dotnet-sdk#615]
I am trying to use the secret management in a Kubernetes cluster with a nested configuration object.

I am using the [`DaprSecretStoreConfigurationProvider`](https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Extensions.Configuration/DaprSecretStoreConfigurationProvider.cs) with bulk secret reading.

A secret in Kubernetes config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')

A secret value must be a flat string.

How is the intended usage with a nested .NET config in this scenario? As the normally used `:` is not allowed for Kubernetes secrets.

**Comment by rynowak** [comment]
This seems like a fine improvement. Since this is a change in behavior we have to add an opt-out. Using `__` is unusual enough and specific enough to ASP.NET Core that I'm comfortable with an opt-out fix.
