### ISSUE TITLE
asp.net core How can sub?

### ISSUE THREAD

**Issue by a121984376** [dapr/dotnet-sdk#626]
## Ask your question here
pub is ok 
![image](https://user-images.githubusercontent.com/15758574/110438478-62eb6600-80f1-11eb-98ff-f083daee43e6.png)

but asp.net core  How Can sub?

there is nothing to receive
![image](https://user-images.githubusercontent.com/15758574/110439418-67644e80-80f2-11eb-8b68-33b63c7c1431.png)

![image](https://user-images.githubusercontent.com/15758574/110439444-70552000-80f2-11eb-9a1d-a8fda237e9bf.png)

**Comment by a121984376** [comment]
> ## Ask your question here
> pub is ok
> ![image](https://user-images.githubusercontent.com/15758574/110438478-62eb6600-80f1-11eb-98ff-f083daee43e6.png)
> 
> but asp.net core How Can sub?
> 
> there is nothing to receive
> ![image](https://user-images.githubusercontent.com/15758574/110439418-67644e80-80f2-11eb-8b68-33b63c7c1431.png)
> 
> ![image](https://user-images.githubusercontent.com/15758574/110439444-70552000-80f2-11eb-9a1d-a8fda237e9bf.png)

pub code.
![image](https://user-images.githubusercontent.com/15758574/110439572-967ac000-80f2-11eb-93a5-fee16f4e66a9.png)

**Comment by rynowak** [comment]
Please try the pub/sub troubleshooting guide: https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-troubleshooting/dotnet-troubleshooting-pubsub/
