### ISSUE TITLE
Dapr Configuration Normalization for Azure Key Vault

### ISSUE THREAD

**Issue by SamuelMcAravey** [dapr/dotnet-sdk#627]
## Describe the proposal
Currently, the `Dapr.Extensions.Configuration` NuGet package includes functionality to normalize a double underscore '__' into a colon to allow for hierarchical configuration. When using the Azure Key Vault secret store we run into the limitation described here:

> Azure Key Vault secret names are limited to alphanumeric characters and dashes. Hierarchical values (configuration sections) use -- (two dashes) as a separator. Colons, which are normally used to delimit a section from a subkey in ASP.NET Core configuration, aren't allowed in key vault secret names. Therefore, two dashes are used and swapped for a colon when the secrets are loaded into the app's configuration.

https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-5.0#secret-storage-in-the-production-environment-with-azure-key-vault

Since the Azure Key Vault secret store is officially supported by Dapr I believe it would be a good idea to either:
1) Add normalization specifically for Key Vault (easy)
2) Allow for customizable normalization or modification of the configuration keys via code (hard)

https://github.com/dapr/dotnet-sdk/blob/7890bc7977e68af8bab85066d2e8213497cda1bd/src/Dapr.Extensions.Configuration/DaprSecretStoreConfigurationProvider.cs#L72-L75

The first option could be changed like this:
```csharp
private static string NormalizeKey(string key)
{
    return key.Replace("__", ConfigurationPath.KeyDelimiter).Replace("--", ConfigurationPath.KeyDelimiter);
}
```

Is this something feasible?

**Comment by rynowak** [comment]
We already added this I think: https://github.com/dapr/dotnet-sdk/issues/615 - it will be part of an upcoming 1.1 release of the SDK.

Does this address what you're looking for?

**Comment by rynowak** [comment]
I think we could make the delimiter configurable - this is what other config providers for `Microsoft.Extensions.Configuration` do. That way the core logic would live inside the SDK, and users would just be responsible for providing delimiters.

We're not going to add support for additional delimiters as built-in defaults. It's always a breaking change to add one, and there are already two built-in options.. `:` and `__`.

**Comment by rynowak** [comment]
I'm open to suggestions about how to make this easy, but my reservation is that we can't add all possible delimiters for all possible configuration stores as defaults. That becomes to hard to work with in the other direction.

**Comment by SamuelMcAravey** [comment]
I do agree that it makes things harder, and I hadn't considered the breaking changes. I'll take a look at options for configuring the delimiters and report back.

**Comment by SamuelMcAravey** [comment]
I've submitted a tentative PR that adds support for arbitrary delimiters while preserving the current behavior with the built-in options. Let me know if that approach looks like we're going down the right path or not. Thanks!

**Comment by rynowak** [comment]
For anyone looking at this issue in the future, we added a feature to allow customizing the set of delimiters that are used to parse keys into the configuration hierarchy. So for the keyvault case you can configure the configure the delimiter to `--`.  See the linked PR for examples.
