### ISSUE TITLE
pubsub is ok. but sub the data is wrong~

### ISSUE THREAD

**Issue by a121984376** [dapr/dotnet-sdk#630]
## Ask your question here
the pub code
![image](https://user-images.githubusercontent.com/15758574/110759743-e7242180-8288-11eb-96ec-afc480fb34cc.png)

the sub code
![image](https://user-images.githubusercontent.com/15758574/110758985-15edc800-8288-11eb-863f-57086d985616.png)
the sub  result
![image](https://user-images.githubusercontent.com/15758574/110759026-22722080-8288-11eb-97b8-08bcc55eae42.png)
the property are all null.....

whey?

**Comment by kshyju** [comment]
Are you supposed to have the `[FromBody]` attribute for the action method parameter ?

```
public IActionResult Sub([FromBody] Transaction input)
{
}
```

**Comment by rynowak** [comment]
Do you have `UseCloudEventsMiddleware()` in startup?

If it helps for debugging you could use:

```C#
public IActionResult Sub(JsonDocument input)
{
...
}
```

`JsonDocument` will give you the raw JSON values that were present, and then you can see if the JSON matches what you expect.

**Comment by a121984376** [comment]
> Are you supposed to have the `[FromBody]` attribute for the action method parameter ?
> 
> ```
> public IActionResult Sub([FromBody] Transaction input)
> {
> }
> ```

![image](https://user-images.githubusercontent.com/15758574/110879242-91e32100-8317-11eb-895a-13caf4c1f6ee.png)

**Comment by a121984376** [comment]
> UseCloudEventsMiddleware

i used   app.UseCloudEvents();

the result is ok .

thanks

**Comment by rynowak** [comment]
Glad to help. 

FYI

> Are you supposed to have the [FromBody] attribute for the action method parameter ?

`[FromBody]` is the default for this cause because it's also using `[ApiController]`
