### ISSUE TITLE
Azure CosmosDB StateStore Default Schema Value?

### ISSUE THREAD

**Issue by iayti** [dapr/dotnet-sdk#631]
Hi,

I do tryouts on Azure CosmosDB for Dapr .Net Sdk. I cannot see the OrderState object I have sent to CosmosDB in the JSON format in Azure Portal Data Explorer. Dapr client brings data from CosmosDB as a deserialized. I can read it 😊 . I need to read Value and write a select query. Id part is not serialized.
![image](https://user-images.githubusercontent.com/30297580/110796956-9cef7000-8289-11eb-9531-45632a93e53b.png)

[Dapr Docs for Azure Cosmos DB](https://docs.dapr.io/operations/components/setup-state-store/supported-state-stores/setup-azure-cosmosdb/#data-format) In the document, a note has been made that the dapr client is taking care of this regarding serialization.

I just change the Cosmos DB to Redis for state store using components, I can see the Json Result.
![image](https://user-images.githubusercontent.com/30297580/110798731-834f2800-828b-11eb-9961-60e7301c190f.png)

Should we have a different setting through this dapr client settings or a different adjustment via Azure Portal?

Additional Info. I can add manually json object to value
![image](https://user-images.githubusercontent.com/30297580/110820915-9e786280-82a0-11eb-9eae-edd422fd2e20.png)

Thank you for your help.
Have a nice coding.
İlker

**Comment by rynowak** [comment]
Hi, please refer to these issues, and it would be helpful if you could add your feedback there:

https://github.com/dapr/dapr/issues/2892

https://github.com/dapr/components-contrib/issues/745

The way a component (such as CosmosDB) stores data is not something the SDK can control.
