### ISSUE TITLE
Dapr Serialization Error with Dapr CLI Publish

### ISSUE THREAD

**Issue by tonysneed** [dapr/dotnet-sdk#634]
## Expected Behavior
Publish with Dapr CLI and ASP.NET subscriber does not generate serialization error.

## Actual Behavior
Publishing to a topic with the Dapr CLI and an ASP.NET subscriber generates a serialization error.

## Steps to Reproduce the Problem
1. Run ASP.NET subscriber: `dapr run --app-id my-subscriber --app-port 5000 -- dotnet run`
2. Publish to a topic: `dapr publish --publish-app-id my-subscriber --pubsub pubsub --topic bar --data '{"data":"bar"}'`
3. Error: **The JSON value could not be converted to Subscriber.Foo. Path: $ | LineNumber: 0 | BytePositionInLine: 24.**

To reproduce, see this repo: https://github.com/tonysneed/DaprSerializationError

> **Note**: No serialization error takes place when a simple string is passed to a subscription with a string parameter.

**Comment by rynowak** [comment]
Hi @tonysneed - I cloned your sample and tried it with no changes, and it works on my machine. I know that's a bit of an unhappy answer for you since you're still stuck.

```
➜ dapr --version
CLI version: 1.0.0
Runtime version: 1.0.1
```

I cloned your repo and followed the commands in your readme and saw the following output:

```
== APP == info: Subscriber.Controllers.SubscriptionController[0]

== APP ==       Foo posted: bar
```

Is your shell doing something weird with escaping here?

You might look into reading the request body as a string and seeing what the text contains. If it's not what you expect I can help you track down the problem further.

**Comment by tonysneed** [comment]
Hi Ryan, Thanks for checking this out. You're right. It's the way quotes need to be escaped on Windows.

On my Mac `'{"data":"bar"}'` works, but not on Windows. On Windows Terminal it needs to be `"{\"data\":\"bar\"}"`, because double quotes need to be escaped using backslashes. 🤦‍♂️

**Comment by mtrmmsoftware** [comment]
> Hi Ryan, Thanks for checking this out. You're right. It's the way quotes need to be escaped on Windows.
> 
> On my Mac `'{"data":"bar"}'` works, but not on Windows. On Windows Terminal it needs to be `"{\"data\":\"bar\"}"`, because double quotes need to be escaped using backslashes. 🤦‍♂️

Hi, apparently I am having the same issue, but on my case I am running the system in with docker compose with Linux containers, so even if the root OS is Windows, the docker and the containers are Linux-es. 

How did you solve the issue?
