### ISSUE TITLE
Add method for health check in dapr client

### ISSUE THREAD

**Issue by dmytrohridin** [dapr/dotnet-sdk#640]
## Proposal
https://docs.dapr.io/reference/api/health_api/
It would be useful to have build-in method (for example `Ping`) in `DaprClient` that checks health of sidecar

**Comment by rynowak** [comment]
Yes, this is something we should add. Happy to accept a PR from anyone who wants to help with this.

**Comment by dmytrohridin** [comment]
will try

**Comment by artursouza** [comment]
This issue is related to https://github.com/dapr/dotnet-sdk/issues/452
