### ISSUE TITLE
Default HTTP and gRPC ports inverted

### ISSUE THREAD

**Issue by laurentkempe** [dapr/dotnet-sdk#643]
## Expected Behavior

According to the [Dapr CLI documentation](https://docs.dapr.io/reference/cli/dapr-run/#flags)

--dapr-grpc-port |   | 3500 | The gRPC port for Dapr to listen on
-- | -- | -- | --
--dapr-http-port |   | 50001 | The HTTP port for Dapr to listen on

## Actual Behavior

The Dapr .NET SDK v1.0.0 uses the same port numbers but inverted the one for HTTP and the one for gRPC [we can see here](https://github.com/dapr/dotnet-sdk/blob/v1.0.0/src/Dapr.Client/DaprClientBuilder.cs#L20-L21).

        private const string DefaultDaprGrpcPort = "50001";
        private const string DefaultDaprHttpPort = "3500";

So, when you execute Dapr run without specifying the ports and want to connect to the default ports, the SDK cannot connect to it!

**Comment by rynowak** [comment]
@laurentkempe - where did you see that info? This is what I see today when I look at that page

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/1430011/114755130-2c1af800-9d0e-11eb-9db3-370a899fe03c.png">

**Comment by laurentkempe** [comment]
> It looks like the documentation was wrong and was changed recently to be correct. [dapr/docs@39c232b](https://github.com/dapr/docs/commit/39c232b21c98432de07fe443345d4fca01488661)

@rynowak Wow I thought I was crazy 🤪 Yes, I saw that on the [run CLI](https://docs.dapr.io/reference/cli/dapr-run/#flags) documentation and this was before the change of the doc 13 days ago as my issue is 16 days old.

> Is there a set of repro steps that leads to a problem?

I described it like that
> So, when you execute Dapr run without specifying the ports and want to connect to the default ports, the SDK cannot connect to it!

but I will try to reproduce and give a better detailed description.

**Comment by rynowak** [comment]
@laurentkempe - did you figure out what the issue was?

**Comment by laurentkempe** [comment]
I didn't had the time this week because I had quite some load at work, I might have a look over the weekend

**Comment by laurentkempe** [comment]
I could not reproduce it!
So, I guess what did happen is that I was following the wrong version of the documentation, prior to the fix and started dapr sidecar from the command line specifying the wrongly documented port. Then using the .NET SDK defaults which were correct but then could not connect to my services.
