### ISSUE TITLE
Allow adding custom HttpClientHandler(s) to DaprClient.CreateInvokeHttpClient

### ISSUE THREAD

**Issue by mmisztal1980** [dapr/dotnet-sdk#647]
## Describe the proposal

At the moment when using the `DaprClient.CreateInvokeHttpClient` it is impossible to provide your own `DelegatingHandler`(s) to handle additional requirements a programmer may have such as:

- performing additional logging
- performance measurement(s)
etc.

The proposal is to add an optional HttpClientHandler parameter to allow providing an externally preconfigured HttpClientHandler to handle outgoing HTTP requests.

**Comment by rynowak** [comment]
Is this needed - vs creating a handler with `new InvocationHandler()`? The handler that does the rewrite is already public so it can be composed with more complex scenarios.

**Comment by mmisztal1980** [comment]
@rynowak in the current implementation the `InvocationHandler` is created inside the method, the caller does not really have an option to compose it.
```
 public static HttpClient CreateInvokeHttpClient(string appId = null, string daprEndpoint = null, string daprApiToken = null, HttpClientHandler handler = null)
{
            var internalHandler = new InvocationHandler()
            {
                InnerHandler = handler ?? new HttpClientHandler(),
                DaprApiToken = daprApiToken
            };
            // (...)
}
```

**Comment by rynowak** [comment]
Right, I'm trying to understand why more flavors of `CreateInvokeHttpClient﻿` offer something you can't do today. `InvocationHandler` is public - you are able to construct it and do whatever you like.

**Comment by mmisztal1980** [comment]
Right, since it's public instantiating your own HttpClient with pre-configured handler(s) is 100% legit, I'm actually inclined to say that this might be the recommended way to go, rather to use `DaprClient.CreateInvokeHttpClient`, however it isn't documented anywhere, and requires you to take a deep dive and read the sdk code :)
