### ISSUE TITLE
Why is DaprServiceCollectionExtensions a part of AspNetCore package

### ISSUE THREAD

**Issue by clintsinger** [dapr/dotnet-sdk#650]
I was wondering why the functionality from DaprServiceCollectionExtensions is in the AspNetCore package and not just in the Dapr.Client one?   I can't see why it has any dependencies on AspNetCore but seems to add value for those only looking to use the Client.

**Comment by rynowak** [comment]
So that we can avoid adding dependencies to `Dapr.Client`. From my experience working on the Microsoft.Extensions libraries, lots of people are passionate about having a small dependency list.

**Comment by clintsinger** [comment]
Got it.  Too bad, AddDaprClient seems like a good extension method for Dapr.Client... :)

**Comment by rynowak** [comment]
Yeah, it's also pretty minimal and easy to replicate. I don't think it's worth us producing an extra package for *just* that method. If more reasons come up in the future, or if M.E.DI moves in-band in .NET we'll consider it.
