### ISSUE TITLE
Google.Protobuf.InvalidProtocolBufferException in GrpcServiceSample

### ISSUE THREAD

**Issue by dabedin** [dapr/dotnet-sdk#653]
## Expected Behaviour
Locally launching the sample [GrpcServiceSample](https://github.com/dapr/dotnet-sdk/tree/master/examples/AspNetCore/GrpcServiceSample) with the `dapr run --app-id grpcsample --app-port 5050 --app-protocol grpc --dapr-http-port 5051 -- dotnet run` I should be able to reach the service via any Dapr sidecar.
For example:
```
POST http://localhost:5051/v1.0/invoke/grpcsample/method/deposit
Content-Type: application/json

{ "id": "17", "amount": 12 }
```
The invocation should reach the service method and process the req.

## Actual Behaviour
The request _v1.0/invoke/grpcsample/method/deposit_ reaches the method but I get a _Google.Protobuf.InvalidProtocolBufferException: Full type name for Transaction is Transaction; Any message's type url_ exception_ on the line `var transaction = request.Data.Unpack<GrpcServiceSample.Generated.Transaction>();`.
The detailed exception is the following:
```
Request starting HTTP/2 POST http://127.0.0.1:5050/dapr.proto.runtime.v1.AppCallback/OnInvoke application/grpc 
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
Executing endpoint 'gRPC - /dapr.proto.runtime.v1.AppCallback/OnInvoke' 
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
Error when executing service method 'OnInvoke'.
Google.Protobuf.InvalidProtocolBufferException: Full type name for Transaction is Transaction; Any message's type url is 
at Google.Protobuf.WellKnownTypes.Any.Unpack[T]()
at GrpcServiceSample.BankingService.OnInvoke(InvokeRequest request, ServerCallContext context) in C:\Repos\dotnet-sdk\examples\AspNetCore\GrpcServiceSample\Services\BankingService.cs:line 63
at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
Executed endpoint 'gRPC - /dapr.proto.runtime.v1.AppCallback/OnInvoke'
```
The request.Data is `{ "@type": "", "@value": "ew0KICAgICJpZCI6ICIxNyIsDQogICAgImFtb3VudCI6IDMNCn0=" }` with the base64 encoded representation of the JSON payload above.
Should I be able to reach the Dapr service method with a payload regardless of the way Dapr interact with the service, gRPC in this case? If expectation is correct, any idea on what could be going wrong?

**Comment by rynowak** [comment]
Hi @dabedin - there's nothing in Dapr that converts JSON requests to Protobuf. 

> Should I be able to reach the Dapr service method with a payload regardless of the way Dapr interact with the service, gRPC in this case?

You *are* reaching the Dapr service method. You can see that because the call stack includes `GrpcServiceSample.BankingService.OnInvoke`

The code in the GrpcServerSample expects a Protobuf message which is why this is failing. Please let me know if you think I'm missing something.

**Comment by dabedin** [comment]
My Q was not well written:  
> Should I be able to reach the Dapr service method with a payload **regardless of the way Dapr interact with the service**, gRPC in this case?

Yes, I get the exception on the line `var transaction = request.Data.Unpack<GrpcServiceSample.Generated.Transaction>(); ` at the reached method. 
Apparently I misunderstood the following cases, mutuating from  #https://github.com/dapr/dapr/issues/2342:

- case 1, caller app: http -> Dapr sidecar -- always grpc --> Dapr sidecar -> http -> called app
- case 4, caller app: http -> Dapr sidecar -- always grpc --> Dapr sidecar -> grpc -> called app

While both 1 and 4 are supported, in 4 the caller should be aware it does need to pass a protobuf payload, right?

**Comment by rynowak** [comment]
> While both 1 and 4 are supported, in 4 the caller should be aware it does need to pass a protobuf payload, right?

Yes, exactly. There are no restrictions inherent to Dapr regarding the format of an invoke method payload. The client and server need to agree on the format that's in use. 

To explain this a bit:

> Yes, I get the exception on the line var transaction = request.Data.Unpack<GrpcServiceSample.Generated.Transaction>(); at the reached method.

```C#
var transaction = request.Data.Unpack<GrpcServiceSample.Generated.Transaction>();
```

This line of code uses a Protobuf type (`Transaction`) and the Protobuf `.Unpack()` method to read the payload in the Protobuf binary format.

When you're receiving an invocation request as a Grpc server in Dapr, `.Data` is a property of type `Any` - this could contain a Protobuf message (example above), this could contain UTF-8 encoded JSON text, or it could contain any other format.

Its your responsibility to read the content according to what you expect.

If all of this sounds messy and confusing, I'd really suggest using HTTP as the protocol, JSON as the format and letting MVC model binding handle serialization.

**Comment by dabedin** [comment]
Agree, I do prefer HTTP + JSON.
The corresponding client for the gRCP + Protobuf service example [GrpcServiceSample ](https://github.com/dapr/dotnet-sdk/tree/master/examples/AspNetCore/GrpcServiceSample) is the [InvokeServiceGrpcExample](https://github.com/dapr/dotnet-sdk/blob/master/examples/Client/ServiceInvocation/InvokeServiceGrpcExample.cs), correct?

**Comment by rynowak** [comment]
yes, that should be right

**Comment by dabedin** [comment]
Thanks for clarifying the topic!
