### ISSUE TITLE
DAPR_API_TOKEN environment variable is not read correctly in 1.1.0

### ISSUE THREAD

**Issue by saber-wang** [dapr/dotnet-sdk#655]
https://github.com/dapr/dotnet-sdk/blob/5e5a42c96e5b6de1374d50432ae3b8442b908964/src/Shared/DaprDefaults.cs#L26

**Comment by a-elsheikh** [comment]
we've also just bumped into this one - fyi @rynowak

**Comment by rynowak** [comment]
Yes, we'll fix this and release a patch.

**Comment by rynowak** [comment]
Can you provide some more info here for testing? What's the actual problem you encountered (just looking for confirmation).

**Comment by saber-wang** [comment]
@rynowak  I just looked at the source code and found this problem

**Comment by a-elsheikh** [comment]
my specific scenario was initializing an ActorProxyFactory and using it to create an actor proxy, calls to the actor began throwing an AuthenticationException with message "Invalid client credentials". Stepping through the code led me to the line mentioned above

**Comment by rynowak** [comment]
Thanks @saber-wang and @a-elsheikh - I am able to confirm this is a bug. I also found an issue with propagating API tokens for the `CreateHttpMethodRequest` family of methods.

**Comment by rynowak** [comment]
We will fix this and release a `1.1.1` patch
