### ISSUE TITLE
Dapr pubsub using rabbitmq

### ISSUE THREAD

**Issue by satishviswanathan** [dapr/dotnet-sdk#659]
## Ask your question here
Getting the following error on subscriber side.

 level=warning msg="retriable error returned from app while processing pub/sub event 2d40b25c-0334-4201-a323-1ff51458faad: {\"error\": \"client error: the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection\"}

**pub sub component configuration**

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://guest:guest@localhost:5672/test"
  - name: durable
    value: "true"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "true"
  - name: deliveryMode
    value: "0"
  - name: requeueInFailure
    value: "true"
  - name: prefetchCount
    value: "0"
  - name: reconnectWait
    value: "0"
  - name: concurrencyMode
    value: parallel

**Subscription configuration**

apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  topic: Order
  route: /orderProcess
  pubsubname: pubsub
scopes:
- daprBackEndService
- daprService1

I'm pretty new on dapr and trying to get my first pub sub working using rabbitmq. Any help is appreciated.

**Comment by satishviswanathan** [comment]
Any help on this highly appreciated

**Comment by jbw** [comment]
Do you have a repo that reproduces this?

**Comment by rynowak** [comment]
Hi, I think you'll get a better response asking on the [Dapr Discord](https://discord.com/invite/ptHhX6jc34)

In general this looks like a connection issue with RabbitMQ - either it's not running or not reachable or port 5672. This isn't a .NET SDK problem and so this isn't the appropriate place to get help.

**Comment by senthomas** [comment]
If you leave the Configure for HTTPS checkbox checked when you created the Project, the generated ASP.NET Core API project includes middleware to redirect client requests to the HTTPS endpoint. 
This breaks communication between the Dapr sidecar and your application unless you explicitly configure the use of HTTPS when running your Dapr application. 
To enable the Dapr sidecar to communicate over HTTPS, include the **--app-ssl** flag in the Dapr command to start the application. 
Also specify the HTTPS port using the --app-port parameter. 

Using **--app-ssl** flag resolved the issue

**Comment by MatiKloster** [comment]
> If you leave the Configure for HTTPS checkbox checked when you created the Project, the generated ASP.NET Core API project includes middleware to redirect client requests to the HTTPS endpoint. This breaks communication between the Dapr sidecar and your application unless you explicitly configure the use of HTTPS when running your Dapr application. To enable the Dapr sidecar to communicate over HTTPS, include the **--app-ssl** flag in the Dapr command to start the application. Also specify the HTTPS port using the --app-port parameter.
> 
> Using **--app-ssl** flag resolved the issue

This worked for me! 
Thanks a lot!
