### ISSUE TITLE
Add support for actor reentrancy

### ISSUE THREAD

**Issue by halspang** [dapr/dotnet-sdk#661]
## Describe the feature
The dapr core runtime is planning on supporting actor reentrancy. The bulk of this logic will be handled in dapr's runtime but the SDK will be responsible for:

- Preserving the header `dapr-reentrant-id`
- Providing the new config fields required by `dapr/config`

For more context on actor reentrancy, the design proposal can be found here: [actor reentrancy](https://github.com/dapr/dapr/issues/2901)

## Release Note
RELEASE NOTE: **ADD** Support for actor reentrancy

**Comment by tomkerkhove** [comment]
Are there any docs on this? I'm probably looking over it.

**Comment by halspang** [comment]
Nothing SDK specific yet, but there's info on the feature itself.

https://docs.dapr.io/developing-applications/building-blocks/actors/actor-reentrancy/

**Comment by tomkerkhove** [comment]
I have found those.

So if we want to use it, we just have to use the host options?

**Comment by sregdorr** [comment]
Just curious... If I'm understanding the PR correctly, this is configured in the host options at the runtime level. Does that mean that you cant configure reentrancy at the actor level? Either all actors are reentrant, or none of them are?

**Comment by halspang** [comment]
Yes, you have to use the host options which means all actor types registered with those options are reentrant. We do not have the fine-grained settings for individual actor reentrancy. @sregdorr - What is your use case for having an individual actor be reentrant instead of the entire type?

**Comment by sregdorr** [comment]
Thanks for the info @halspang! I have an app that is currently utilizing dotnet Orleans and am interested in moving it to Dapr to allow for a polyglot system. I have a couple of grains (actors) whose sole purpose are simply to shuttle tasks to a set of other grains that actually do the legwork. For those shuttle grains, identity is not important and single-threaded operation is not desired. I always identify them with a `Guid.Empty` and In Orleans I can make them reentrant by setting the [Reentrant] attribute on the grain class. 

I do realize that this may be an anti-pattern with regard to the actor model however.  If I understand correctly, identity of an actor is pretty much the point! It seems that these shuttle grains might be better utilized as a simple gRPC service.

**Comment by halspang** [comment]
@sregdorr Gotcha, thanks for explaining your use case! 

If identity/single-threaded isn't required, could you just give them a unique ID? Instead of `Guid.Empty` do a `Guid.NewGuid`?

I think the alternate of making it a simple gRPC service is also a good idea. It's also worth noting that Dapr supports gRPC proxying now and we're working to add support for that in the .NET SDK as well. #741

**Comment by aktxyz** [comment]
any idea when the reentrancy support will make it into this sdk?

**Comment by halspang** [comment]
@aktxyz 

> any idea when the reentrancy support will make it into this sdk?

It's been in the sdk since 1.3. It's currently a preview feature in the runtime, though we're looking into seeing when we can take it out of the preview features.

**Comment by aktxyz** [comment]
> @aktxyz
> 
> > any idea when the reentrancy support will make it into this sdk?
> 
> It's been in the sdk since 1.3. It's currently a preview feature in the runtime, though we're looking into seeing when we can take it out of the preview features.

I did not realize that !  thanks

**Comment by rogerex** [comment]
in case anyone else is searching this, you need to setup in this way
```csharp
serviceCollection.SetupActors(options =>
            {
                options.ReentrancyConfig = new ActorReentrancyConfig()
                {
                    Enabled = true,
                    MaxStackDepth = 5,
                };
                // Your actors registration......
            });
```

**Comment by ardalis** [comment]
Is it still preview in 2023?
