### ISSUE TITLE
Remove or use unused constant ContentTypeApplicationJson [kind/tidyup]

### ISSUE THREAD

**Issue by jbw** [dapr/dotnet-sdk#663]
## Minor question while skimming the code to find out more about implementation

`ContentTypeApplicationJson ` in `Constants.cs` is unused and the only other reference to 'application/json' is in `DaprClientGrpc.cs`:

```cs
if (content != null)
{
    envelope.Data = content;
    envelope.DataContentType = "application/json";
}
```

Not sure if this part of the code should be using that constant or it can be removed.

**Comment by rynowak** [comment]
If you're interested in this feel free to send a PR. IMO the best fix here is to use https://docs.microsoft.com/en-us/dotnet/api/system.net.mime.mediatypenames.application.json?view=net-5.0

This is minor code cleanup, so if you're interested feel free.
