### ISSUE TITLE
Simplify dapr grpc service development with a default implementation of AppCallback

### ISSUE THREAD

**Issue by heavenwing** [dapr/dotnet-sdk#669]
## Purpose

Provide a default implementation of AppCallback to developer, they just writes public methods of business logic, don't care about below AppCallback interfaces:

- OnInvoke
- ListTopicSubscriptions
- OnTopicEvent
- ListInputBindings
- OnBindingEvent

Use below code snippet to register default AppCallback implementation:

```csharp
endpoints.MapAppCallback();
```
Provide a base grpc service of Dapr, developer write derived class to contains real business logic. This base class also use for service collection extension method to register the grpc service. For example:

```csharp
services.AddDaprGrpcService<BankingService2>();
```

Whole feature consist of 3 milestones to implement:

1. Support Service Invocation and PubSub with DaprClient injection
2. Support Binding
3. Enhance Service Invocation with State injection

I will add milestone PR into this Proposal issue subsequently.

**Comment by rynowak** [comment]
Hi @heavenwing - this is not something we plan to add to the Dapr .NET SDK. There's a plan underway to make gRPC for Dapr in general work similarly to the standard gRPC programming experience. https://github.com/dapr/dapr/issues/3231

When this is done, service invocation for gRPC will be authored like any other gRPC client/server and not use app callback.

If you are passionate about writing a dispatching framework, I'd suggest publishing it as your own project. Writing a new programming model is a huge job in terms of testing and documentation. We don't plan to add new frameworks or programming models to the Dapr .NET SDK.

**Comment by rynowak** [comment]
Closing this as we have no plans to add a framework inside the Dapr .NET SDk. gRPC proxying for service invocation is in Dapr 1.3. I would recommend everyone use that.
