### ISSUE TITLE
Add support to provide Actor TypeName during runtime at startup.

### ISSUE THREAD

**Issue by bjorkstromm** [dapr/dotnet-sdk#677]
## Describe the proposal

Currently, since Actor Placement Service is global within the Kubernetes cluster, it makes it difficult to run multiple versions (e.g. DEV and TEST) of the application within the same cluster. This is due to the fact that Actor names are either automatically assigned from the name of the implementing class or by using the `ActorAttribute` and specifying the `TypeName` property. Bot of these approaches are compile-time constants which can't be adjusted during runtime.

Here's two proposals:

1. Make it possible to resolve Actor TypeName from an environment variable when specified in the `ActorAttribute`. This is e.g. possible in Azure Functions with most of the attributes there. This would allow us to use the attribute as follows:
   ```csharp
   [Actor(TypeName = "%MyActorName%")]
   public class MyActorName : Dapr.Actors.Runtime.Actor, IMyActor
   {
   }
   ```
   The `%MyActorName%` can then be resolved from an environment variable using e.g. [Environment.ExpandEnvironmentVariables](https://docs.microsoft.com/en-us/dotnet/api/system.environment.expandenvironmentvariables?view=net-5.0), or using a more sophisticated approach as Azure Functions SDK (see [NameResolverExtensions.cs](https://github.com/Azure/azure-webjobs-sdk/blob/892f6278f449c468391ce76aa086cf78aa065a5f/src/Microsoft.Azure.WebJobs.Host/NameResolverExtensions.cs#L39)).

2. Make it possible to provide ActorTypeName when calling `RegisterActor<T>()` on the `ActorRegistrationCollection`. This would currently be possible if `ActorTypeName` on `ActorTypeInformation` wasn't readonly. (I do it today using reflection :)). Propsal here is to add a overload to `RegisterActor<T>()` which takes a `string` parameter for the Actor TypeName.

**Comment by rynowak** [comment]
I'd prefer approach 2 - the functions approach would be surprising, given that nothing else we do works that way. 

Feel free to send a PR for option 2 :)

**Comment by bjorkstromm** [comment]
@rynowak consider it done!

Regarding Approach 1, I actually wanted this also for the `TopicAttribute`. See https://github.com/dapr/dotnet-sdk/issues/678. Don't really know what the best approach would be there (beside the Azure Function approach). But, but... Let's continue that discussion on that issue.

**Comment by devlead** [comment]
Must say I really like option one, would make it really straightforward to have the same set of "artifacts" flow and be reused through environments.
