### ISSUE TITLE
Add support to provide Pubsub (and Topic) during runtime at startup for controller methods.

### ISSUE THREAD

**Issue by bjorkstromm** [dapr/dotnet-sdk#678]
## Describe the proposal

Pubsub name might not be known at compile time, so it would be reasonable to have an approach to specify it during runtime at startup. It's currently possible if mapping endpoints directly (https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.AspNetCore/DaprEndpointConventionBuilderExtensions.cs), but not possible for methods within a controller.

My proposal is to make it possible to resolve Pubsub (and Topic) from an environment variable when specified in the `TopicAttribute`. This is e.g. possible in Azure Functions with most of the attributes there. This would allow us to use the attribute as follows:
```csharp
[Topic("%MyPubSub%", "%MyTopic%")]
[HttpPost("onEvent")]
public async Task<IActionResult> OnEvent([FromBody] Event data)
{
}
```

`%MyPubSub%` and `%MyTopic%` can then be resolved from an environment variable using e.g. [Environment.ExpandEnvironmentVariables](https://docs.microsoft.com/en-us/dotnet/api/system.environment.expandenvironmentvariables?view=net-5.0), or using a more sophisticated approach as Azure Functions SDK (see [NameResolverExtensions.cs](https://github.com/Azure/azure-webjobs-sdk/blob/892f6278f449c468391ce76aa086cf78aa065a5f/src/Microsoft.Azure.WebJobs.Host/NameResolverExtensions.cs#L39)).

Another approach would be to add an overload to `MapSubscribeHandler` to somehow override the values specified in `TopicAttribute`. Don't know what the best approach would be here yet... Currently, to workaround this, I've just created my own 
`MapSubscribeHandler` which takes a `string` parameter for overriding the PubSub name.

**Comment by rynowak** [comment]
Here's what I'd suggest - lets add an interface like the following:

```cs
public interface ITopicMetadata
{
        string Name { get; }

        string PubsubName { get; }
}
```

Then implement this interface on `TopicAttribute`. 

The replace all of the consumption of `TopicAttribute` with `ITopicMetadata` inside the framework.

This technique is one I've used before in MVC and it's very flexible. Users can implement their own dynamic logic however they like. So if you like the env-var convention that functions uses, then you can use that.

**Comment by bjorkstromm** [comment]
@rynowak Sounds like a plan! I can send a PR for this.

Without knowing that much about MVC and  endpoint metadata, how are users supposed to extend this then? One obvious way is to implement a custom attribute (which implements the `ITopicMetadata` interface) and handle the logic there.

Are there other ways of adding metadata to endpoints within a controller? A quick google didn't yield much info about this topic.

**Comment by sapinderpalsingh** [comment]
There is already an extension method `WithThopic` provided on `IEndpointConventionBuilder`, which you can use with your MapControllerRoute method.

example:
```
app.UseEndpoints(endpoints =>
            {
                endpoints.MapSubscribeHandler();
                endpoints.MapControllerRoute("default", "/subscribe").WithTopic(eventhubSettings.PubsubName, eventhubSettings.TopicName);
                
            });
```

**Comment by rynowak** [comment]
> One obvious way is to implement a custom attribute (which implements the ITopicMetadata interface) and handle the logic there.

Yes. This is the pretty simple case. You get to write custom code to compute the topic name based on whatever inputs you like, as long as they are available from statics + attribute constructor.

These are useful because you can build your own conventions, or consider extra data sources like env-vars.

> Are there other ways of adding metadata to endpoints within a controller? A quick google didn't yield much info about this topic.

Yes, you can do this via [application model](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-5.0) and write your own code to configure the model. 

The reason I like the attribute-based approach is that it's pretty easy to understand. Technically it doesn't enable anything that new that's impossible today. 

Application model on the other hand is somewhat involved to understand and work with.

**Comment by andreatosato** [comment]
I create my TopicEnvAttribute and pass environment variable to ctor
