### ISSUE TITLE
Create functionality which eases securing application using Dapr-Api-Token

### ISSUE THREAD

**Issue by bjorkstromm** [dapr/dotnet-sdk#682]
## Describe the proposal

When reserching guidance for securing PUBSUB, https://github.com/dapr/dapr/issues/3178 I found out that we can instruct Dapr to send a `Dapr-Api-Token` header with each request when communication with the app.

I noticed there are no convenience methods in the .NET SDK for e.g. securing pubsub endpoints using this. What I did instead was to create a simple `AuthenticationHandler` which reads the `Dapr-Api-Token` header and matches it against a pre-configured value (in my case, the `DAPR_API_TOKEN` environment variable).

I'd suggest we'd add something to the .NET SDK for easily securing endpoints that Dapr will communicate with. I'm far from a ASP.NET Core expert, so if @rynowak could chime in with any suggestions I'm all ears. The custom `AuthenticationHandler` is a simple solution, but if you'd like to create something around already existing middleware we could do that as well.

**Comment by rynowak** [comment]
This is something we'd like to have as an option. I think can AuthenticationHandler is the right starting point but I want to confirm a few things.

@tratcher @davidfowl - does an AuthenticationHandler do anything on its own? Would we need an authentication handler + an authorization policy?

The scenario is being able to secure per-endpoint whether the traffic comes from the Dapr sidecar or from another source. Dapr already has a shared-secret header-based mechanism for this, and we want to wire it up to ASP.NET Core.

**Comment by Tratcher** [comment]
That would require an AuthenticationHandler to read/verify the token and an authorization policy on the affected endpoints to reference the handler.

**Comment by Tratcher** [comment]
Your policy may be as simple as: `[Authorize("Dapr")]`, where "Dapr" is the auth scheme name for your auth handler.

**Comment by rynowak** [comment]
@Tratcher - that's what I was hoping the answer was.

**Comment by bjorkstromm** [comment]
> Your policy may be as simple as: `[Authorize("Dapr")]`, where "Dapr" is the auth scheme name for your auth handler.

Yup, this is basically what I've done in my project. Would be happy to send a PR for the AuthenticationHandler.
