### ISSUE TITLE
Dapr initialisation check.

### ISSUE THREAD

**Issue by Jossec101** [dapr/dotnet-sdk#692]
## Describe the proposal

In our case, we need to do some calls on application start, and we identified that we were locking app port HTTP 80 and DAPR was not being initialised. I didn't find a way to check when is the dapr sidecar initialised. It would be a nice idea to provide a boolean property or even a method to check when is the sidecar initialised and ready for receiving requests.

Thanks for this great runtime!

**Comment by rynowak** [comment]
We have this actually. You can use `DaprClient.CheckHealthAsync()` 

See: https://github.com/dapr/dotnet-sdk/commit/2ddb4bb7e059a28a3bb326e5c0b1cf36dd9b6bd3
