### ISSUE TITLE
Support .net 6 preview 4 new Minimal APIs

### ISSUE THREAD

**Issue by doddgu** [dapr/dotnet-sdk#695]
Hi, is there anyone working on Minimal APIs support?

**Comment by doddgu** [comment]
Maybe adding extensions for IEndpointRouteBuilder will work?

**Comment by doddgu** [comment]
in DaprEndpointRouteBuilderExtensions.cs
I added an extension method. It's looks like worked, but I only test invocation.
```csharp
        /// <summary>
        /// Adds Dapr integration for Minimal APIs to the provided <see cref="IEndpointRouteBuilder" />.
        /// </summary>
        /// <param name="builder">The <see cref="IEndpointRouteBuilder" />.</param>
        /// <param name="services">The <see cref="IServiceCollection" />.</param>
        /// <param name="configureClient">The (optional) <see cref="DaprClientBuilder" /> to use for configuring the DaprClient.</param>
        /// <returns>The <see cref="IEndpointRouteBuilder" /> builder.</returns>
        public static IEndpointRouteBuilder AddDapr(this IEndpointRouteBuilder builder, IServiceCollection services, Action<DaprClientBuilder> configureClient = null)
        {
            if (builder is null)
            {
                throw new ArgumentNullException(nameof(builder));
            }

            // This pattern prevents registering services multiple times in the case AddDapr is called
            // by non-user-code.
            if (services.Any(s => s.ImplementationType == typeof(DaprMinimalApisMarkerService)))
            {
                return builder;
            }

            services.AddDaprClient(configureClient);

            services.AddSingleton<DaprMinimalApisMarkerService>();
            services.AddSingleton<IApplicationModelProvider, StateEntryApplicationModelProvider>();
            services.Configure<MvcOptions>(options =>
            {
                options.ModelBinderProviders.Insert(0, new StateEntryModelBinderProvider());
            });

            return builder;
        }
```

**Comment by doddgu** [comment]
We found sub isn't support too.

**Comment by doddgu** [comment]
I found another exception, result in the actor function does not work.
see #https://github.com/dotnet/aspnetcore/issues/33964

And MapActorsHandlers function throw exception too.
Because endpoints.ServiceProvider.GetService<ActorRuntime>() return null. I change it to builder.Services.BuildServiceProvider().GetService<ActorRuntime>() , it's working, but health check broken down.

**Comment by davidfowl** [comment]
Explicit support shouldn't need to be added for minimal APIs. There are a few things decoupled from MVC won't be supported:
- There's no support for custom model binders (so the FromState attribute won't work). StateEntry\<T\> won't work either.
- AddDapr currently hangs off IMvcBuilder, but it does some other non-MVC specific work (like adding the DaprClient). This means to use it with minimal APIs you might have to call AddDaprClient explicitly. This doesn't seem like a big deal.

You'll want to get @rynowak to guide here as he's well versed in this part of the stack. My current take is that not much needs to be done.

**Comment by doddgu** [comment]
> Explicit support shouldn't need to be added for minimal APIs. There are a few things decoupled from MVC won't be supported:
> 
> * There's no support for custom model binders (so the FromState attribute won't work). StateEntry<T> won't work either.
> * AddDapr currently hangs off IMvcBuilder, but it does some other non-MVC specific work (like adding the DaprClient). This means to use it with minimal APIs you might have to call AddDaprClient explicitly. This doesn't seem like a big deal.
> 
> You'll want to get @rynowak to guide here as he's well versed in this part of the stack. My current take is that not much needs to be done.

I think this can be a feature. Because support ModelBinderProvider was moved to feature at aspnetcore.
https://github.com/dotnet/aspnetcore/issues/33955

If you decide not to support it, can you make a guide for Minimal APIs working. I don't have to use FromState, but the actor is not working( #705 ).

**Comment by davidfowl** [comment]
I don’t know what doesn’t work beyond the StateEntry and the FromState attributes

**Comment by rynowak** [comment]
Hi @doddgu - sorry I'm showing up late here... 

Can you explain what the things are that are not working or missing? I don't expect Minimal APIs support to require work from the Dapr SDK. 

For example it is expected that `[FromState]` does not work. `[FromState]` is an MVC feature and MVC is not part of minimal APIs. What else?

**Comment by doddgu** [comment]
#713 and #711  can fix actor not working on Minimal APIs, but that is preview 4 and 5. I will try it again on .net 6 preview 7 without #713 .

**Comment by doddgu** [comment]
Hi @rynowak 
I can't try it, because #https://github.com/dotnet/aspnetcore/issues/35285

**Comment by doddgu** [comment]
I used self hosted, and get a new exception

```
Dapr:DaprApiException:"error invoke actor method: error finding address for actor type BankActor with id 993eb0a7-d82a-419f-828d-cb60d99f6c87"
```

client daprd log
```
time="2021-08-18T10:29:30.3976376+08:00" level=error msg="app returned http status code 500 from subscription endpoint" app_id=xxx instance=yyy scope=dapr.runtime type=log ver=1.3.0
```

service daprd log
```
time="2021-08-18T10:29:35.6048172+08:00" level=error msg="error getting topics from app: unexpected end of JSON input" app_id=aaa instance=bbb scope=dapr.runtime type=log ver=1.3.0
```

**Comment by doddgu** [comment]
I found /dapr/config response is empty.

**Comment by doddgu** [comment]
In the method Dapr.Actors.ActorRuntime.SerializeSettingsAndRegisteredTypes, it needs to build json into response, but Flush is not work.

**Comment by doddgu** [comment]
I use MemoryStream, I get the json.

**Comment by doddgu** [comment]
Hi @rynowak 
I solved the problem, because ```context.Response.BodyWriter``` need to call FlushAsync, I don't know why, but add this ,it works.
```
private static IEndpointConventionBuilder MapDaprConfigEndpoint(this IEndpointRouteBuilder endpoints, IServiceProvider serviceProvider)
        {
            var runtime = serviceProvider.GetRequiredService<ActorRuntime>();
            return endpoints.MapGet("dapr/config", async context =>
            {
                context.Response.ContentType = "application/json";
                await runtime.SerializeSettingsAndRegisteredTypes(context.Response.BodyWriter);
                await context.Response.BodyWriter.FlushAsync(); // this is my add
            }).WithDisplayName(b => "Dapr Actors Config");
        }
```

**Comment by doddgu** [comment]
I started a pr, please review.

**Comment by davidfowl** [comment]
Yes this looks like legitimate bug.

**Comment by rynowak** [comment]
Thanks @doddgu
