### ISSUE TITLE
Response.BodyWriter on Net6.0  Required Call  CompleteAsync()?

### ISSUE THREAD

**Issue by saber-wang** [dapr/dotnet-sdk#704]
## Describe the proposal
https://github.com/dapr/dotnet-sdk/blob/a65e8b287d4c48f93952221cb1c6a1b1346ece26/src/Dapr.AspNetCore/DaprEndpointRouteBuilderExtensions.cs#L47

If no call  CompleteAsync(), there is no output

![image](https://user-images.githubusercontent.com/45062099/124051943-07eacf80-da50-11eb-8ac5-337b6f925ea6.png)

**Comment by rynowak** [comment]
This has been fixed.
