### ISSUE TITLE
Call actor throw InvalidProgamException

### ISSUE THREAD

**Issue by doddgu** [dapr/dotnet-sdk#705]
## Expected Behavior

Call actor success.

## Actual Behavior

![image](https://user-images.githubusercontent.com/7299249/124070536-8ce5e100-da70-11eb-992e-59febca6536c.png)

## Steps to Reproduce the Problem

Use Minimal APIs.
.Net 6 preview 5
OS: Win 11
IDE: VS 2022 Preview

Github Repo: https://github.com/doddgu/MinimalApiActor.git
Steps: 
1. Run docker compose.
2. Visit https://localhost:8002
3. Click the "Test Actor" button.
Original Exception: The reason is when using MinimalApi, MapActorsHandlers method is using endpoints.ServiceProvider. The ServiceProvider can not get the service.
![image](https://user-images.githubusercontent.com/7299249/124410619-7516a180-dd7d-11eb-8d4d-7beb779ddf5c.png)

Now Exception: I try to add extension, please see #695 , I resolve with builder.Services. But, it throw another InvalidProgramException.

## Release Note

RELEASE NOTE:

**Comment by davidfowl** [comment]
Steps to reproduce the problem are missing…

**Comment by doddgu** [comment]
## Steps to Reproduce the Problem：
Github Repo: https://github.com/doddgu/MinimalApiActor.git
Original Exception: The reason is when using MinimalApi, MapActorsHandlers method is using endpoints.ServiceProvider. The ServiceProvider can not get the service.
![image](https://user-images.githubusercontent.com/7299249/124410619-7516a180-dd7d-11eb-8d4d-7beb779ddf5c.png)
Now Exception: I try to add extension, please see #695 , I resolve with builder.Services. But, it throw another exception in the topic.

**Comment by doddgu** [comment]
Based on web api, it's success.
