### ISSUE TITLE
Unable to read message from queue in back ground service 

### ISSUE THREAD

**Issue by VenkateshSrini** [dapr/dotnet-sdk#714]
Hi All,

Is there some guidance available to read a published message from Dapr in Rabbit MQ to be read from Subscriber that is not an ASP.NET core application. Basically, I would like to read a message from back ground service application. Now I do not find a way to do the same without HttpRequest object

**Comment by rynowak** [comment]
Hi @VenkateshSrini - Dapr PubSub operates over an HTTP/gRPC interface. We don't provide a way for your to poll for messages currently. You could use the RabbitMQ SDK for this and a [worker service](https://docs.microsoft.com/en-us/dotnet/core/extensions/workers)

**Comment by VenkateshSrini** [comment]
@rynowak ,
Then how would I work on .NET core BackGround Services
