### ISSUE TITLE
Pub/Sub wildcard Topic.* subscriptions do not receive messages

### ISSUE THREAD

**Issue by theperm** [dapr/dotnet-sdk#725]
## Expected Behavior

Subscribing to my User.* should receive a message sent to User.1

## Actual Behavior

Nothing is happening and no errors can be seen anywhere. 

I've went through the pub sub troubleshooter and the subscription and route do exist in dapr, just the published messages dont get to the handler
If i remove the wildcard from subscription and publish to a single User topic then it works as expected.

The application API controller has a handler to receive messages from the topic.
The web application also host actors. The idea is to take messages from pubsub and pass them to the actors host in the same service
Message on topic User.1 calls a handler on the User actor 1

## Steps to Reproduce the Problem

Create a .net controller with a handler like this
`
        [HttpPost("User")]
        [Topic(DaprPubSubName, "User.*")]
        public async Task<ActionResult<string>> User(Data dataEvent)
        {
            _logger.LogInformation("Handling data for User {0}", dataEvent.UserId);
            var proxy = ActorProxyFactory.CreateActor<IUserActor>(dataEvent.User, "User", "UserActor");
            await proxy.SetUserDataAsync(dataEvent);
`

The controller startup.cs is
`
 public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddActors(options =>
            {
                // Register actor types and configure actor settings
                options.Actors.RegisterActor<User>();
            });
            services.AddControllers().AddDapr();

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "UserActorService", Version = "v1" });
            });

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "UserActorService v1"));

            }
            app.UseRouting();
            app.UseCloudEvents();
            app.UseEndpoints(endpoints =>
            {
                // Register actors handlers that interface with the Dapr runtime.
                endpoints.MapActorsHandlers();
                endpoints.MapSubscribeHandler();
                endpoints.MapControllers();
            });
        }
    }
`
Next Publish message to topic User.1
In my case i had an actor host in a different service where i did the following

`await Client.PublishEventAsync(pubsubName, $"User.{user}", Data.Create());`

## Release Note

RELEASE NOTE:

**Comment by fbridger** [comment]
@theperm Is this something currently supported by Dapr? I cannot find documentation related to this use case.

**Comment by theperm** [comment]
It is supposed to be supported, see 
https://github.com/dapr/dapr/issues/1786 and 
https://github.com/dapr/dapr/issues/814

**Comment by halspang** [comment]
@theperm - I'm not sure that those issues actually added the functionality. Especially the dynamic subscription one as I don't see a linked PR. For the wildcard subscriptions, I'm also not sure how they would've functioned with the linked PRs in there. Maybe it's a per technology thing?

Regardless, I've tried to rework the pubsub quickstart which uses node/python and neither of them seem to work for a wildcard either. So I don't think this is a .NET issue but rather something that still isn't implemented or is reliant on the component.

For more thorough testing from my part, what component are you using?

**Comment by theperm** [comment]
I've only used the Redis pub sub component to test this. I'm s little confused as to what those PRs added as it was claimed by someone on discord it was wild card subscriptions.

**Comment by halspang** [comment]
@theperm - Circling back here, I think this is a runtime feature more than anything else. I'd recommend opening an issue there if you want this feature. I'm going to close this issue for that one but feel free to reopen if you think it belongs here/want to continue the discussion.
