### ISSUE TITLE
Expose HttpClient on ActorProxy

### ISSUE THREAD

**Issue by clintsinger** [dapr/dotnet-sdk#728]
The `ActorProxy` doesn't allow access to the `HttpClient`.   This is useful so that one would be able to add additional configuration such as being able to define the `HttpClient.Timeout`.   

As an example use case, being able to set the `Timeout` to `InfiniteTimespan`  when doing service debugging would help in scenarios when stepping through the code takes longer than the default timeout.

**Comment by doddgu** [comment]
I agree, I think it could be more open.  For example, response processing.
The scene is I want throw user friendly exception in actor, and I don't want to cover it with error code and error message in response.

client
```csharp
var balance = await bank.GetAccountBalance();
```
client side global exception catch
```csharp
ActorProxy.ResponseProcessing = (resp, e) =>
{
     if (resp.StatusCode == 299)
    {
        // to do something
        e.Handle = true;  // dapr actor 
    }
};
```

actor method, global exception catch will catch the user friendly exception and set status code = 299, response body is "Just Test".
```csharp
public async Task<AccountBalance> GetAccountBalance()
{
    throw new UserFriendlyException("Just Test");
}
```
----
Now, my solution is
Common actor response
```csharp
public class ActorResponse<T> where T : class
{
    public int ErrorCode { get; set; }
    public string ErrorMessage { get; set; }
    public T Result { get; set; }
}
```
client
```csharp
var balanceResponse = await bank.GetAccountBalance();
if (balanceResponse.ErrorCode == 200)
{
    // to do something
}
else if(balanceResponse.ErrorCode == 299)
{
    throw new UserFriendlyException(balanceResponse.ErrorMessage);
}
else
{
    throw new Exception(balanceResponse.ErrorMessage);
}
```
actor method
```csharp
public async Task<ActorResponse<AccountBalance>> GetAccountBalance()
{
    return new ActorResponse()
    {
        ErrorCode = 299,
        ErrorMessage = "JustTest",
    }
}
```
----
It's too complicated. I think c# could be a little more elegant.
