### ISSUE TITLE
Raspberry Pi4 build issue

### ISSUE THREAD

**Issue by dwhiteddsoft** [dapr/dotnet-sdk#729]
## Expected Behavior

I wanted to run the GRPC subscriber sample on the Raspberry Pi. Simply did a dotnet build to obtain the error

## Actual Behavior

dotnet build produces this error:
/home/pi/.nuget/packages/grpc.tools/2.32.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Google.Protobuf.Tools cannot determine host OS and CPU. [/home/pi/dapr-throughput/dotnet-sdk/src/Dapr.Client/Dapr.Client.csproj]
/home/pi/.nuget/packages/grpc.tools/2.32.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Use environment variables PROTOBUF_TOOLS_OS={linux|macosx|windows} and PROTOBUF_TOOLS_CPU={x86|x64} to try the closest match to your system. [/home/pi/dapr-throughput/dotnet-sdk/src/Dapr.Client/Dapr.Client.csproj]
/home/pi/.nuget/packages/grpc.tools/2.32.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : You may also set PROTOBUF_PROTOC to specify full path to the host-provided compiler (v3.5+ is required). [/home/pi/dapr-throughput/dotnet-sdk/src/Dapr.Client/Dapr.Client.csproj]

Build FAILED.

/home/pi/.nuget/packages/grpc.tools/2.32.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Google.Protobuf.Tools cannot determine host OS and CPU. [/home/pi/dapr-throughput/dotnet-sdk/src/Dapr.Client/Dapr.Client.csproj]
/home/pi/.nuget/packages/grpc.tools/2.32.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Use environment variables PROTOBUF_TOOLS_OS={linux|macosx|windows} and PROTOBUF_TOOLS_CPU={x86|x64} to try the closest match to your system. [/home/pi/dapr-throughput/dotnet-sdk/src/Dapr.Client/Dapr.Client.csproj]
/home/pi/.nuget/packages/grpc.tools/2.32.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : You may also set PROTOBUF_PROTOC to specify full path to the host-provided compiler (v3.5+ is required). [/home/pi/dapr-throughput/dotnet-sdk/src/Dapr.Client/Dapr.Client.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:21.62

## Steps to Reproduce the Problem

- git clone repo
- dotnet build

## System Info

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /opt/dotnet/sdk/5.0.302/

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  5.0.302 [/opt/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.8 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.8 [/opt/dotnet/shared/Microsoft.NETCore.App]

protoc --version
libprotoc 3.6.1

Environment variables set after compile errors (results were the same)
PROTOBUF_TOOLS_OS=linux
PROTOBUF_TOOLS_CPU=arm64
PROTOBUF_PROTOC=/usr/bin/protoc

**Comment by wcs1only** [comment]
Fix for this is likely to update to Grpc.Tools 2.38.1, which includes support for arm64 according to: https://grpc.io/blog/grpc-on-arm64/#overview-of-grpc-and-protobuf-support-on-arm64-linux

**Comment by dwhiteddsoft** [comment]
This only works for arm64 and not for armv7. Closing as the fix above does fix for arm64. If anyone finds this, you are out of luck on armv7 (standard Pi4 distribution)
