### ISSUE TITLE
Prefix the request Uri

### ISSUE THREAD

**Issue by farhadnowzari** [dapr/dotnet-sdk#742]
https://github.com/dapr/dotnet-sdk/blob/9104c6624cc474e52717ddb7408a75449b071a02/src/Dapr.Client/InvocationHandler.cs#L112

In the above method, it could be cool on creating the httpClient the UriBuilder's path could have a prefix before right side of the assignment for the path.
in our case I have configured a sidecard for `CamundaPlatform` and there is a camunda client library available for dotnet.
To access CamundaPlatform you need to do this `http://HOST_ADDRESS/engine-rest` but now the sidecar doesn't know about `/engine-rest` so the dapr-sdk sends the request like this `http://DAPR_ENDPOINT/v1.0/invoke/APP_ID/method/messages` for example and it should send it like this `http://DAPR_ENDPOINT/v1.0/invoke/APP_ID/method/engine-rest/messages`.

I would be happy to make a pull request and add this optional prefix while creating the InvokeHandler :)

Regards,
Farhad

**Comment by farhadnowzari** [comment]
**Update**
Ok I managed to do it with adding the InvocationHandler as an InnerHandler to a custom Handler I wrote.
But the issue is on building the InvocationHandler from my code I cannot set the DaprApiToken myself because it is internal.

I will look more into it. For now, for the purpose of testing it works.

**Comment by rynowak** [comment]
Hi @farhadnowzari - thanks for filing this issue. Can you explain more about what you're to achieve? I see a lot of technical details but I don't really understand what it is you're trying to do.

**Comment by farhadnowzari** [comment]
Hi, thanks for your reply 😊

We have an external service in our case Camunda platform which we could create a binding/middleware for but since the bindings/middlewares are in goLang and we currently didn't have much time we created a sidecar for it so the sidecar can handle the requests with method invocation instead of accessing this service directly.
But Camunda runs on the following address `scheme://hostname/engine-rest`. When we add the sidecar for Camunda the `engine-rest` part will be a part of the method. We are using another third party library for Camunda in dotnet which expects the httpclient passed to it for building the service already contain the `engine-rest` in the `BaseAddress` but the httpclient which is created by `DaprClient` is like this `scheme://daprEndpoint:3500/v1.0/invoke/Camunda/method` so when the other library sends a request it will be like this `scheme://daprEndpoint:3500/v1.0/invoke/Camunda/method/external-tasks/fetchAndLock` and it should be like this `scheme://daprEndpoint:3500/v1.0/invoke/Camunda/method/engine-rest/external-tasks/fetchAndLock`
To be honest the other third party library should've support this so it prefixes the endpoints with `engine-rest` but they are using refit and it is not an option there (as I asked them).
So for now as a workaround I created a `DelegatingHandler` and suffixing the path with `engine-rest` and adding the `InvocationHandler` from dapr as an InnerHandler to this custom handler but it's a bad practice because I saw that invocation handler also takes care of API token setting internally and with my implementation I cannot set it.

What do you think? 🤔
