### ISSUE TITLE
is there a way to specify TTL when publishing an event?

### ISSUE THREAD

**Issue by aktxyz** [dapr/dotnet-sdk#750]

**Comment by allantargino** [comment]
Yes @aktxyz:

```cs
...

var metadata = new Dictionary<string, string>()
{
    { "ttlInSeconds", "120" },
};

dapr.PublishEventAsync(pubsubName, topicName, data, metadata);
```

**Comment by aktxyz** [comment]
thanks !   the only place the string ttl or ttlinseconds shows up is in a proto file, would be a good add to any docs :)

thanks for the help !

https://github.com/dapr/dotnet-sdk/search?q=ttl
https://github.com/dapr/dotnet-sdk/search?q=ttlinseconds

**Comment by aktxyz** [comment]
this works great by the way ... thanks !
