### ISSUE TITLE
Actor state can't be reset in case of any exception in the user code.

### ISSUE THREAD

**Issue by mtaghavi2005** [dapr/dotnet-sdk#762]
## Expected Behavior
According to what is documented in the source code (Actor.cs), in time of execution of an actor method, if user code throws any exception, all the state changes in the state manager should not be saved.

https://github.com/dapr/dotnet-sdk/blob/75bdb8ce2fa73bcd425743b13013b83677726370/src/Dapr.Actors/Runtime/Actor.cs#L97
![image](https://user-images.githubusercontent.com/1976118/136043080-3812d56e-6551-47b5-a692-11d8f383726c.png)

## Actual Behavior

Actor saves all state changes, regardless of whether there is any exception in the user code or not.

## Steps to Reproduce the Problem

After calling the following Actor Method, the state will be saved in the actor state storage. 

```
        public async Task DoSomeTask()
        {
            await StateManager.SetStateAsync("TestState", "Some Value");

            throw new Exception("Something went wrong!");
        }
```

**Comment by fabistb** [comment]
@msfussell can you please add this issue to our project?

**Comment by halspang** [comment]
Took a look into this and was able to repro it. I'll work on a fix.
