### ISSUE TITLE
Actor: Get existing reminder by name

### ISSUE THREAD

**Issue by ssm3ll** [dapr/dotnet-sdk#772]
## Expected Behavior

As per official documentation https://docs.dapr.io/reference/api/actors_api/#get-actor-reminder it is possible to get existing reminder by its name. So Actor should contain method GetReminderAsync(string reminderName) to get existing reminder, that has been previously created using RegisterReminderAsync (string reminderName, byte[] state, TimeSpan dueTime, TimeSpan period) method

## Actual Behavior

Currently it's only possible to register or unregister reminder

## Steps to Reproduce the Problem

Nor Actor neither DaprHttpInteractor contain method to get existing actor reminder by it's name

**Comment by rynowak** [comment]
Hi @ssm3ll,

You're right that we don't surface this through the Actors SDK. Do you have a use case in mind here? What do you plan to do with the data you will get? 

That information will help us prioritize this as well as determine how it should be designed.

**Comment by tstojecki** [comment]
In the absence of this, is there any downside to registering a reminder with the same name with each request in a controller? We have a service that uses an actor to get/set state and want to have one instance of a reminder running at all times.

**Comment by fabistb** [comment]
@halspang Is it possible to surface this api via the SDK?
Based on my tests the reminder API behavior changes when reminder partitioning is activated.

If reminder partitioning isn't activate _UnregisterReminder()_ returns 200 even if no reminder is currently active.
This makes it possible to call the method in an optimistic if it isn't clear if a reminder is currently active or not.

However if reminder partitioning is activate _UnregisterReminder()_ returns 500 if no reminder is currently active.
With this change the best way is probably to call the _Get actor reminder_ api validate the response and only if a reminder is active utilize the _UnregisterReminder()_ method. So it would be helpful if the _Get actor reminder_ api could also be surfaced via sdk.

**Comment by shivamkm07** [comment]
@halspang This issue can be closed now.

**Comment by fabistb** [comment]
@shivamkm07 thank you very much!
Just tried it and returned all the information I'm interested in.

**Comment by ssm3ll** [comment]
> @fabistb @ssm3ll Get Actor Reminder API has been added in Dotnet sdk in 1.11. `GetActorReminder` returns `IActorReminder` Object if the reminder exists, otherwise null. Feel free to try this and let us know in case of any issues. P.S. I will be creating Docs PR soon for the change.

thank you. it works

**Comment by olitomlinson** [comment]
> @fabistb @ssm3ll Get Actor Reminder API has been added in Dotnet sdk in 1.11. GetActorReminder returns IActorReminder Object if the reminder exists, **otherwise null**.


@WhitWaldo  Are we sure this behavior that I'm seeing in 1.15 isn't a recent regression as I never get `null` when calling `GetActorReminder` when the reminder doesn't exist.

**Comment by WhitWaldo** [comment]
@olitomlinson  Based on a really quick reading of the implementation, this starts with default values for each property and overrides them with the provided values from the response if available. While there are failovers that in theory could return null, I'm not sure it ever would take those paths.

Since there's interest in knowing if the reminder exists in advance, I think it's worth revisiting this logic, but we can do that in another issue.
