### ISSUE TITLE
When publishing a message allow setting Cloudevent attributes / Pub-Sub routing

### ISSUE THREAD

**Issue by mcrio** [dapr/dotnet-sdk#773]
## Proposal

Hi,

As we have the Pub/Sub routing feature, it'll be very useful to be able to set specific Cloudevent attributes when publishing the message.

At this point, the `Publish` implementation accepts only the message data, and there seems to be no other way to override the `event.type` or another attribute, other than making a direct HTTP request to the sidecar with the `application/cloudevents+json` raw data.

Another useful feature would be to specify tracing headers for scenarios like the outbox pattern where a separate process publishes the messages, in order to preserve correct tracing

**Comment by shobhitkasliwal-onbe** [comment]
@mcrio  - did you find a solution for this ?

I am using the Orchestrator pattern in my .NET  6 apps  and calling multiple services using the pubsub and would like to maintain the same traceid for tracing but it is generating a new traceid for each pubsub request. 

Service1 (Puts msg on queue) -> Service 2 Receives it -> Service 2 (Puts msg on queue as response) - > service 1 Receives it
... some business logic with wait for the response from service 2  ....
Service1 (Puts msg on queue) -> Service 3 Receives it -> Service 3 (Puts msg on queue  as response) - > service 1 Receives it
... some business logic with wait for the response from service 3  ....
Service1 (Puts msg on queue) -> Service 4 Receives it -> Service 4 (Puts msg on queue  as response) - > service 1 Receives it
.. and so on

I see a traceid being propogated from Service 1 to Service 2 for first call and then it generates a new for other calls. 

How can I make sure all services in this flow has same trace id ?

**Comment by mcrio** [comment]
Hi @shobhitkasliwal-onbe as described above my workaround was to not use the SDK but HttpClient directly and forwarding the trace-id within the `traceparent` header. Dapr will pick up that HTTP header.

**Comment by riezebosch** [comment]
> Hi @halspang
> 
> **Tracing:** Thanks. I'll check the docs you provided and get back to you.
> 
> **.Net SDK Publish()**
> 
> > To do this you just set the metadata isRawPayload in the client.PublishEventAsync(). Is this what you're looking for?
> 
> Unfortunatelly Pub/Sub routing does not work if `isRawPayload` is enabled. See demo repo here: https://github.com/mcrio/dapr-pub-sub-routing-problem I had a conversation with @pkedy about this.
> 
> The `PublishEventAsync` method does not seem to allow sending a Cloudevent as it'll create an envelope around the data and mark the content as `application/json`:
> 
> https://github.com/dapr/dotnet-sdk/blob/cc1b097991bbf268464b74935cdfbb35c0a26443/src/Dapr.Client/DaprClientGrpc.cs#L131
> 
> **My Workaround** Using plain HttpClient to send a request against the Dapr HTTP API:
> 
> ```
>                 var routingKey = "myroutingkey";
>                 var payload = new { Foo = "bar" };
>                 var cloudEvent = new { Type = routingKey, Data = payload };
>                 var requestContent = new StringContent(
>                     JsonSerializer.Serialize<object>(cloudEvent, jsonOptions),
>                     Encoding.UTF8,
>                     "application/cloudevents+json"
>                 );
>                 HttpResponseMessage response = await _httpClient.PostAsync(
>                     $"/v1.0/publish/{PubSubName}/{topicName}",
>                     requestContent
>                 ).ConfigureAwait(false);
> ```
> 
> It'll be great if we could use the DaprClient for that.
> 
> Let me know if I missed something.
> 
> Cheers

Same experience here, also came to the same conclusion. Would be awesome if the client was smart enough to recognize the input being a cloud event since the dapr component in the sidecar then uses it as-is. It also turns out to be impossible to hook into the process of the client being constructed to fix it ourselves.

**Comment by gdifilippo-ca** [comment]
Hi, aren't there any updates on this issue? I would like to use the "type" attribute of the CloudEvent envelope to do routing but it seems to me that currently, there is no way to override its default value of "com.dapr.event.sent" using the SDK, right?

**Comment by suraciii** [comment]
Some thoughts:

1. Add two new types, `CloudEvent` and `CloundEvent<TData>`, and change dapr client's internal behavior to attach `"application/cloudevents+json"` content type when publishing cloud events, like this:
```csharp
public class CloudEvent<TData>(TData data, string type, string subject = null, string source = null, string id = null) {};

public override Task PublishEventAsync<TData>(...)
{
    // ...
    return MakePublishRequest(pubsubName, topicName, content, null, data is CloudEvent ? Constants.ContentTypeCloudEvent : null, cancellationToken);
}

private async Task MakePublishRequest(
    string pubsubName,
    string topicName,
    ByteString content,
    Dictionary<string, string> metadata,
+   string dataContentType,
    CancellationToken cancellationToken)
{
    // ...
    if (content != null)
    {
        envelope.Data = content;
        envelope.DataContentType = dataContentType ?? Constants.ContentTypeApplicationJson;
    }
    // ...
}
```
usage:
```csharp
await daprClient.PublishEventAsync("my-pubsub", "my-topic", new CloudEvent<MyEvent>(data: myEvent, type: nameof(MyEvent)));
```  

2. Change/Add APIs to allow users to specify data content type manually:
``` csharp
public abstract Task PublishEventAsync<TData>(
    string pubsubName,
    string topicName,
    TData data,
    string dataContentType,
    CancellationToken cancellationToken = default);
```
usage:
```csharp
await daprClient.PublishEventAsync("my-pubsub", "my-topic", new myCloudEvent(data: , type: , ...), dataContentType: "application/cloudevents+json");
```

3. Or just make `DaprClientGrpc` public to let users extend it easier.

**Comment by yaron2** [comment]
@halspang why is this closed?

**Comment by ChristianWeyer** [comment]
Yes, pls re-open it. This is a really important addition.
Thanks! @halspang

**Comment by ChristianWeyer** [comment]
Ah, it seems it has already been merged @yaron2:
https://github.com/dapr/dotnet-sdk/pull/868

**Comment by ChristianWeyer** [comment]
> > For the tracing, this is all handled natively in .NET. You can use the system diagnostic activity: https://docs.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-instrumentation-walkthroughs
> 
> Just for the archive:
> 
> Regarding messaging outbox pattern and tracing, I was able to simply forward the `traceparent` header while publishing the message with the `HttpClient`. That made the whole execution path connect nicely:
> 
> ```
> Ingress > ServiceA > OutboxPublisher >
>       > Consumer1  
>       > Consumer2
> ```
> 
> Would be nice if we could do that using the DaprClient and not rely on a HttpClient but anyway seems to be working this way as well ;)

@mcrio 
Did you try to use DaprClient in the latest version for the correct end-to-end tracing?

**Comment by mcrio** [comment]
Hi @ChristianWeyer I haven't had yet the chance to try it out.

**Comment by ChristianWeyer** [comment]
Thanks!
Do you have the sample code for your HttpClient-based solution?

**Comment by mcrio** [comment]
Hi @ChristianWeyer 

Something along these lines:

```cs
// Dapr Json conventions
JsonSerializerOptions jsonOptions = new ();
jsonOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
jsonOptions.DictionaryKeyPolicy = JsonNamingPolicy.CamelCase;
jsonOptions.PropertyNameCaseInsensitive = true;

// `message` must be marked as object otherwise the serializer will serialize just the interface members
var cloudEvent = new { Type = routingKey, Data = (object)message };
string jsonCloudEvent = JsonSerializer.Serialize<object>(cloudEvent, jsonOptions);

var requestContent = new StringContent(
    jsonCloudEvent,
    Encoding.UTF8,
    "application/cloudevents+json"
);

var request = new HttpRequestMessage
{
    RequestUri = new Uri(
        $"/v1.0/publish/{pubSubName}/{topicName}",
        UriKind.Relative
    ),
    Method = HttpMethod.Post,
    Content = requestContent,
};
if (!string.IsNullOrWhiteSpace(traceIdentifier))
{
    request.Headers.Add("traceparent", traceIdentifier);
}

HttpResponseMessage response = await _httpClient.SendAsync(request).ConfigureAwait(false);
```

**Comment by ChristianWeyer** [comment]
> Hi @ChristianWeyer I haven't had yet the chance to try it out.

It is still unclear how to do end-to-end tracing as described here with the latest addition of CloudEvent support in DaprClient.
https://github.com/dapr/dapr/issues/4571

Any hints @halspang ?

Thanks!
