### ISSUE TITLE
Publishing raw messages in any serialization with dapr dotnet sdk

### ISSUE THREAD

**Issue by modabas** [dapr/dotnet-sdk#775]
This has been asked before in #718 , with dapr/dapr#3143 it's possible to publish raw messages in any serialization with dapr. 

With dotnet sdk, it's possible to add rawPayload tag to metadata to indicate this is a raw message:

```csharp

                var metadata = new System.Collections.Generic.Dictionary<string, string>();
                metadata.Add("rawPayload", "true");
                await client.PublishEventAsync<HelloRequest>(
                    "pubsub",
                    "SayHelloRaw",
                    new HelloRequest
                    {
                        Name = name
                    },
                    metadata
                );
```

However, it's not possible to change message content serialization (json by default) and content type info ("application/json" by default) sent to dapr.

Do you have plans to add this functionality to dotnet sdk?

**Comment by halspang** [comment]
We'll add a new method that will skip the json serialization portion and work on raw bytes instead.
