### ISSUE TITLE
SecretStoreProvider: Failed to init state store secretstores.local.file - invalid character 'ï'

### ISSUE THREAD

**Issue by francescocristallo** [dapr/dotnet-sdk#776]
I've followed the SecretStoreConfigurationProviderSampleexample here:
https://github.com/dapr/dotnet-sdk/tree/master/examples/AspNetCore/SecretStoreConfigurationProviderSample

but I can't make it work.
My steps:

I created a new Console App with .Net6 RC2 in Visual Studio 2022.
Dapr version:
CLI version: 1.4.0
Runtime version: 1.4.3

My minimum viable repo is here: https://github.com/francescocristallo/DaprLocalSecret

I open the cmd as Admin, type:
```
cd C:\Users\user\source\repos\DaprLocalSecret\DaprLocalSecret
dapr run --app-id DaprTest --components-path ./components/ -- dotnet run
```
The console starts Dapr but displays:

**"failed to init state store secretstores.local.file/ named demosecrets: invalid character 'ï' looking for beginning of value"**

I tried many combinations of relative paths, and moving around the secrets.json file, but it can never locate the file.
This happens with a new WebAPI project or Blazor Webassembly project as well.

I used Project Tye, with the same error.

I couldn't find any similar problem online, there must be something I'm missing or that I do wrong.

Could this be a .Net6 bug?

**Comment by halspang** [comment]
I can't access your repo, I get a 404. Is it private?

I ran the sample in our repo and it works for me. The error you're seeing is also a runtime error, not a .NET error.

**Comment by francescocristallo** [comment]
I accidentally set the repo as private, now is public.
I'll try to post this question in the main Dapr Issues page, it looks like is unrelated to the dotnet sdk
