### ISSUE TITLE
Can't  serialize dynamic object in actor

### ISSUE THREAD

**Issue by zsq1576154634** [dapr/dotnet-sdk#778]
## Steps to Reproduce the Problem
actor code
![image](https://user-images.githubusercontent.com/52565295/141073638-e621c0e7-7903-4d79-b0d1-2b76c6337665.png)
when I beg that Actor
![image](https://user-images.githubusercontent.com/52565295/141073763-0d4e0f27-4af4-4a08-b9f7-7c46f28b7485.png)
habs this error

 Dapr.Actors.ActorMethodInvocationException: Remote Actor Method Exception
       ---> Dapr.Actors.ActorInvokeException: Type '<>f__AnonymousType0`2[System.Int32,System.Int32]' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a parameterless constructor - all public members of the type will then be serialized, and no attributes will be required.

RELEASE NOTE:1.4

**Comment by halspang** [comment]
Actors use DataContractSerializer and inherit all of its behavior and limitations. This is not something we control inside of Dapr.

I don't suggest trying to use `dynamic` with actors.
