### ISSUE TITLE
Support Dapr for .NET 6 minimal API

### ISSUE THREAD

**Issue by rizamarhaban** [dapr/dotnet-sdk#780]
Using Dapr for minimal API. I tried and the service require to add controllers `services.AddControllers().AddDapr()`
I was wondering if we can just do `services.AddDapr()`  So no need to add controllers.

**Comment by yaron2** [comment]
Transfered to correct repo.

cc @rynowak

**Comment by halspang** [comment]
@rizamarhaban - What are you trying to add into your services? There is a separate method for the client if that's all you need. I believe this method is on top of controllers because we need controllers to setup the various Dapr endpoints.

**Comment by WhitWaldo** [comment]
I'm going to mark this as closed since it's getting to be an older ticket, but please feel free to re-open it if you have any follow-up questions.
