### ISSUE TITLE
Bulk State

### ISSUE THREAD

**Issue by dream2zz** [dapr/dotnet-sdk#785]
## Describe the proposal

need  some methods named "SaveBulkStateAsync" and "SaveBulkStateAndETagAsync" .

in other words, we think the method name should be paired.

**Comment by halspang** [comment]
Is this as an alternate to `ExecuteStateTransactionAsync` or something different? What's your use case here?

**Comment by Dream2zz** [comment]
yes, is as an alternate , is talking about  specification

**Comment by halspang** [comment]
@rynowak - What do you think of adding this? Technically, the Dapr runtime does support sending a list of requests to its `SaveState` API. Even in the SDK, we're just sending an array of a single request at a time.

This API does overlap with the transactional API, but it comes with less guarantees and opens up bulk APIs to people who don't want to use a transactional statestore. I think there's some value here, and it's a relatively small change.
