### ISSUE TITLE
reentrant actor question

### ISSUE THREAD

**Issue by aktxyz** [dapr/dotnet-sdk#792]
In the dapr doc info, they show some reentrant actor scenarios.  In these cases, the best I can tell from looking thru the code, is that the reentrant header id is automatically handled by the dapr-dotnet sdk?

```
ActorA -> ActorA
ActorA -> ActorB -> ActorA
```
https://docs.dapr.io/developing-applications/building-blocks/actors/actor-reentrancy/

Here is my question ... is this a valid scenario?

```
ActorA -> invoke some other dapr service passing the reentrant id (not an actor) -> ActorA
```

It seems like the dapr spec allows for this, as long as the header is passed to that last ActorA  call.
Does the dapr dotnet sdk support this?

or am I just way off base here.

**Comment by halspang** [comment]
You're correct that the headers need to be passed and that currently, the .NET SDK handles everything. I don't know how well it preserves the headers from the service invocations though. 

Have you tried this already? If it doesn't work we can look into what it would take to get it.

Or, as an alternative, you can define the service as ActorB instead, which would give you this out of the box.

**Comment by halspang** [comment]
@aktxyz - Were you able to find a solution that worked for you?

**Comment by aktxyz** [comment]
I did finally get around to trying this ... and it looks like the headers required for re-entrant actor calls are not getting passed along when there is a service invocation in the mix ... ie ... client -> actor(a) -> serviceinvocation -> actor(a)

Any thoughts on how to get access to the magic header info ... and then add to the actor call?
