### ISSUE TITLE
Pub/sub subscriber endpoint protect

### ISSUE THREAD

**Issue by ssm3ll** [dapr/dotnet-sdk#796]
Just wonder how Dapr guarantee that subscriber endpoint will be called only by Dapr sidecar and only if any event occurs on e.g. event hub side. Currently it's possible to call same endpoint using v1.0/invoke sidecar api so any other component can invoke subscriber endpoint. Let me explain:

we have appId: eventlistener with is called by subscriber component restricted by scope with route: /receiver
but I can also directly call same endpoint using http://localhost:<dap_port>/v1.0/invoke/eventlistener/method/receiver

I know that I can use oAuth midlewarfe and DAPR/API tokens but in case of called endpoint there is no difference as in both cases it was called by dapr sidercar (pub.sub or service invocation).

**Comment by halspang** [comment]
@ssm3ll - Thanks for opening this issue! I think you have a couple ways you can do this:

1. Use the Dapr/API tokens, but deploy your application in a configuration that can use unique tokens. If you deploy your subscribing app in its own sidecar, they could have a unique secret. Thus, only requests from that sidecar should be accepted.
2. You can try using access control lists: https://docs.dapr.io/operations/configuration/invoke-allowlist/

Other than these options, I think it would be best for you to cut an issue to the runtime. The responsibility of the SDK is to provide an endpoint that can be called by dapr. If we want different security protocols, we should start at the runtime and work backwards from there.

**Comment by halspang** [comment]
@ssm3ll - This has been stale for a while. Do you need anything else from this issue?

**Comment by ssm3ll** [comment]
@halspang my apologies for delay response. thanks for you answer. I am going to close this issue
