### ISSUE TITLE
StateManager.RemoveStateAsync inside a run-once reminder is logging unexpected 404 errors

### ISSUE THREAD

**Issue by repne** [dapr/dotnet-sdk#797]
This is happening in Dotnet 6 using Dapr.Actors.AspNetCore 1.5.0.

## Expected Behavior

I have an actor that removes its own state after some time using a reminder:

```
  await RegisterReminderAsync(
      CleanUpReminderName,
      null,
      TimeSpan.FromDays(2),
      TimeSpan.FromMilliseconds(-1));
```
and in the actual reminder code, after checking that the state exist I have:
```
await StateManager.RemoveStateAsync(StateName);
```

The expectation is that the state is deleted and no errors are logged.

## Actual Behavior

The state is correctly deleted but I get a spike of 404 errors with the format:

`DELETE http://localhost:<daprPort>/v1.0/actors/<actorType>`

No actor id, nor anything else, the URL simply looks truncated.

**Comment by halspang** [comment]
@repne - Thanks for opening this issue! Where does that error message come from? Is your application logging it, or is the dapr runtime logging it?

**Comment by repne** [comment]
> @repne - Thanks for opening this issue! Where does that error message come from? Is your application logging it, or is the dapr runtime logging it?

We are seeing this in appinsights using the appinsights dotnet sdk (not dapr own telemetry implementation). I will have more details once I'm back from holiday early January. Thanks for looking into this.

**Comment by halspang** [comment]
@repne - Are you still having trouble here/can you provide a repro?

**Comment by repne** [comment]
I haven't seen the issue since 1.7 I think. We can close this.
