### ISSUE TITLE
Is Grpc Proxy Support available in the SDK?

### ISSUE THREAD

**Issue by Sen-Gupta** [dapr/dotnet-sdk#829]
## Is Grpc Proxy  Support Available?

Please help us understand if Grpc Proxy Support is available in dotnet dapr sdk?

As described here:
https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/

We tried to follow the instruction/steps shown on this  video but  the client fails to hit Grpc Port.
https://www.youtube.com/watch?v=Q2xS153IofM

We are on DotNet 6.0.100 and Version 17.1.0 Preview 3.0

**Comment by halspang** [comment]
Yes it is, we just don't have an example for proxying. You'd use this method to create your invoker which will handle passing the header for you:

https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Client/DaprClient.cs#L133
