### ISSUE TITLE
App API Token support

### ISSUE THREAD

**Issue by gdlcf88** [dapr/dotnet-sdk#835]
https://docs.dapr.io/operations/security/app-api-token/

Hi, can we support App API Token in .NET SDK? :)

https://github.com/dapr/go-sdk/blob/40d8a4eabe2bc6244a0de6789f74d2fe6e302db9/service/http/service.go#L53
https://github.com/dapr/go-sdk/blob/40d8a4eabe2bc6244a0de6789f74d2fe6e302db9/service/http/invoke.go#L40-L46

**Comment by JadynWong** [comment]
Sdk contains authentication processing for requests from Dapr.
https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.AspNetCore/DaprAuthenticationHandler.cs

According to the documentation, `DaprAuthenticationOptions.Token` should read the value of the `APP_API_TOKEN` environment variable, but currently it reads the value of the `DAPR_API_TOKEN` environment variable.

Go sdk and php sdk both do this.
https://github.com/dapr/php-sdk/blob/f0d66c38fbe7ade9b7f51a432fa1f7ed1f015bf8/src/lib/Middleware/Defaults/TokenAuth.php#L20

https://github.com/dapr/go-sdk/blob/40d8a4eabe2bc6244a0de6789f74d2fe6e302db9/service/http/service.go#L53
