### ISSUE TITLE
state store query API: validate changes in the syntax of query JSON

### ISSUE THREAD

**Issue by dmitsh** [dapr/dotnet-sdk#837]
Per work items below, the syntax of the state query JSON has been slightly changed, to make it more intuitive:
https://github.com/dapr/components-contrib/issues/1490
https://github.com/dapr/components-contrib/pull/1491
https://github.com/dapr/components-contrib/pull/1500
https://github.com/dapr/docs/pull/2195

Please validate this change in the SDK, and fix if necessary.

**Comment by halspang** [comment]
Validated the Query API still works. Utilized a Cosmos backend for the test and was able to query items without providing/using `value`.
