### ISSUE TITLE
404 Not Found on Dapr net6.0 web application

### ISSUE THREAD

**Issue by jsacapdev** [dapr/dotnet-sdk#851]
## Expected Behavior

Calling the route `GET http://127.0.0.1:5000/17` should result in a 200 type response

## Actual Behavior

The following is returned back from the Visual Studio Code [Rest Client Plugin](https://marketplace.visualstudio.com/items?itemName=humao.rest-client):

```
HTTP/1.1 404 Not Found
Content-Length: 0
Connection: close
Date: Mon, 28 Mar 2022 15:33:44 GMT
Server: Kestrel
```

## Steps to Reproduce the Problem

1. Clone this sample [repository](https://github.com/jsacapdev/az.container.apps)
2. Open the root in Visual Studio Code
3. Run the application using F5
4. Call the route. Note the repository has a sample [http](https://github.com/jsacapdev/az.container.apps/blob/main/test/dev.http)  file that can be used.

**Comment by JadynWong** [comment]
https://github.com/jsacapdev/az.container.apps/blob/3958ada03f356630a46079860f49819bb22c2e3e/src/ControllerSample/Controllers/SampleController.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L10

You can remove the `[Route("[controller]")]` attribute or change the URL like this `http://127.0.0.1:5000/Sample/deposit`.

**Comment by jsacapdev** [comment]
thanks @JadynWong
