### ISSUE TITLE
Dapr dependency only dotnetcore 3.1

### ISSUE THREAD

**Issue by NJadeRabbit** [dapr/dotnet-sdk#862]
## Dapr dependency only dotnetcore 3.1?
Although it can also be used, it feels strange .
![1649838394](https://user-images.githubusercontent.com/48701698/163133807-7e85549d-18c0-426c-8881-34edd3fa4500.jpg)

Dapr  dependency also dotnet 5 and dotnet 6.
Please update. Thank you!

**Comment by NJadeRabbit** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.1;netcoreapp3.1;net5.0;net6.0</TargetFrameworks>
    </PropertyGroup>

    ...
</Project>
```

**Comment by halspang** [comment]
@NJadeRabbit - Thanks for opening this issue!

As an SDK, we made the decision to not support `netstandard2.x`. This is due primarily to a lack of ability to chose when we can deprecate that. Technically, `netstandard2.1` is no longer receiving support as of May 2021 (if I'm reading things correctly).

That, and we also had to make the decision of what to support based on how much effort it is. Right now, we support `netcore3.1`, `net5.0`, and `net6.0`.

Do you have a use case for `netstandard2.1`?

**Comment by NJadeRabbit** [comment]
> @NJadeRabbit - Thanks for opening this issue!
> 
> As an SDK, we made the decision to not support `netstandard2.x`. This is due primarily to a lack of ability to chose when we can deprecate that. Technically, `netstandard2.1` is no longer receiving support as of May 2021 (if I'm reading things correctly).
> 
> That, and we also had to make the decision of what to support based on how much effort it is. Right now, we support `netcore3.1`, `net5.0`, and `net6.0`.
> 
> Do you have a use case for `netstandard2.1`?

Sorry, I accidentally wrote an extra netstandard2.1 . I don't have a use case for it.
I just want to see dapr on nuget Net SDK dependency is not just dotnetcore3.1. Dotnet5 and dotnet6 should also be included
___

I know it already supports dotnet5 and dotnet6, but for OCD like me, looking at the dapr SDK on nuget, it only has dotnetcore 3.1. It's very uncomfortable.

**Comment by halspang** [comment]
Yup, it may be less fun to look at but since we don't do anything framework specific (like a net6 only feature), we get no benefit from building all the images. It just makes our build/CI take longer and use more CPU cycles that we don't need.

Closing this issue as we don't plan on adding the other build targets.
