### ISSUE TITLE
Add documentation about configuration API (subscribe configuration method) - Dotnet SDK

### ISSUE THREAD

**Issue by amulyavarote** [dapr/dotnet-sdk#872]
**What content needs to be created or modified?**
Add information about the configuration API (subscribe configuration method) for dotnet sdk.

**Describe the solution you'd like**

**Where should the new material be placed?**
Under sdk documentation

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by halspang** [comment]
This is done: https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-client/#get-configuration-keys-alpha
