### ISSUE TITLE
[proposal]Subscription supports adding custom metadata

### ISSUE THREAD

**Issue by saber-wang** [dapr/dotnet-sdk#873]
## Describe the proposal
https://github.com/dapr/dotnet-sdk/blob/291f73758d9231e72198c124c6286643fc8795df/src/Dapr.AspNetCore/TopicAttribute.cs#L22

Incoming metadata required for custom subscriptions

For example, rabbitmq use topic exchange to route messages
```
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order_pub_sub
spec:
  topic: B
  route: /B
  pubsubname: pubsub
  metadata:
    routingKey: keyA
```

Given c#'s Attribute limitations, can  design to add an independent 'TopicMetadataAttribute'`
Examples:
```
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class TopicMetadataAttribute : Attribute
    {
        public string? Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public TopicMetadataAttribute(string id,string name, string value)
        {
            Id = id;
            Name=name;
            Value = value;
        }

        public TopicMetadataAttribute(string name, string value)
        {
            Name=name;
            Value = value;
        }
    }
```
`ITopicMetadata` add `MetadataIds`(array) to point to ` TopicMetadataAttribute.Id`

Use example
```
        [Topic("pubsub", "topic", new string[2] { "m1", "m2" })]
        [Topic("pubsub", "topic2", new string[1] { "m2" })]
        [HttpPost("subscription")]
        [TopicMetadata("m1", "n1", "v1")]
        [TopicMetadata("m2", "n2", "v1")]
        public void Subscription()
          {
             //code
          }
```
```
[{
        "topic": "topic",
        "pubsubName": "pubsub",
        "route": "subscription",
        "metadata": {
            "n1": "v1",
            "n2": "v1"
        }
    },
    {
        "topic": "topic2",
        "pubsubName": "pubsub",
        "route": "subscription",
        "metadata": {
            "n1": "v1",
            "RawPayload": "true"
        }
    }]
```

Automatically attach these metadata when `IOriginalTopicMetadata.Id` is null.
Use example
```
        [Topic("pubsub", "topic"})]
        [Topic("pubsub", "topic2")]
        [HttpPost("subscription")]
        [TopicMetadata("n1", "v1")]
        [TopicMetadata("n2", "v1")]
        public void Subscription()
          {
             //code
          }
```
result:
```
[{
        "topic": "topic",
        "pubsubName": "pubsub",
        "route": "subscription",
        "metadata": {
            "n1": "v1",
            "n2": "v1"
        }
    },
    {
        "topic": "topic2",
        "pubsubName": "pubsub",
        "route": "subscription",
        "metadata": {
            "n1": "v1",
            "n2": "v1"
        }
    }]
```

When multiple values are set in one metadata of topic, the set delimiter is used to convert to one value
```
        [Topic("pubsub", "topic",metadataSeparator:","})]
        [HttpPost("subscription")]
        [TopicMetadata("n1", "v1")]
        [TopicMetadata("n1", "v2")]
        public void Subscription()
          {
             //code
          }
```
result:
```
[{
        "topic": "topic",
        "pubsubName": "pubsub",
        "route": "subscription",
        "metadata": {
            "n1": "v1,v2"
        }
    }]
```

**Comment by saber-wang** [comment]
Given c#'s property limitations, can  design to add an independent 'TopicMetadataAttribute'`
Examples:
```
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class TopicMetadataAttribute : Attribute
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public TopicMetadataAttribute(string id,string name, string value)
        {
            Id = id;
            Name=name;
            Value = value;
        }
    }
```
`ITopicMetadata` add `MetadataIds`(array) to point to ` TopicMetadataAttribute.Id`

Use example
```
        [Topic("pubsub", "topic", MetadataIds = new string[2] { "m1", "m2" })]
        [Topic("pubsub", "topic2", MetadataIds = new string[1] { "m2" })]
        [HttpPost("subscription")]
        [TopicMetadataAttribute("m1", "n1", "v1")]
        [TopicMetadataAttribute("m2", "n2", "v1")]
        public void Subscription()
          {
             //code
          }
```

**Comment by saber-wang** [comment]
@halspang Can it be implemented?

**Comment by halspang** [comment]
@saber-wang - I'm a little confused as to what this is trying to accomplish. Can I have a full example of what this would do/is for?

**Comment by saber-wang** [comment]
@halspang 
Simply put, it is to add more diversified data for subscription

At present, the metadata to be added is the `routingkey` of `rabbitmq`

**Comment by saber-wang** [comment]
@halspang  I created a merge request. You can check it.

**Comment by halspang** [comment]
@saber-wang - Thanks for adding the PR, but I'm still not super sure how it really changes anything. The subscription endpoint code doesn't seem to be referencing it except to add it to the class, but it doesn't appear used after that.

The goal is to be able to use this metadata as routing at the endpoint level? If so, I don't think it's hooked in quite like that. If that's the end goal, I'd just have an endpoint that inspected the event and called whatever method I was looking for.

If I'm not understanding this correctly, do you think you can modify the pubsub example? I think I need to see this running in an app to fully understand it.

**Comment by saber-wang** [comment]
@halspang It mainly realizes the routingkey function in this [document](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-rabbitmq/#use-topic-exchange-to-route-messages). the current  publishing already supports adding metadata, but the subscription lacks any entry to add relevant metadata.of course, we can also implement this function like rawpayload https://github.com/dapr/dotnet-sdk/blob/0046507076f52c367651a3bc5c66338131e1977c/src/Dapr.AspNetCore/IRawTopicMetadata.cs#L19



All of them are designed to provide more metadata content for dapr
https://github.com/saber-wang/dapr-dotnet-sdk/blob/master/src/Dapr.AspNetCore/DaprEndpointRouteBuilderExtensions.cs#L130

**Comment by saber-wang** [comment]
@halspang At present, it is difficult to express metadata under V2 routing.
for example,this will be understood as setting metadata for each endpoint.
```
        [Topic("pubsub", "withdraw")]
        [TopicMetadata("routingKey", "keyB")]
        [HttpPost("withdraw")]
        public async Task<ActionResult<Account>> Withdraw(Transaction transaction, [FromServices] DaprClient daprClient)
        {
           //code
        }

        [Topic("pubsub", "withdraw", "event.type ==\"withdraw.v2\"", 1)]
        [TopicMetadata("routingKey", "keyA")]
        [HttpPost("withdraw.v2")]
        public async Task<ActionResult<Account>> WithdrawV2(TransactionV2 transaction, [FromServices] DaprClient daprClient)
        {
            //code
        }
```
In fact, the metadata of a topic only needs to be set once.
```
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order_pub_sub
spec:
  topic: B
  route: /B
  pubsubname: pubsub
  metadata:
    routingKey: keyA,keyB
```

**Comment by saber-wang** [comment]
@halspang  @rynowak Any better advice?😖

**Comment by saber-wang** [comment]
@rynowak  The current problem is how to add more diverse data for subscriptions from applications, just like 'rawpayload'.Is `IEndpointSelectorPolicy` used to handle routing, or do I have problems understanding `IEndpointSelectorPolicy`?

**Comment by saber-wang** [comment]
@halspang The dapr runtime itself supports adding metadata from outside components, but many components do not use these metadata. See my proposal in [dapr ](https://github.com/dapr/dapr/issues/4694)

https://github.com/dapr/components-contrib/blob/6c7ff60c9ea0d98f1d9c0ed19b26525eb3e67e07/pubsub/requests.go#L26-L28
```
// SubscribeRequest is the request to subscribe to a topic.
type SubscribeRequest struct {
	Topic    string            `json:"topic"`
	Metadata map[string]string `json:"metadata"`
}
```

**Comment by rynowak** [comment]
Thanks @saber-wang for the explanation - this makes sense to me now, and I agree. We should add support for passing through metadata to Dapr with attributes 👍

**Comment by saber-wang** [comment]
@rynowak However, I find it very difficult to express metadata using attributes in V2 routing

You can view previous discussions https://github.com/dapr/dotnet-sdk/issues/873#issuecomment-1140222734  and RP #876 😖

**Comment by saber-wang** [comment]
@rynowak @halspang RP #876  can check.
