### ISSUE TITLE
Invoke with method containing query string needs to be /?

### ISSUE THREAD

**Issue by penfold** [dapr/dotnet-sdk#902]
## Expected Behavior

The method parameter passed to DaprClient.InvokeMethod***Async with query parameters should work with 'method?param1=123'.

## Actual Behavior

Using 'method?param1=123' leads to an internal error reported back

Using the method parameter method/?param1=123' works.

## Steps to Reproduce the Problem

CLI version: 1.7.1
Runtime version: 1.7.4

**Comment by halspang** [comment]
@penfold - Thanks for opening this issue! Can you please paste the error you get here?

**Comment by halspang** [comment]
@penfold - I tried to repro this and found it works fine for me:

Calls:
```
➜  ~/Projects/TestBed/TestBed.Web git:(master) ✗ 
$ curl 'http://localhost:22222/api/service/testParam?test=123'                           
➜  ~/Projects/TestBed/TestBed.Web git:(master) ✗ 
$ curl 'http://localhost:60541/v1.0/invoke/testbed/method/api/service/testParam?test=456'
```

App response:
```
== APP == info: TestBed.Web.Controllers.ServiceController[0]
== APP ==       Received: 123
== APP == info: TestBed.Web.Controllers.ServiceController[0]
== APP ==       Received: 456
```

Code:
```csharp
[HttpGet("testParam")]
public Task TestParam([FromQuery] string test)
{
    logger.LogInformation($"Received: {test}");
    return Task.CompletedTask;
}
```

What does your endpoint setup look like?

**Comment by halspang** [comment]
@penfold - Are you able to provide a repro for this?

**Comment by ekjuanrejon** [comment]
Having the same issue but with the following query string

filter[policy]=12345
@halspang

**Comment by philliphoff** [comment]
@penfold @ekjuanrejon Are you still running into this issue?  I've successfully used both `method?name=value` and `method/?name=value` in `InvokeMethodAsync()` calls, for both `GET` and `POST` methods, with the latest (1.11.0) version of the Dapr Client SDK.

If either of you are still having issues, could you post a more complete repro?

**Comment by ekjuanrejon** [comment]
Reverted to using http client.

**Comment by WhitWaldo** [comment]
@penfold This scenario is covered in a [unit test here](https://github.com/dapr/dotnet-sdk/blob/23e8df02953c2cf4ad8bc7b5023978f16a92f0e1/test/Dapr.Client.Test/DaprClientTest.InvokeMethodAsync.cs#L509). 

Given the age of this issue, I'm going to go ahead and mark it closed as resolved, but if you're still experiencing an issue, please feel free to re-open or open a new issue.
