### ISSUE TITLE
Relationship with cloudevents/sdk-csharp

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#91]
I'm digging through https://github.com/dapr/dotnet-sdk/issues/74 - and there's a bunch of non-trivial stuff that CloudEvents do. 

It's going to be easy to do #74 because the scope is very limited - but for the longer term, have you had any conversations with the maintainers of that project? Someone who *wants* to process CloudEvents other than their payload will likely end up using it - I'm hoping we can make that a good experience - however I haven't had the time to go deep into it.

This might be something for @davidfowl and I to chase.

**Comment by msfussell** [comment]
Closing issue. No work needed here
