### ISSUE TITLE
Moar gRPC?

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#92]
Now that we've got a gRPC client - do we want to take a more thorough look at the experience for ASP.NET Core + gRPC + Dapr? I happen to [know a guy](https://ndcsydney.com/talk/grpc-for-asp-net-core-a-new-framework-for-lightspeed-web-apis/).

At this minimum this would probably be a review of some of the practices + more samples, at the maximum we might identify more features and integration points.

**Comment by jeastham1993** [comment]
@amanbha  Not familiar enough with gRPC in dotnet core to help with a gRPC wrapper, but happy to help with the grunt work on the restructuring on the client packages if needed.

**Comment by amanbha** [comment]
Closed by https://github.com/dapr/dotnet-sdk/pull/244
