### ISSUE TITLE
SDK code doesn't reflect renaming on UnlockResponse.Status

### ISSUE THREAD

**Issue by tmacam** [dapr/dotnet-sdk#921]
PR dapr/dapr#4989 (issue dapr/dapr#4988) updated the names of some enums in `UnlockResponse.Status` ProtoBuff definition:

* `LOCK_UNEXIST` became `LOCK_DOES_NOT_EXIST `
* `LOCK_BELONG_TO_OTHERS`  became `LOCK_BELONGS_TO_OTHERS`

Code in clients SDKs needs to be updated to account for this modification. 

This modification should not cause any change in over-the-wire encoding but will cause problems when regenerating language-dependent code from those definitions.

Notice: The Distributed Lock API is an Alpha version and is subject to change. As such, I am unsure of the need to have this added to this SDK Release notes.

## Release notes

* **FIX** Addresses some typo and grammar issues in UnlockReponse.Status struct. Although Distributed Lock API is alpha version, this is a breaking change.

**Comment by halspang** [comment]
@tmacam - Can you add a release note for this? It is an alpha version, but it'll have a breaking change here. That's fine for alpha APIs but we should let people know that in the release notes so they aren't surprised.
