### ISSUE TITLE
How to get all entries using QueryStateAsync?

### ISSUE THREAD

**Issue by luboshl** [dapr/dotnet-sdk#945]
I use state store to save and get items to/from `Redis` using .NET client, it works fine. Now I need to `get all entries with query state`. I try different forms of query:

```csharp
var query1 = """
    {
      "filter": {}
    }
    """;
var query2 = """
    "filter": {}
    """;
var query3 = "{}";

var queryResult = await daprClient.QueryStateAsync<Product>("statestore", query, cancellationToken: ct);
```

But I constantly get `failed query in state store statestore: query index not found`:

```
Dapr.DaprException: Query state operation failed: the Dapr endpointed indicated a failure. See InnerException for details.
       ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="failed query in state store statestore: query index not found")
         at Dapr.Client.DaprClientGrpc.QueryStateAsync[TValue](String storeName, String jsonQuery, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
```

What is the correct form for the query? Or do I need to initialize the store? I haven't found anytning about that in the documentation.

**Comment by halspang** [comment]
From what I see in the docs, it looks like Redis requires query indices which need to be setup in the yaml.

https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/#querying-json-objects-optional

Closing this as it's a component question.
