### ISSUE TITLE
Unable to send SNS with MessageAttribute in InvokingBindingAsync()

### ISSUE THREAD

**Issue by SPrabaga** [dapr/dotnet-sdk#957]
We need to send sns notification with message attribute also on daprClient.InvokingBindingAsync(), to filter sns message based on message attribute filter policy subscription. could you please help.

**Comment by SPrabaga** [comment]
Could you please confirm message attribute added on daprClient.InvokingBindingAsync() method Request. Like this 
**Request:**
request.MessageAttributes.Add(
    "SNSType",
    new MessageAttributeValue()
    {
        Type = "String",
        Value = "SNS"
    }); 
**Response:**
    For the Subscription filter policy. Like this on AWS
{
  "SNSType": [
    "Type ":"String"
    "Value":" SNS"
  ]
}
    
    Could you please update asap. Thanks

**Comment by halspang** [comment]
The InvokeBinding call just takes your provided object/data (serialized to json if an object) and sends it to the component. So if you're encoding that into your request object, it should be fine.

If you're asking if the `BindingRequest` object has a `MessageAttributes` field. It does not. Bindings are generic and we don't have anything tech specific in the object.

**Comment by halspang** [comment]
@SPrabaga - Do you need anything else here?

**Comment by halspang** [comment]
I'm going to close this issue, feel free to reopen if you need more help.
