### ISSUE TITLE
Introduce DOTNET version specific versions

### ISSUE THREAD

**Issue by bobbyangers** [dapr/dotnet-sdk#985]
Although technically `dotnetcore3.1` is compiler compatible with `net5`, `net6`, `net7`, there are some differences, especially regarding the referenced **nuget** packages.

This said with the battery of tests that is in this project, it would make sense to compile against each framework individually and make the specific version available.

By adding these sections where appropriate in the `.csproj` this can be achieve.

p.s.  `net5` is no longer supported by Microsoft since April 2022

```
<TargetFrameworks>netcoreapp3.1;net5;net6;net7</TargetFrameworks>
```
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.2" />
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.1' ">
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net5' ">
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net6' ">
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.1" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net7' ">
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
  </ItemGroup>
```

**Comment by WhitWaldo** [comment]
I'm going to close this simply because like in the linked PR, the client is currently targeting .NET 6 and .NET 8 (and .NET 7 for workflows) and that itself will shift with the .NET 9 release.
